### PR TITLE
Experimental wrapper over SpaCy

### PR DESCRIPTION
**Pull request by alvations**
This should automate installation of spacy.

```
pip install -U nltk[spacy] 
```

(Note: The usual `pip install -U nltk[all]` would also install SpaCy.)

And to use, the `from nltk import astronaut` line must come first:

```python
>>> from nltk import astronaut 
>>> from nltk import word_tokenize, pos_tag

>>> word_tokenize("how are you? I'm fine. Thank you")
['how', 'are', 'you', '?', 'I', "'m", 'fine', '.', 'Thank', 'you']

>>> pos_tag(word_tokenize("how are you? I'm fine. Thank you"))
[('how', 'WRB'), ('are', 'VBP'), ('you', 'PRP'), ('?', '.'), ('I', 'PRP'), ("'", "''"), ('m', 'VBZ'), ('fine', 'JJ'), ('.', '.'), ('Thank', 'VBP'), ('you', 'PRP')]

>>> word_tokenize
<function nltk.astronaut.<lambda>(input)>

>>> pos_tag
<function nltk.astronaut.<lambda>(input)>
```

### CODE REVIEW

**Comment by iliakur** [comment]
Sorry to be a downer, but we're adding a layer of abstraction here and there's a price for that.
Could you give a short cost-benefit summary of this change?

**Comment by alvations** [comment]
It's some out of the blue idea, purely thought experiment =)

My thought was to get something for easy benchmarking for the use of something like this, esp. in a specialize CI workflows on specific branch. Same abstraction/overloading idea can be used to overwrite the default `word_tokenize` and `pos_tag` for external packages too, e.g. new languages can use similar `override_model` to globally change the commonly used NLTK's function.


**Pros:**
 - easy benchmarking
 - general workflow to extend for other external overriding

**Cons:**
 - additional dependencies
 - not even sure who would use something like this ;P

Anyone can think/come up with more pros/cons?

**Comment by alvations** [comment]
After sleeping through the idea, it's a rather bizarre one, with the 10MB, 90MB and >700MB models from spacy and for multiple languages. Maybe it's a bad idea to naively overwrite with a single model. 

But something for benchmarking across tools would be nice. Maybe a better idea/proposal another time.

**Comment by iliakur** [comment]
I like that you tried it out :) Sometimes that's the only way to scratch an itch and see if it's real.

Sorry for jumping right away with the criticism. Maybe we can mark these PRs with a label or a WIP tag so that we all know when we're just messing around in a sandbox?

**Pull request closed without merging**
