### PR TITLE
nkjp reader

### PR DESCRIPTION
**Pull request by ducki13**
Reader of The National Corpus of Polish

### CODE REVIEW

**Comment by stevenbird** [comment]
Thanks @ducki13. I think it would be good to include the million-word subcorpus with NLTK's corpus collection, and to add an entry for it in the [corpus interface](https://github.com/nltk/nltk/blob/develop/nltk/corpus/__init__.py). What do you think?

**Comment by ducki13** [comment]
Hello stevenbird. I am very glad that you want my code to be a part of NLTK :) I've already commited an entry. Is anything else what is necessary for right submission of NKJP?

**Comment by stevenbird** [comment]
Nice work @ducki13, and I liked the decorator. We should consider using that elsewhere. I've tested this and will merge it now. Shall we add the million-word subcorpus to NLTK's corpus collection?

**Comment by ducki13** [comment]
Yes, I'd like to submit the corpus and I've already made the pull request with NKJP, here is the link: https://github.com/nltk/nltk_data/pull/17 . Data is submited in taz.bz extension, because size of zip package was too big to make a commit, I wrote about this problem here: https://groups.google.com/forum/#!topic/nltk-dev/VMMCXejQJMQ .

**Pull request merged**
