### PR TITLE
Update Travis CI matrix

### PR DESCRIPTION
**Pull request by kevin-brown**
- [x] Remove sudo from Python 3.7 builds
- [ ] Test on Python 3.4

### CODE REVIEW

**Comment by alvations** [comment]
@kevin-brown Thanks for the contribution! 

I think py3.4 was purposely dropped to minimize tests and also encourage people to move on to newer Python3 versions. Could you revise your commits and remove the Py3.4 tests?

**Comment by kevin-brown** [comment]
I added Python 3.4 to the testing matrix because it looks like NLTK officially supports Python 3.4. While I'm in favor of removing it if it's no longer supported, we should probably also remove it from the other places where it is referenced:

* https://github.com/nltk/nltk/blob/399343024888e73e8714203738ea826e1224489d/setup.py#L54
* https://github.com/nltk/nltk/blob/399343024888e73e8714203738ea826e1224489d/setup.py#L83
* https://github.com/nltk/nltk/blob/399343024888e73e8714203738ea826e1224489d/web/install.rst#L4

Otherwise I'm hesitant to recommend that we don't test on Python 3.4 when it's a version of Python that NLTK claims to officially support.

**Comment by alvations** [comment]
@stevenbird could we drop support for Python 3.4? If so, @kevin-brown do you mind removing that from the `setup.py` and `install.rst`?

**Comment by stevenbird** [comment]
@kevin-brown: ready for you to drop the change concerning Python 3.4 from your PR

**Comment by kevin-brown** [comment]
Sorry for the delay. I dropped Python 3.4 so now it's just the changes to the Python 3.7 builds.

**Review by alvations — APPROVED** [review]
Removing sudo from Travis =)

**Comment by stevenbird** [comment]
Thanks @kevin-brown, @alvations

**Pull request merged**
