### PR TITLE
Fix a bug that left out the last section/heading.

### PR DESCRIPTION
**Pull request by elespike**
Also refactored the logic a bit.

Here's an alternative using `itertools.groupby`, in case you prefer it:
```python
sections, block = list(), list()
for k, g in groupby(self.parser.parse(stream.read()), key=lambda t: t.level == 0 and t.type == 'heading_open'):
    if k or block:
        block.extend(g)
    if not k and block:
        sections.append(block)
        block = list()
```

### CODE REVIEW

**Comment by tomaarsen** [comment]
Hey!

Can we get a simple test for this? I'm assuming that this is reasonably doable. You could put the tests in [nltk/test/corpus.doctest](https://github.com/nltk/nltk/blob/develop/nltk/test/corpus.doctest) or [nltk/test/unit/test_corpora.py](https://github.com/nltk/nltk/blob/develop/nltk/test/unit/test_corpora.py), I'll leave the choice to your judgement.
If needed, you can put a markdown file in [nltk/test/unit/files](https://github.com/nltk/nltk/tree/develop/nltk/test/unit/files) that can be read with the markdown reader.

**Comment by elespike** [comment]
Hi, @tomaarsen 

Thanks for taking a look! No problem, I'll add tests. =)

~Out of curiosity, are the doctests published as documents anywhere? There's a lot of great info in there.~ [found them](https://www.nltk.org/howto.html)!
To confirm: if I choose doctests, is it still ok to add files at `nltk/test/unit/files`, or is that only for unit tests?

**Comment by tomaarsen** [comment]
On further glance, it seems like `nltk/test/unit/files` is currently just used for twitter tests. If it's not too many files that you intend on adding, then you can just add them directly to `nltk/test`. I see there's already some files there for testing, like `floresta.txt`, `onto1.fol` and `sem3.cfg`.

And I see that you found the documents! The current setup is far from ideal to be honest, as there's no separation between documentation and tests, so there are plenty of arbitrary tests in the how-to pages.

**Comment by elespike** [comment]
Understood! I've started writing some documentation-style tests, so far only using inline data as done [here](https://www.nltk.org/howto/corpus.html#plaintext-corpus-reader).

Another question: this `CategorizedMarkdownCorpusReader` class has some external dependencies, all of which are python packages. Should I actually add them to `tox.ini` as mentioned at the very bottom of [this file](https://github.com/nltk/nltk/blob/develop/web/dev/local_testing.rst)?

**Comment by tomaarsen** [comment]
@elespike I'm a bit surprised the CI tests are passing currently. Locally I have issues unless I install these packages:
- ``markdown-it-py``
- ``mdit-py-plugins``
- ``mdit-plain``
- `pyyaml`

I'll add them myself, as this is looking good, and I want to release a new version soon :)

**Comment by tomaarsen** [comment]
I see this is causing some issues in the CI: `mdit-plain` doesn't work with Python 3.7. I want to keep Python 3.7 support for another 6 months, so this is a bit problematic.

**Comment by elespike** [comment]
I'll have a look today. That's my own package and I think it might be just a walrus operator. 😆

**Comment by elespike** [comment]
@tomaarsen, please try again. I verified that `mdit-plain` didn't actually depend on Python 3.8 and uploaded a new release that will install and run on 3.7:
https://pypi.org/project/mdit-plain/1.0.1/ (https://github.com/elespike/mdit_plain/commit/218934eafd04725ecfdbf1026bc44ae4ecd0eedc)

**Comment by tomaarsen** [comment]
Wonderful! Appreciate it :)

**Pull request merged**
