### PR TITLE
Change English code from 'en' to 'eng' and a bug in lemma count() fun…

### PR DESCRIPTION
**Pull request by letuananh**
Change English code from 'en' to 'eng' and a bug in lemma count() function (currently lemma counting only works in English)

### CODE REVIEW

**Comment by stevenbird** [comment]
Why do you propose to change this code from ISO 639-1?

**Comment by alvations** [comment]
I think it's because Open Multilingual Wordnet is using the 3 characters language code.

**Comment by stevenbird** [comment]
Thanks @alvations. @fcbond do you have any advice please?

**Comment by fcbond** [comment]
G'day,

as Liling said, all the languages except English use the three letter
codes.   As English is the default, and this doesn't change, almost no
behaviour changes here.  And the bug in lemma.count() makes it hard to
write monolingual applications.

On Sat, Sep 5, 2015 at 12:34 AM, Steven Bird notifications@github.com
wrote:

> Thanks @alvations https://github.com/alvations. @fcbond
> https://github.com/fcbond do you have any advice please?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nltk/nltk/pull/1107#issuecomment-137784758.

## 

Francis Bond http://www3.ntu.edu.sg/home/fcbond/
Division of Linguistics and Multilingual Studies
Nanyang Technological University

**Comment by stevenbird** [comment]
I see, thanks @fcbond

**Pull request merged**
