### PR TITLE
Hotfix/bugs on wordnet app

### PR DESCRIPTION
**Pull request by StephanHasler**
This pull request resolves two bugs in the wordnet_app (#3002 and #3003).

### CODE REVIEW

**Comment by arademaker** [comment]
I am assuming the use of HTML in the code like https://github.com/nltk/nltk/blob/4616bcdf3b045e4c76b724e210f11fd0b8b9a501/nltk/app/wordnet_app.py#L897 is because NLTK is avoiding have to depend on web frameworks like Flask right?

**Comment by StephanHasler** [comment]
I guess the use of a web framework like Flask could lead to less and simpler code. I would prefer that.
The question is, if it makes sense to port the wordnet_app. It seems no one uses it. The wordnet online search is more informative. I used the wordnet_app only once when the online search was not available.

**Comment by arademaker** [comment]
Hi @StephanHasler, I am curious, what 'wordnet online search' are you using? 

1. The Princeton web interface for PWN 3.1 at https://wordnet.princeton.edu?
2. The http://en-word.net from the Open English WordNet (fork from Princeton WN 3.0/3.1) from @jmccrae ? 
3. The multilingual http://compling.hss.ntu.edu.sg/omw/ from @fcbond ? 
4. The Polish/English wordnets interface at http://plwordnet.pwr.wroc.pl/wordnet/? 

I also have my own web interface for the Portuguese Wordnet and Princeton English Wordnet 3.0 at http://openwordnet-pt.org.

**Comment by StephanHasler** [comment]
I use the princeton Web interface. I was not aware of the others.
I would not have fixed the wordnet_app, if I knew the alternatives, e.g. Open English Wordnet.
Thanks for telling me!

**Comment by purificant** [comment]
LGTM

I was able to reproduce both of https://github.com/nltk/nltk/issues/3002 and https://github.com/nltk/nltk/issues/3003 and the change set in this PR prevents the issues from occurring in my testing.

**Comment by purificant** [comment]
LGTM

I was able to reproduce both of https://github.com/nltk/nltk/issues/3002 and https://github.com/nltk/nltk/issues/3003 and the change set in this PR prevents the issues from occurring in my testing.

**Review by purificant — APPROVED** [review]

**Comment by tomaarsen** [comment]
I trust your judgement on this @purificant. Beyond that, these changes seem sensible when inspected.
I appreciate your work on this @StephanHasler! Especially the latter bug seems nasty to chase down.

**Pull request merged**
