### PR TITLE
Fix find_concordance() returning empty list for left_context

### PR DESCRIPTION
**Pull request by dnc1994**
Patching #2088

### CODE REVIEW

**Comment by alvations** [comment]
[CI: retest]

**Comment by alvations** [comment]
Thanks @dnc1994 for the contribution! LGTM =)

BTW, since `[CI: retest]` hasn't worked on Travis. I've manually created a branch checkout to run the test on https://travis-ci.org/nltk/nltk/builds/429420483

**Review by alvations — APPROVED** [review]
LGTM!

**Comment by stevenbird** [comment]
Thanks @dnc1994

**Pull request merged**
