### PR TITLE
Cleaning up RTE classification code

### PR DESCRIPTION
**Pull request by alvations**
Attending to #1836

- Moved `lemmatize` and `ne` tagging functions to a class function inside the `RTEFeatureExtractor` object

 - Moved the `demo*()` functions to proper unittest in `nltk/test/unit/test_rte_classify.py`.

I'm not sure how `megam` on CI but in the case that the testing fails, we can skip the `megam` and `bfgs` tests.

### CODE REVIEW

**Comment by stevenbird** [comment]
@ewan-klein alerting you to this work on your code in case you can review

**Comment by ewan-klein** [comment]
@alvations @stevenbird Not all of the affected code is mine. But the proposed changes look sensible and I don't foresee any problems with merging them in. I haven't tried to chase down the failing check, but I assume it is innocuous or fixable.

**Comment by alvations** [comment]
@ewan-klein Thanks for looking through the proposed changes! The main purpose was so that the changes made to resolve the LGTM issues (from #1776) can be tracked with proper unittest by moving the demo code there.

The latest commit should resolve the string checking fails on the unittest.

**Comment by stevenbird** [comment]
Thanks @alvations and @ewan-klein

**Pull request merged**
