### PR TITLE
Load PunktParameters from tab files

### PR DESCRIPTION
**Pull request by ekaf**
Tab files are not exposed to the "sleepy" vulnerabilities reported with Python pickles.

This PR adds a loader for the [corresponding data package](https://github.com/nltk/nltk_data/pull/215).

```
from nltk.tokenize.punkt import PunktTokenizer
tokenizer = PunktTokenizer()

text = 'tél. abst. dec. 15'

tokenizer.load_lang('english')
print(tokenizer.tokenize(text))
```
['tél.', 'abst.', 'dec. 15']

Using the new _load_lang_ function, this tokenizer can change language on the fly:

```
tokenizer.load_lang('french')
print(tokenizer.tokenize(text))
```
['tél. abst. dec.', '15']

### CODE REVIEW

**Comment by ekaf** [comment]
More calling functions need editing, so changing to draft.

**Comment by ekaf** [comment]
I think this PR is complete now. However, first merging the [corresponding nltk_data package](https://github.com/nltk/nltk_data/pull/215) would be a prerequisite for testing this PR.

**Comment by ekaf** [comment]
(Edited) After applying _git rebase_, the following problem seems solved.

This seems similar to a CI error seen recently. Here, CI failed already on pre-commit ("reformatted nltk/test/unit/test_disagreement.py"), though this PR does not modify that file:

> 2024-07-26T07:32:44.6552315Z black....................................................................Failed
> 2024-07-26T07:32:44.6553250Z - hook id: black
> 2024-07-26T07:32:44.6553575Z - files were modified by this hook
> 2024-07-26T07:32:44.6553816Z 
> 2024-07-26T07:32:44.6553980Z reformatted nltk/test/unit/test_disagreement.py
> 2024-07-26T07:32:44.6554251Z 
> 2024-07-26T07:32:44.6554436Z All done! ✨ 🍰 ✨
> 2024-07-26T07:32:44.6554745Z 1 file reformatted, 360 files left unchanged.
> 2024-07-26T07:32:44.6555006Z 
> 2024-07-26T07:32:45.6834128Z isort....................................................................Passed
> 2024-07-26T07:32:45.7018446Z ##[error]Process completed with exit code 1.
>

**Comment by ekaf** [comment]
All the doctests in _nltk/tokenize/*py_ succeed. 
In particular, sent_tokenize() does not use pickles anymore.
Users are encouraged to test this PR and report any difference with the previous pickles.

**Comment by ekaf** [comment]
CI now fails with this:
>    Resource punkt_tab not found.
>   Please use the NLTK Downloader to obtain the resource:

@stevenbird, _nltk_data/index.xml_ does not mention the newest data packages, so it could look like the index was not rebuilt after merging the latest  _nltk_data_ PRs.

**Comment by sadra-barikbin** [comment]
@ekaf , just doing `import nltk` raises the error that you mentioned above. `LookupError` `Resource punkt_tab not found.`

**Comment by ekaf** [comment]
Thanks @sadra-barikbin, this is indeed a sad situation: it is not even possible to import nltk. The reason is that the plaintext corpus reader fails to initialize a sent_tokenizer.
 As a consequence, nltk.download (or anything else) won't work, since _nltk_ is not defined.
@stevenbird, this is almost the worst that can happen.

**Comment by ekaf** [comment]
@alvations, @stevenbird, @purificant,   the plain NLTK v. 3.8.1 can confirm that the _nltk_data index_ needs rebuilding:

```
import nltk
print(f"NLTK v. {nltk.__version__}")

```

> NLTK v. 3.8.1


`nltk.download("punkt_tab")
`

> [nltk_data] Error loading punkt_tab: Package 'punkt_tab' not found in
> [nltk_data]     index
>

**Comment by ekaf** [comment]
This nltk_data [PR should fix the index](https://github.com/nltk/nltk_data/pull/220)

**Comment by ekaf** [comment]
After rebuilding the nltk_data index, the "punkt_tab" package can now be downloaded using nltk from the _develop_ branch, but not from the branch associated with this PR. So nltk still cannot start using this PR.

 I guess it is because the _plaintext_ corpora reader (called from _meteor_) now needs to initialize its _sent_tokenizer_ using the "punkt_tab" package. Without that package, nltk fails to start, and hence, it is not able to download the package. 

But once the package is downloaded using the _develop_ branch, it is possible to test this PR.

Maybe it  would be possible to avoid the requirement of loading a _sent_tokenizer_ while starting nltk.

**Comment by ekaf** [comment]
CI succeeds and everything seems ok now.

**Review by JoshuaPeddle — APPROVED** [review]

**Comment by ekaf** [comment]
Fixed a small incompatibility in the new version of ne_chunk(), so that the nltk's whole suite of tokenizer/tagger/chunker runs using the same high-level calls as before dropping the pickles:

```
>>> sent = "Consolidated Gold Fields is a British industrial conglomerate."
from nltk.tokenize import word_tokenize
>>> wsent = word_tokenize(sent)
>>> print(wsent)
```
['Consolidated', 'Gold', 'Fields', 'is', 'a', 'British', 'industrial', 'conglomerate', '.']

```
>>> from nltk.tag import pos_tag
>>> psent = pos_tag(wsent)
>>> print(psent)
```
[('Consolidated', 'NNP'), ('Gold', 'NNP'), ('Fields', 'NNP'), ('is', 'VBZ'), ('a', 'DT'), ('British', 'JJ'), ('industrial', 'JJ'), ('conglomerate', 'NN'), ('.', '.')]

```
>>> from nltk.chunk import ne_chunk
>>> from pprint import pprint
>>> pprint(ne_chunk(psent))
```
Tree('S', [Tree('GSP', [('Consolidated', 'NNP')]), Tree('ORGANIZATION', [('Gold', 'NNP'), ('Fields', 'NNP')]), ('is', 'VBZ'), ('a', 'DT'), Tree('GPE', [('British', 'JJ')]), ('industrial', 'JJ'), ('conglomerate', 'NN'), ('.', '.')])

**Comment by stevenbird** [comment]
Thanks @ekaf and sorry for the delay I'm doing fieldwork with almost zero bandwidth

**Pull request merged**
