### PR TITLE
Make plot methods return Axes objects

### PR DESCRIPTION
**Pull request by nick-ulle**
This pull request addresses issue #2239.

So far I've only modified the code for `FreqDist.plot`. If the maintainers agree with the proposal in #2239, I will also modify the code for `ConditionalFreqDist.plot`.

Feedback is appreciated.

### CODE REVIEW

**Comment by alvations** [comment]
Thanks @nick-ulle for the proposal! The change looks good, please proceed with other plots that you think should use the same `ax.set_title()` idiom.

**Comment by stevenbird** [comment]
Hi @nick-ulle -- please go ahead with more of this, if you can, thanks.

**Comment by alvations** [comment]
There's still a few points where `pylab` is used, it can be improved but this PR looks good to merge since we have cleaned up the `probability.py` and the test passes

----

For reference:

```
$ grep matplotlib nltk/**/*.py
nltk/app/__init__.py:        from matplotlib import pylab
nltk/app/__init__.py:            "nltk.app.wordfreq not loaded " "(requires the matplotlib library)."
nltk/app/wordfreq_app.py:from matplotlib import pylab
nltk/draw/dispersion.py:        from matplotlib import pylab
nltk/draw/dispersion.py:            'The plot function requires matplotlib to be installed.'
nltk/draw/dispersion.py:            'See http://matplotlib.org/'
nltk/parse/dependencygraph.py:        from matplotlib import pylab
nltk/sentiment/util.py:        import matplotlib.pyplot as plt
nltk/sentiment/util.py:            'The plot function requires matplotlib to be installed.'
nltk/sentiment/util.py:            'See http://matplotlib.org/'
nltk/tbl/demo.py:    Note: requires matplotlib
nltk/tbl/demo.py:    import matplotlib.pyplot as plt
nltk/tokenize/texttiling.py:    from matplotlib import pylab
```

**Review by alvations — APPROVED** [review]
LGTM now with the improvements to `nltk.probability`

**Comment by stevenbird** [comment]
Thanks @nick-ulle... more welcome!

**Pull request merged**
