### PR TITLE
installation via puppet

### PR DESCRIPTION
**Pull request by deanmalmgren**
I'm not sure if this is the best place to put this or whether this is even the appropriate forum for it, but I thought that the NLTK user community would like to know about (and contribute to) the [puppet-nltk project](https://github.com/datascopeanalytics/puppet-nltk) that we are working on to make it easy to install nltk on many machines in an automated and reliable way. 

If there is a better place to include this or a better forum for this kind of thing, please let me know and I'm happy to use that alternative channel instead.

### CODE REVIEW

**Comment by kmike** [comment]
Hi @deanmalmgren,

puppet-nltk looks nice! But I'm -1 on adding these instructions to docs - they looks a bit too specific. Most people don't need nltk-puppet, and those who need it may prefer chef or ansible or other orchestration framework. What nltk-puppet solves is definitely not a kind of problem first-time NLTK users solve.

@stevenbird what do you think about creating "related projects" page in Wiki, or just putting a list of related projects to the main wiki page?

**Comment by deanmalmgren** [comment]
Completely understood, @kmike. If you and @stevenbird have any other ideas for places to mention things like this, I'd be happy to include it there.

**Comment by stevenbird** [comment]
Thanks @deanmalmgren; I've added a link to puppet-nltk from the nltk github wiki.

**Comment by deanmalmgren** [comment]
Sounds great, Steven. Thanks!

**Comment by stevenbird** [comment]
Oh, note that the plural of "corpus" is "corpora" (not "corpi" as on your webpage).

**Comment by deanmalmgren** [comment]
haha. just updated now. Thanks for the catch

**Pull request closed without merging**
