### PR TITLE
Don’t import requests during the module import. #1725

### PR DESCRIPTION
**Pull request by dimazest**

### CODE REVIEW

**Comment by pykler** [comment]
Corenlp is still being imported upon `import nltk` this means that even if now import nltk works some of the generic nltk features might still be broken. The right approach "if corenlp" is not part of the required packages, is to not import it at all rather than move the import for the requests library.

**Comment by alvations** [comment]
@pykler is right. If the `corenlp` interface is optional, it shouldn't be expose to the top level imports at https://github.com/nltk/nltk/blob/develop/nltk/parse/__init__.py#L81 , commenting out L81 on the `nltk.parse.__init__.py` is needed. 

@dimazest could you help to check whether commenting out `nltk.parse.__init__.py` causes any test to fail since the namespace use in the unittest or doctest might be different? Thanks in advance!

**Comment by stevenbird** [comment]
Here's an alternative approach, to convert the load-time error to a runtime error. If we did it this way, we avoid the inconvenience of a longer import statement when using corenlp (and needing to remember which modules are included in package imports).

https://github.com/nltk/nltk/blob/develop/nltk/classify/maxent.py#L56

**Comment by dimazest** [comment]
Does it still requires a change?

I would still import corenlp classes in the .parse module, even if requests are not installed. In this way the corenlp classes are not different from others.

I would not silence the import error, because when the corenlp interface is used, but requests are not installed, then seeing an import error is more informative than seeing a name error.

**Comment by pykler** [comment]
Again my comment is, if corenlp is required, then it should not be an
optional dependency. Otherwise everyone who wants to install nltk and have
the default set of use cases installed, would always need to do, `pip
install nltk[corenlp]`. Moreover breaking much already existing code bases
and install_requires. For me, I pinned to 3.2.2 until this is resolved.

Hatem Nassrat

**Comment by dimazest** [comment]
There are two conflicting things. First is to be able to use NLTK without any dependencies installed. For example, someone just extracted nltk distribution and wants to use the minimal functionality.

Second, NLTK has dependencies, and even if setup.py is used, requiring a user to install numpy among other dependencies is too much.

NLTK should be impoetable without dependencies installed (I hope that is fixed, but we should have a test for that, so the situation doesn't repeat).

Now the question is what to do if you want to use a part of NLTK that has a dependency? For example, you've been using the NLTK blue score function, and now got into parsing and want to use corenlp​. You already have NLTK installed, but without the extra. When you use the code that has an uninstalled dependency, you get an import error and know exactly what should be installed (unless you've read the to be written documentation and installed nltk[corenlp]).

Why is it a good idea import everything? I guess when ipython is used, so people could inspect provided classes and always see the same list.

Why do we have extras in setup.py? Because there should be a complete list of dependencies.

-- I'm sorry if it's not clear, typing on the phone is harder than I expected.

**Comment by pykler** [comment]
Sounds good, if thats the design then the exceptions raised should indicate
potentially that sub dependencies are needed. This is more of a feature
request at this point.

Hatem Nassrat

On Fri, May 19, 2017 at 1:00 PM, Dmitrijs Milajevs <notifications@github.com

**Comment by stevenbird** [comment]
@dimazest, I agree. But @pykler said that [Corenlp is still being imported upon import nltk](https://github.com/nltk/nltk/pull/1727#issuecomment-302577992). That would seem to be a showstopper. I haven't been able to replicate this problem. If there is no such problem, then I think we don't need to do anything further, right?

**Comment by dimazest** [comment]
I'll give it a closer look.

**Comment by pykler** [comment]
Corenlp is being imported in the ntlk.parse which is being imported in
nltk.__init__  ... See the stack trace shared on #1725

**Comment by stevenbird** [comment]
I'll package a new release as soon as the CI test has completed.

**Comment by stevenbird** [comment]
I think that @dimazest's solution of embedding the imports is sufficient.

**Pull request merged**
