### PR TITLE
Fixing Jenkins

### PR DESCRIPTION
**Pull request by alvations**

### CODE REVIEW

**Comment by alvations** [comment]
[CI: retest]

**Comment by fievelk** [comment]
Hi @alvations. Could you please explain the rationale behind these changes, so that it's easier to review them?

**Comment by alvations** [comment]
I think cloudbees is having some issues with the fedora17 and fedora25 build and I'm just testing which configuration with which jenkins works. And it's causing the failed builds. I.e.
 - https://nltk.ci.cloudbees.com/job/nltk-cloudbees-fc25/PYV=3.5.4,jdk=jdk8latestOnlineInstall/lastBuild/console shows fedora17
 - https://nltk.ci.cloudbees.com/job/nltk-cloudbees-fc25/PYV=2.7.14,jdk=jdk8latestOnlineInstall/lastBuild/console shows fedora25 

but they should all be fedora25 from the global slave configurations and the build configurations. 

----

Apparently all the corenlp tests didn't kick in since last dec because they changed from http -> https and now all the unstable builds on CI was caused by corenlp.

https://nltk.ci.cloudbees.com/job/nltk-cloudbees-fc25/PYV=2.7.14,jdk=jdk8latestOnlineInstall/lastBuild/console

----

And the pylint has some bugs left unpatched in their master branch and it's causing the error at the end too. 

https://nltk.ci.cloudbees.com/job/nltk-cloudbees-fc25/PYV=2.7.14,jdk=jdk8latestOnlineInstall/lastBuild/console

----

Please don't merge this first. I'll clean up the edits we made sure:

 - cloudbees makes fedora25 stable and fedora17 stable
 - skipped all corenlp tests since we're dropping official support after stanford release their official python wrapper
 - [DONE]: made sure that pylint patch is pip-able.

**Comment by alvations** [comment]
[CI: retest]

**Comment by alvations** [comment]
[CI: retest]

**Comment by alvations** [comment]
[CI: retest]

Success at last! https://nltk.ci.cloudbees.com/job/nltk-cloudbees-fc25/ 

----

To summarize the port to support Python3.6 on the CI server:

 - [FIXED] Fedora needed to be upgraded from 17 -> 25 with Python3.5 binaries support from Cloudbees
 - [FIXED] The path names becomes really long on Cloudbees when we put in complicated configuration and test matrix, we cannot exceed the 127 shell line restriction https://github.com/tox-dev/tox/issues/477#issuecomment-359015276

 - [FIXED] We need to update the Stanford dependencies links from http -> https.
 - [FIXED] CoreNLP doctests are failing, so temporary I've disabled and skipped them, we need to raise an issue to track this. And ultimately deprecate it and point people to their official Python API. 

- [FIXED] Symbolic links are always stale in new test builds because they are not overwritten. Since we're updating the binaries, the symbolic links should be forced to renew, thus the `ln -sf ...`

 - [FIXED] The empty nosetest output xml file was because PyLint is still giving errors on https://github.com/PyCQA/pylint/issues/1774 so we will just pip install from their master branch

**Comment by alvations** [comment]
[CI: retest]

**Comment by alvations** [comment]
[CI: retest]

**Comment by alvations** [comment]
@fievelk given your experience with the CI setup and tests, could you help to review and see whether the changes are okay?  Thank you in advance!

At last, the tests checks out on the CI.

**Comment by iliakur** [comment]
Which version of tox are you using?
I'm guessing while you're digging around in that part of the code, you might be interested in simplifying the `tox.ini` file using factor-conditional settings:
https://tox.readthedocs.io/en/latest/config.html#factors-and-factor-conditional-settings

**Comment by alvations** [comment]
@Copper-Head Nice suggestion, I didn't know about that feature! 

Seems like the CI using `tox-2.9.1` https://nltk.ci.cloudbees.com/job/nltk-cloudbees-fc25/PYV=2.7.14,jdk=jdk8latestOnlineInstall/lastBuild/console

I think the harder part is figuring out CI server configuration that suits this tox feature.
I'll skip that for now but a good feature improvements for the future ;P

**Comment by iliakur** [comment]
Do you think this would be easier to configure with TravisCI instead of cloudbees?

**Comment by stevenbird** [comment]
@Copper-Head: I think that's a good future option if we have further problems with cloudbees.

**Comment by alvations** [comment]
@Copper-Head @stevenbird 

Having the flexibility of configuring the matrix within the `.travis.yml` file and making the test specific to `python` with `tox` in Travis makes it easier to maintain. 

Currently, cloudbees configuration is not transparent to users without the access, having the configurations all in the `.travis.yml` file  would be more transparent.

**Comment by stevenbird** [comment]
Merging. We'd still appreciate feedback from @fievelk

**Pull request merged**
