### PR TITLE
Fix for https://github.com/nltk/nltk/issues/3294

### PR DESCRIPTION
**Pull request by soras**

### CODE REVIEW

**Review by ekaf — APPROVED** [review]
Thanks @soras, this should indeed solve #3294.

**Comment by ekaf** [comment]
@soras, please note that CI fails. The reason is that pyupgrade modifies your file: it removes the "r" parameter of _open_ (I don't know why it likes it better that way). After this change you need to call "git add" and "git commit" again.

**Comment by soras** [comment]
> @soras, please note that CI fails. The reason is that pyupgrade modifies your file: it removes the "r" parameter of _open_ (I don't know why it likes it better that way). After this change you need to call "git add" and "git commit" again.

Thanks for the notice. I don't have experience with your workflow. I see CI failing, but I don't see how pyupgrade is rewriting the file. Is this information available only for maintainers? 

Anyway, I'll follow your guide and see if I can improve the code.

**Comment by ekaf** [comment]
> I don't see how pyupgrade is rewriting the file. Is this information available only for maintainers?

@soras, pyupgrade rewrites the file on your local machine, the first time you try to commit it, so you should be able to see the change locally. I am not aware of any information that would be available only to maintainers: as far as I know, everything is open.

**Review by ekaf — APPROVED** [review]

**Pull request merged**
