### PR TITLE
Fix Issue #1946 by correcting typo from presnet to present

### PR DESCRIPTION
**Pull request by somnathrakshit**
Changed `__conjugation_suffix_verb_presnet` to `__conjugation_suffix_verb_present`  in nltk/stem/snowball.py

### CODE REVIEW

**Comment by somnathrakshit** [comment]
Any suggestions as to why the build might have failed?

**Comment by alvations** [comment]
@somnathrakshit the build is failing because we've reconfigured the CI server.

We need to wait for https://github.com/nltk/nltk/pull/1942 to be merged before new PR can pass the build. Sorry about that.

**Comment by somnathrakshit** [comment]
Sure. So, should I start a new PR after #1942 is merged or will this one do?

**Comment by alvations** [comment]
Now worries. Leave this PR open while we wait. We can do a retest after #1942 is merged.

**Comment by somnathrakshit** [comment]
@alvations Now that #1942 is merged, can you please do a retest on this one?

**Comment by alvations** [comment]
[CI: retest]

----

@somnathrakshit Sure =)

**Comment by somnathrakshit** [comment]
thanks :)

**Comment by somnathrakshit** [comment]
@alvations Is this good enough for merge?

**Comment by stevenbird** [comment]
Thanks @somnathrakshit

**Comment by somnathrakshit** [comment]
Thanks for the merge. :smile:

**Pull request merged**
