### PR TITLE
Drop support for Python 3.6, support Python 3.10

### LINKED ISSUE #2912: Consider deprecating Python 3.6
Hello!

Python 3.6 is approaching its End Of Life on December 23rd, and we should consider dropping support for Python 3.6 accordingly. In particular, this involves modifying:
* CI tests
* `python_requires` in `setup.py`.
* Lots of documentation throughout the project.

Among other places, I'm sure.

- Tom Aarsen

### LINKED ISSUE #2913: Add CI tests for Python 3.10
Hello!

Python 3.10 is no longer a glimmer far into the future, and we should start supporting it. The first step in doing so is adding 3.10 to the CI tests, and mentioning that NLTK works for Python 3.10 in our documentation throughout the project.

- Tom Aarsen

### PR DESCRIPTION
**Pull request by tomaarsen**
Closes #2912, closes #2913

Hello!

### Pull request overview
* Set `python_requires` in `setup.py` to `>=3.7` instead of `>=3.6`.
* Removed mention of supporting Python 3.6 in documentation.
* Mention support for Python 3.10 in documentation.
* Removed py36 tests in tox, and add py310 tests.

---

### Note
I left mentions of Python 3.6 in the tools folder, e.g. in `run_doctests.py`:
https://github.com/nltk/nltk/blob/6411fabf05a75e2beb82b29fed614dbd12688f7f/tools/run_doctests.py#L10-L16

This folder seems mostly outdated and unused, also containing references back to jenkins and travis. One of the files, `run_doctests.py`, is not the proper way that doctests should be ran regardless. I didn't worry about these cases too much.

Thanks to @purificant for the commit of his I borrowed from his Python 3.10 branch :)

We should prepare a release soon.

- Tom Aarsen

### CODE REVIEW

**Review by purificant — APPROVED** [review]

**Comment by tomaarsen** [comment]
This PR is now planned to be merged *after* the upcoming NLTK release (3.6.6), allowing existing Python 3.6 users to benefit from our changes over the past months.

**Comment by stevenbird** [comment]
Merged, now that [3.6.6](https://pypi.org/project/nltk/3.6.6/) is released.

**Comment by stevenbird** [comment]
Thanks @tomaarsen, @purificant

**Comment by tomaarsen** [comment]
Weirdly enough - these tests passed, but every single CI run after this PR fails to build scikit-learn on Windows. I've removed CI tests for Windows 10 for now, until scikit-learn 1.0.2 releases (planned in middle December 2021), which supposedly adds support for Python 3.10 in Windows.

**Pull request merged**
