### PR TITLE
Support Open English Wordnet 2022

### LINKED ISSUE #3059: Which Open English Wordnet version is useful?
Unlike the original Princeton WordNet, which has at least two widely used versions (3.0 and 3.1), it may not be relevant for NLTK to support all versions of the OEWN project, because these are not so widely used, and the most recent version tends to supersede all the preceding ones.
NLTK currently supports the 2021 edition of OEWN through the
_nltk_data/corpora/wordnet2021.zip_ package. An official 2022 edition is underway, but its data format has shifted to YAML, and it is not clear whether the OEWN project will also produce a data package in the original data format compatible with NLTK.
Meanwhile, the _wndb_ project by @1313ou at https://github.com/x-englishwordnet/wndb already supplies suitable packages for OEWN 2022, that work well with NLTK.

This raises a few questions:
1. Should the next OEWN package replace the preceding one?
2. Should NLTK prefer the official or an alternative package source for OEWN data?
3. Should _wordnet.py_ aim at supporting YAML?

### PR DESCRIPTION
**Pull request by ekaf**
Fix #3059: add support for the latest OEWN release.

For ex., pretty print a list of synsets which have been split between WordNet 3.0 and OEWN 2022. This info is stored in the 'splits' dictionary, with counts of how many senses are carried over into each part of the split.

```
from nltk.corpus import wordnet2022 as wn

print(f"{len(wn.splits)} synsets were split between Wordnet 3.0 and {wn.get_version()}:\n")

for ss in sorted(list(wn.splits.keys())):
    print(f"{ss} -> {' + '.join([b + ' (' + str(a) + ' sensekey/s)' for a,b in wn.splits[ss]])}")
```

```
48 synsets were split between Wordnet 3.0 and 2022:

00040058-s -> 00040230-s (1 sensekey/s) + 00040078-s (2 sensekey/s)
00046299-r -> 00473995-r (1 sensekey/s) + 00046404-r (3 sensekey/s)
00202934-v -> 00296457-v (1 sensekey/s) + 00203725-v (2 sensekey/s)
00371163-s -> 03166825-s (1 sensekey/s) + 00372435-s (3 sensekey/s)
00522349-s -> 00524222-s (1 sensekey/s) + 00524591-s (1 sensekey/s)
00688377-v -> 00691232-v (1 sensekey/s) + 00715545-v (3 sensekey/s)
00766234-n -> 00770522-n (2 sensekey/s) + 00770714-n (4 sensekey/s)
00779248-n -> 00783716-n (11 sensekey/s) + 00784043-n (1 sensekey/s)
00824767-v -> 00826835-v (1 sensekey/s) + 00827564-v (20 sensekey/s)
00845523-n -> 01242621-n (1 sensekey/s) + 00854605-n (10 sensekey/s)
00949619-n -> 00959774-n (1 sensekey/s) + 00960217-n (1 sensekey/s)
00988988-s -> 00993654-s (1 sensekey/s) + 00992517-s (7 sensekey/s)
01068306-s -> 01072418-s (3 sensekey/s) + 01072535-s (1 sensekey/s)
01301051-v -> 01306626-v (1 sensekey/s) + 01306219-v (3 sensekey/s)
01878870-s -> 01885678-s (1 sensekey/s) + 01884927-s (5 sensekey/s)
01896031-n -> 01919623-n (2 sensekey/s) + 15493564-n (1 sensekey/s)
01934026-s -> 01940337-s (1 sensekey/s) + 01940546-s (1 sensekey/s)
01965512-s -> 01972504-s (1 sensekey/s) + 01972346-s (1 sensekey/s)
02025274-s -> 02032791-s (4 sensekey/s) + 02032319-s (1 sensekey/s)
02436025-s -> 02444882-s (1 sensekey/s) + 02444687-s (2 sensekey/s)
02572119-v -> 02587275-v (13 sensekey/s) + 02587734-v (2 sensekey/s)
02672831-n -> 02707303-n (2 sensekey/s) + 02707568-n (1 sensekey/s)
02713992-n -> 02749134-n (1 sensekey/s) + 02748990-n (1 sensekey/s)
02795978-n -> 02831901-n (2 sensekey/s) + 02831715-n (3 sensekey/s)
03794136-n -> 03839810-n (2 sensekey/s) + 04498159-n (1 sensekey/s)
04347754-n -> 04397290-n (3 sensekey/s) + 15489595-n (1 sensekey/s)
04722910-n -> 15481687-n (1 sensekey/s) + 04775404-n (1 sensekey/s)
04876561-n -> 04930628-n (2 sensekey/s) + 15487181-n (1 sensekey/s)
05257737-n -> 15492611-n (3 sensekey/s) + 05316440-n (1 sensekey/s)
05820462-n -> 05881630-n (2 sensekey/s) + 05881755-n (1 sensekey/s)
06206210-n -> 06271738-n (1 sensekey/s) + 15486704-n (1 sensekey/s)
06823760-n -> 06908760-n (1 sensekey/s) + 06908910-n (2 sensekey/s)
07035153-n -> 07141653-n (1 sensekey/s) + 07141454-n (2 sensekey/s)
08949093-n -> 09071981-n (4 sensekey/s) + 15493161-n (1 sensekey/s)
08963369-n -> 09086346-n (1 sensekey/s) + 09087281-n (1 sensekey/s)
09570298-n -> 09701985-n (1 sensekey/s) + 09701769-n (3 sensekey/s)
09636339-n -> 09768800-n (3 sensekey/s) + 15488205-n (2 sensekey/s)
09637013-n -> 09768800-n (1 sensekey/s) + 15484808-n (3 sensekey/s)
09638245-n -> 15477219-n (1 sensekey/s) + 15481078-n (1 sensekey/s)
09676490-n -> 09806046-n (3 sensekey/s) + 15488853-n (1 sensekey/s)
10000459-n -> 10133212-n (1 sensekey/s) + 10133069-n (1 sensekey/s)
10002031-n -> 10134719-n (1 sensekey/s) + 10134810-n (1 sensekey/s)
10012484-n -> 10145398-n (1 sensekey/s) + 10145549-n (2 sensekey/s)
10210648-n -> 10345541-n (2 sensekey/s) + 10345714-n (4 sensekey/s)
10557854-n -> 10386944-n (1 sensekey/s) + 10695603-n (3 sensekey/s)
11642430-n -> 15485356-n (1 sensekey/s) + 15487307-n (2 sensekey/s)
12578255-n -> 12733986-n (2 sensekey/s) + 12733586-n (4 sensekey/s)
13316722-n -> 13477672-n (1 sensekey/s) + 15493399-n (2 sensekey/s)

```

### CODE REVIEW

**Comment by ekaf** [comment]
NB: this PR needs access to the _wordnet2022.zip_ data package. Otherwise the tests fail:

```
 nltk/data.py:583: in find
    raise LookupError(resource_not_found)
E   LookupError: 
E   **********************************************************************
E     Resource wordnet2022 not found.
E     Please use the NLTK Downloader to obtain the resource:
E   
E     >>> import nltk
E     >>> nltk.download('wordnet2022')
```

**Comment by stevenbird** [comment]
[CI: retest]

**Comment by stevenbird** [comment]
I've merged the PR that added wordnet2022

**Comment by tomaarsen** [comment]
Hello!

Thanks for this @ekaf. I've deleted the cached NLTK data for this PR and I'll re-run the test suite.

**Comment by ekaf** [comment]
Thanks @tomaarsen, now there's only a small problem left with python-3.11 on macos-latest, that seems not to have access to _pytest_:

```
Run pytest --numprocesses auto -rsx --doctest-modules nltk
/Users/runner/work/_temp/154f4771-6afc-4f54-bf01-12821ffc6e74.sh: line 1: pytest: command not found
Error: Process completed with exit code 127.
```

**Comment by tomaarsen** [comment]
This is caused by an issue with GitHub Actions caching on Mac with Python 3.11. I've encountered this problem in one of my other repositories too. I've removed the broken cache and restarted the failed job. Thanks for the heads up @ekaf.

**Review by tomaarsen — APPROVED** [review]
LGTM.

**Comment by stevenbird** [comment]
Great to have this @ekaf !

**Pull request merged**
