### PR TITLE
Fixing `__cmp__` for 2and3

### PR DESCRIPTION
**Pull request by heatherleaf**
Here's a load of changes to the 2and3 branch. 

I've changed all `__cmp__` to `__eq__` and `__lt__` together with a `@total_ordering`. 

I have also made som changes to string handling, which might interfere with kmike's current work. Please look through them!

I've added a "text" format to `nltk.data.load` and added an optional `encoding` argument to several file reading and string parsing functions.

The following doctests now pass for py26, py27 and py32 (I don't have py33 so I can't test that):
- align ccg chat80 chunk collocations corpus data dependency drt featgram featstruct grammar grammartestsuites internals japanese logic metrics parse probability relextract resolution segmentation semantics simple stem tag tokenize tree treetransforms util wordnet

I can't test the following doctests, since I don't have the necessary dependencies:
- childes classify discourse gluesemantics inference nonmonotonic
  - (but all gluesemantics tests pass until it tries to use the MaltParser)

The following four tests fail:
- misc portugese_en sourcedstring toolbox

### CODE REVIEW

**Comment by heatherleaf** [comment]
Oh, it fixes issue #324

**Comment by kmike** [comment]
Wow, that's awesome!

**Comment by stevenbird** [comment]
Thanks Peter! Mikhail: I'll leave you to merge this into 2and3 when you're ready.

**Comment by heatherleaf** [comment]
Some more information:

There's an API change in `sem.glue.GlueDict`, so that `GlueDict('glue.semtype')` now must be written like this:
- `GlueDict('nltk:grammars/sample_grammars/glue.semtype')`

`nltk.data.load` has a new format for text:
- a new argument `encoding` for specifying the unicode encoding -- it works for all non-binary formats (i.e., all except pickle, yaml and raw)
- if `encoding` is not specified, `load` first tries with UTF-8, and if that fails it falls back to Latin-1
- this means that `load` reads a unicode file for all non-binary formats
- "text" format returns a unicode string, "raw" format returns a byte string

**Pull request merged**
