### PR TITLE
Test improvements

### PR DESCRIPTION
**Pull request by kmike**
In order to run tests across multiple python interpreters it is very convenient to use the http://tox.testrun.org/ tool. I've added a tox config and a TESTING.rst file with the draft info about how to run tests.

Some doctests are also fixed (there are still a lot of them failing though).

### CODE REVIEW

**Comment by kmike** [comment]
just discovered a better way to fix the doctests, please delay merging

**Comment by stevenbird** [comment]
OK.  Thanks for the tox config.  Please note that some doctests are user documentation and not really regression tests, and will eventually need to live in a docstring.

> > > chunkscore.recall()
> > > 0.33333333333333331

In the docstring we permit ellipses, and can write the above result instead as 0.33333...

However, its a higher priority to get all our tests working where they are, so using float_equals() is fine.

**Comment by kmike** [comment]
Yeah, but this may be 0.49999999999 vs 0.5 where ellipses won't help

**Comment by stevenbird** [comment]
Ready to merge?

NB I intend to tweak docstring imports of the form "from nltk.x.y import z" -> "from nltk.x import z" wherever possible.  In general, x/**init**.py explicitly imports all names from x/y.py that are to be made "public".

**Comment by kmike** [comment]
Yes, I think this is ready and can be merged. There are still a lot of tests failing but the number is reduced for a good amount.

The missing numpy causes 8 test failures but it is not available for pypy (that's why python 2.7 has 13 failed doctests and pypy has 21). We can either live with this or somehow tweak the tox.ini.

**Pull request merged**
