### PR TITLE
Fixing Kneser-Ney LM Implementation

### PR DESCRIPTION
**Pull request by manujosephv**
@iliakur 

The most commonly stated example to get the intuition of Kneser Ney is below:

There is a sentence - "I can't see without my reading _" - and we need to complete this sentence. But the rule is that you are only allowed to look at the last word, just like a language model. Intuitively, the guess would be "glasses". But what about "Francisco"? If you just look at the pure unigram frequencies, Francisco has a higher probability than glasses.

Suppose, we do not have the bigram "reading glasses" in our corpus. So under Absolute Discounting, we will be using the unigram probabilities of the word "glasses" and "Francisco" to estimate the next word and because of the higher frequency of "Francisco" it is more likely to be picked as the word than "glasses".

This is the problem Kneser-Ney tries to tackle. Eventhough "Francisco" is more common, it always follows "San". So, can we use this idea when we are backing-off to a lower order probability. This idea is formalized as Continuation Probability - how likely is a word to appear as a novel continuation?

image

image

#### References

- [Mini Example](http://idiom.ucsd.edu/~rlevy/lign256/winter2008/kneser_ney_mini_example.pdf)
- [PPT](http://www.cs.virginia.edu/~kc2wc/teaching/NLP16/slides/04-LMeval.pdf)
- [Dan Jurafsky](https://www.youtube.com/watch?v=ody1ysUTD7o)
- [Simple calculation-Medium](https://medium.com/@dennyc/a-simple-numerical-example-for-kneser-ney-smoothing-nlp-4600addf38b8)
- [Another doc](https://www.cl.uni-heidelberg.de/courses/ss15/smt/scribe6.pdf)
- [Original Paper](https://www-i6.informatik.rwth-aachen.de/publications/download/951/Kneser-ICASSP-1995.pdf)

### CODE REVIEW

**Comment by stevenbird** [comment]
[CI: retest]

**Comment by stevenbird** [comment]
[CI: retest]

**Comment by stevenbird** [comment]
[CI: retest]

**Comment by stevenbird** [comment]
[CI: retest]

**Comment by stevenbird** [comment]
@manujosephv sorry for the delay... we had issues with our CI testing, and have only just now got it running properly.

**Comment by stevenbird** [comment]
@iliakur would you be able to review this PR please?

**Comment by iliakur** [comment]
My turn to aplogize, I've been really overwhelmed recently. I've blocked the first weekend of May for dealing with everything NLTK-related, so @manujosephv feel free to open up **all the MRs**, and we'll try to come up with a coherent way to merge them together :)

**Comment by iliakur** [comment]
I've skimmed the changes and the math and it seems right. I will double-check the math again tomorrow with a fresh head.
I'm being careful because this is an overhaul of the Kneser-Ney algorithm. @stevenbird how do we best communicate that to the users? Note that the interface is not changing, only the scores.

**Comment by manujosephv** [comment]
closing because #2709 supersedes this

**Comment by stevenbird** [comment]
> I've skimmed the changes and the math and it seems right. I will double-check the math again tomorrow with a fresh head.
> I'm being careful because this is an overhaul of the Kneser-Ney algorithm. @stevenbird how do we best communicate that to the users? Note that the interface is not changing, only the scores.

@iliakur the only place to do this is in the release notes (and I'll take care of that)

**Pull request closed without merging**
