### PR TITLE
MALT, gluesemantics and dependency graph integration.

### PR DESCRIPTION
**Pull request by dimazest**
Parse is already a list of parses, there is no need to return a list of them.

### CODE REVIEW

**Comment by stevenbird** [comment]
@heatherleaf, @dhgarrette: I just want to check with you that there's no reason for this method to return a list of lists, thanks.

**Comment by heatherleaf** [comment]
I think the fix is ok. But note that `ParserI.parse()` returns an iterator, not a list. Probably better anyway, but any documentation stating that `Glue.dep_parse()` returns a list should be updated.

Also, this might break code that uses `dep_parse`

**Comment by dimazest** [comment]
Without this patch `gluesemantics_malt.doctest` is broken:

```
[dimazest@mac nltk]$ ../../bin/fowler.corpora-test nltk/parse/ nltk/test/  --doctest-modules --doctest-glob '*.doctest' -k gluesemantics_malt.doctest
================================== test session starts ===================================
platform darwin -- Python 3.4.3 -- py-1.4.26 -- pytest-2.6.4
plugins: bdd, cov, xdist
collected 166 items

nltk/test/gluesemantics_malt.doctest F

======================================== FAILURES ========================================
_____________________ [doctest] nltk/test/gluesemantics_malt.doctest _____________________
022     ...      ('^(every)$', 'univ_quant'),
023     ...      ('^(girl|dog)$', 'NN')
024     ... ])
025     >>> depparser = MaltParser(tagger=tagger)
026
027 --------------------
028 Automated Derivation
029 --------------------
030     >>> glue = Glue(depparser=depparser)
031     >>> readings = glue.parse_to_meaning('every girl chases a dog'.split())
UNEXPECTED EXCEPTION: AttributeError("'list_iterator' object has no attribute 'nodes'",)
Traceback (most recent call last):

  File "/Users/dimazest/miniconda3/lib/python3.4/doctest.py", line 1318, in __run
    compileflags, 1), test.globs)

  File "<doctest gluesemantics_malt.doctest[6]>", line 1, in <module>

  File "/Users/dimazest/Documents/qmul/tools/src/nltk/nltk/sem/glue.py", line 457, in parse_to_meaning
    for agenda in self.parse_to_compiled(sentence):


  File "/Users/dimazest/Documents/qmul/tools/src/nltk/nltk/sem/glue.py", line 539, in parse_to_compiled
    gfls = [self.depgraph_to_glue(dg) for dg in self.dep_parse(sentence)]

  File "/Users/dimazest/Documents/qmul/tools/src/nltk/nltk/sem/glue.py", line 539, in <listcomp>
    gfls = [self.depgraph_to_glue(dg) for dg in self.dep_parse(sentence)]

  File "/Users/dimazest/Documents/qmul/tools/src/nltk/nltk/sem/glue.py", line 552, in depgraph_to_glue
    return self.get_glue_dict().to_glueformula_list(depgraph)

  File "/Users/dimazest/Documents/qmul/tools/src/nltk/nltk/sem/glue.py", line 233, in to_glueformula_list
    top = depgraph.nodes[0]

AttributeError: 'list_iterator' object has no attribute 'nodes'

/Users/dimazest/Documents/qmul/tools/src/nltk/nltk/test/gluesemantics_malt.doctest:31: UnexpectedException
================= 165 tests deselected by '-kgluesemantics_malt.doctest' =================
======================== 1 failed, 165 deselected in 2.46 seconds ========================
```

**Comment by dimazest** [comment]
I've been sloppy with using list, any iterable (an iterator or a list) should be fine here.

**Comment by stevenbird** [comment]
Thanks @heatherleaf, I'll update the documentation (which currently doesn't exist).
Thanks for the fix @dimazest.

**Comment by stevenbird** [comment]
So, `Glue.dep_parse` calls `MaltParser.parse` which resolves to `ParserI.parse` which calls `MaltParser.parse_sents` which returns `iter(DependencyGraph)`.

`ParserI.parse` just gets the next `DependencyGraph` and this gets passed all the way back out. I.e.  `Glue.dep_parse` returns a `DependencyGraph` (not an iterator). I'll update the documentation accordingly.

**Pull request merged**
