### PR TITLE
Remove unused variables from classify/maxent.py

### PR DESCRIPTION
**Pull request by pratapvardhan**

### CODE REVIEW

**Comment by pratapvardhan** [comment]
I do see unused imports in 

```
../app/wordnet_app.py
../ccg/chart.py
../chunk/util.py
../corpus/europarl_raw.py
```

Quite many in `import os/re/sys` unused in `../corpus/reader/*`

these are safe to cleaned up I suppose? I've started to get around the codebase lately. I thought, I'll start off with
1. Cleaning the files
2. Adding testcases, then move to
3. Adding new features.

**Comment by alvations** [comment]
@pratapvardhan it is advisable to run [autopep8](https://github.com/hhatto/autopep8) before changing the code formats. And for dead code [vulture](https://pypi.python.org/pypi/vulture) Also, different parts of NLTK is written by different people so please do note the styles.

If you're looking to fix PEP8 E712. Also, if you're going to PEP8-ize the NLTK codebase, please do mind @raymondh [`Beyond PEP8`](https://www.youtube.com/watch?v=wf-BqAjZb8M)

Also, these:

``` shell
$ grep -rn "== True:"
tokenize/punkt.py:1503:            if is_sent_starter == True:
corpus/reader/childes.py:340:                    if relation == True:
sentiment/sentiment_analyzer.py:49:        if labeled == True:
sentiment/sentiment_analyzer.py:196:        if accuracy == True:
sentiment/sentiment_analyzer.py:210:            if precision == True:
sentiment/sentiment_analyzer.py:214:            if recall == True:
sentiment/sentiment_analyzer.py:218:            if f_measure == True:
sentiment/sentiment_analyzer.py:224:        if verbose == True:
sentiment/util.py:291:        if remove_duplicates == True:
sentiment/util.py:300:                if skip_retweets == True:
sentiment/util.py:304:                if skip_tongue_tweets == True:
sentiment/util.py:308:                if skip_ambiguous_tweets == True:
sentiment/util.py:314:                if strip_off_emoticons == True:
sentiment/util.py:317:                if remove_duplicates == True:
sentiment/util.py:355:            if skip_header == True:
sentiment/util.py:373:            if skip_header == True:
sentiment/util.py:574:    if save_analyzer == True:
sentiment/util.py:644:    if plot == True:
classify/util.py:256:            if is_male == True:
treetransforms.py:198:                if expandUnary == True:
treeprettyprinter.py:325:        if abbreviate == True:
```

and these:

``` shell
$ grep -rn "== False:"
tag/tnt.py:146:        if self._unk is not None and self._T == False:
sem/evaluate.py:547:                if value == False:
tokenize/punkt.py:1526:            if is_sent_starter == False:
twitter/twitterclient.py:230:                if self.handler.do_continue() == False:
twitter/twitterclient.py:266:                if self.handler.do_continue() == False:
twitter/twitterclient.py:512:        if self.repeat == False:
sentiment/sentiment_analyzer.py:52:        elif labeled == False:
stem/lancaster.py:261:                if rule_was_applied == False:
```

**Comment by pratapvardhan** [comment]
@alvations -- Agreed. I've previously messed up once with autopep8 on NLTK (ignoring styles). So, I was a bit catious on auto-pep8-ing.

I've seen that brillant talk :-) E712 fix was more of a personal style.

Thanks for the comments.

**Comment by alvations** [comment]
@pratapvardhan I would use autopep8 and vulture to detect where to cleanup and then manually clean it up. Just my preference when cleaning up code, I think it would be more coherent to go through and clean up most catch-able / grep-able parts of the codebase than to do individual PRs

**Comment by pratapvardhan** [comment]
@alvations -- vulture seems interesting. Yea, I've been using grep to catch unused imports.

**Comment by pratapvardhan** [comment]
Sorry but I'm a bit unsure here. Should I close this PR or send patches with above pointed issues?

**Comment by alvations** [comment]
I would either
- undo the `== True` -> `is True` patch from `util.py` and leave that for another PR. Then the removal of stale code in the `maxent.py` looks good to merge or
- go ahead and be consistent and change all `== True` -> `is True` in the codebase and then ask for another round of code review.

**Comment by pratapvardhan** [comment]
That makes sense. I've undone the == True -> is True patch from util.py. I'll take this case separately. 

This is good to go. Thanks @alvations

**Comment by alvations** [comment]
@pratapvardhan Sorry for the wait. Thanks for cleaning out the unused variable!

**Pull request merged**
