### PR TITLE
test json2csv adding info for debugging

### PR DESCRIPTION
**Pull request by lrnzcig**
For debugging problems in #1010

### CODE REVIEW

**Comment by lrnzcig** [comment]
If the problem is related to order, already solved in commit 577ceb9

**Comment by ewan-klein** [comment]
@lrnzcig: I'm still getting this:

```
........Error while comparing files. First difference at line below.
=> Output file line: b'#tomorrowspaperstoday #bbcpapers http://t.co/ts9ZnULDwr\xe2\x80\x9d",21910500,suttonnick\r\n'
=> Refer. file line: b'\n'
F..
======================================================================
FAIL: test_tweet_usermention (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ewan/git/nltk/nltk/test/unit/test_json2csv_corpus.py", line 105, in test_tweet_usermention
    'tweets.20150430-223406.usermention.csv.ref'), 'Error in csv file'
AssertionError: Error in csv file

----------------------------------------------------------------------
Ran 11 tests in 0.237s

FAILED (failures=1)
Process terminated with an exit code of 1
```

Is there a spurious blank line in the reference file?

**Comment by lrnzcig** [comment]
@ewan-klein I've been looking at the ref file and it looks ok.

The only particular thing about this area of the file is that this is a tweet with carriage returns in the text of the tweet. Looking at the binary content of the file, the EOL of the files is `'\r\n'` but the EOL of the text of the tweet is `'\n'`. I don't know exactly what platform you are using, but I've been browsing and python3.4 does have by default support for "universal newlines". Besides, this same tweet with the same text is present in some other reference files. So I don't really have an good explanation for the problem.

What OS are you using? Could you send me the file you generate, so that I take a look to the binary content and try to figure out what's the difference? (Although I see the problem seems to happen when reading the reference file).

Thanks.

**Comment by lrnzcig** [comment]
Sorry @ewan-klein forge my last comment. I did not realize I can reproduce the problem in python3. Let me debug it and do yet another pull request.

**Pull request merged**
