### PR TITLE
synset_from_sense_key: searching for sense key in index.sense

### PR DESCRIPTION
**Pull request by jayralencar**
I found a little mistake on the method ```synset_from_sense_key```:

On searching for the sense key ```bank%1:06:00::```, for example, it returns the synset ```Synset('bank.n.10')``` (offset: 00169305)  instead of ```Synset('bank.n.10')``` (offset: 02787772), which is the correct. See index.sense excerpt:

...
banjul%1:15:00:: 08946042 1 0
bank%1:04:00:: 00169305 10 0
**bank%1:06:00:: 02787772 9 0**
bank%1:06:01:: 04139859 8 0
bank%1:14:00:: 08420278 2 20
...

To fix it I used the same logic of the method ```lemma_from_key```, using ```_binary_search_file```.

### CODE REVIEW

**Comment by stevenbird** [comment]
Thanks @jayralencar. I'm having a hard time reviewing this PR given the incidental formatting changes.

**Comment by ekaf** [comment]
The synset_from_sense_key() function was fixed in PR #2621, so it now returns the correct synset.

**Comment by stevenbird** [comment]
Resolved in #2621

**Comment by stevenbird** [comment]
Thanks @jayralencar, @ekaf

**Pull request closed without merging**
