### PR TITLE
Improve spanish stemmer

### PR DESCRIPTION
**Pull request by Madrigal**
This is a refactor of things that smell bad on the spanish stemmer. No functionality was affected.

I verified that it doesn't break anything with the test files in https://github.com/snowballstem/snowball-data/tree/master/spanish. It would be a good idea to add those to the unit tests for spanish stemmer, but I didn't found any reference on how the nltk project handles this kind of testing. If you guide me through it I'll be happy to help.

### CODE REVIEW

**Comment by stevenbird** [comment]
Thanks @Madrigal.

**Comment by stevenbird** [comment]
You would be welcome to add tests to the module docstring (those that are useful to a user), or put them in `nltk/test/stem.doctest` (this is more for regression testing, not user documentation).

**Comment by Madrigal** [comment]
I was thinking more on something like adding it to `nltk/test/unit/test_stem.py`

However, I don't see any kind of exhaustive testing there. [Snowball data](https://github.com/snowballstem/snowball-data) contains the reference test cases for all implementation of snowball stemmer, and Snowball project is licensed under BSD, (see http://snowball.tartarus.org/license.php) so I guess we can distribute the data for testing with nltk. Let me know if that works for the project, and where should I put it if so.

**Comment by stevenbird** [comment]
I would be happy to add the snowball test data to the NLTK data collection. Then you could access it via a corpus reader, and put your test code under `test/unit` as you suggest. Would that work?

**Comment by Madrigal** [comment]
Yes, that would be really nice :)

**Comment by stevenbird** [comment]
Sure. I've opened an issue for this, https://github.com/nltk/nltk_data/issues/21

**Comment by stevenbird** [comment]
I've uploaded the snowball test data. You probably need to set up a corpus reader like `PPAttachmentCorpusReader`. We could refactor things to have a corpus reader that handles files consisting of whitespace-delimited fields, and which calls a supplied factory function on the fields.

**Pull request merged**
