### PR TITLE
First try at travis

### PR DESCRIPTION
**Pull request by alvations**
Stabbing #2098

### CODE REVIEW

**Comment by alvations** [comment]
Now that's much better, we got travis to work. Lets track the tasks from #2098 here instead:

Moving on, lets track what we need to do while migrating to Travis:

 - **Setting up tox on `.travis.yml`**
     ✔Keeping the matrix we use from Jenkins
     ✔ Tests on Py2.7, 3.5 and 3.6
     ✔ Clean up `tox.ini` and separate tests for pure python CI and third-party CI (e.g. Senna, Stanford CoreNLP and Stanford NLP tools)
     ~: test on Py3.7~ (not yet supported)

-  **Setting up `after-success` instructions**
    ✔ setting up `coverage` and checking `nosetest` outputs
    ✔ run through pylint

 - **Documentation for Continuous Integration** 
    ✔ Deprecation of the cloudbees (cleanup jenkins related scripts)
    ✔ Explain how the `.travis.yml` and `tox` works.
    ✔How to setup and run tox tests locally
    
____ 

Perhaps in another PR: 

- **Additional builds**
     - Make sure `book` build works and finally regular build passes?? (Do we have specific tests for `nltk_book` related code?)

 - **Other custom builds that we need** [If possible but maybe another PR] 
    - Setting up flake8 environment 
    - Cython / Binarized build #2094
    - Checks for vulnerable build #1976

 - **Clearing out pylint messages**
     - See https://gist.github.com/alvations/92e704b733a9ef22489d7fbab5510612

**Comment by alvations** [comment]
Looks like the old neural dep parser API for  the NLP is choking up the doctest. Should we skip the test for the neural dep parser on CI in favour of proper tests for the the corenlp later on?

**Comment by alvations** [comment]
While going through the tox setup, I found that we've been ignoring all the warnings from `pylint` and piping it out without anyone looking into the problems =( 

```
pylint -f parseable nltk > pylintoutput
```

And that's causing > 10 mins choked up on the CI... I think we should run this locally and resolve the issues from  the local pylint log first, then re-enable them in CI. 

Here's the 20,000+ lines of pylint output: https://gist.github.com/alvations/75a7a602d5e1f0db3f7fb8dc6c482492

List of issues includes:

```
Counter({'C0103(invalid-name)': 3608,
         'W0614(unused-wildcard-import)': 1785,
         'C0326(bad-whitespace)': 1754,
         'C0111(missing-docstring)': 1606,
         'C0330(bad-continuation)': 1551,
         'C0321(multiple-statements)': 987,
         'C0301(line-too-long)': 755,
         'C0303(trailing-whitespace)': 529,
         'W0212(protected-access)': 418,
         'R1705(no-else-return)': 416,
         'W0613(unused-argument)': 363,
         'R0201(no-self-use)': 259,
         'W0612(unused-variable)': 247,
         'W1401(anomalous-backslash-in-string)': 232,
         'R0205(useless-object-inheritance)': 192,
         'R0913(too-many-arguments)': 188,
         'E0611(no-name-in-module)': 185,
         'W0221(arguments-differ)': 166,
         'C1801(len-as-condition)': 154,
         'W0201(attribute-defined-outside-init)': 152,
         'R0914(too-many-locals)': 142,
         'W0401(wildcard-import)': 141,
         'W0621(redefined-outer-name)': 140,
         'W0611(unused-import)': 136,
         'R0401(cyclic-import)': 132,
         'R0801(duplicate-code)': 127,
         'E1101(no-member)': 126,
         'W0622(redefined-builtin)': 117,
         'W0223(abstract-method)': 112,
         'R0912(too-many-branches)': 90,
         'R1710(inconsistent-return-statements)': 87,
         'C0411(wrong-import-order)': 86,
         'C0325(superfluous-parens)': 84,
         'R0903(too-few-public-methods)': 83,
         'R0902(too-many-instance-attributes)': 59,
         'C0413(wrong-import-position)': 57,
         'W0311(bad-indentation)': 49,
         'C0200(consider-using-enumerate)': 47,
         'W0102(dangerous-default-value)': 46,
         'R1702(too-many-nested-blocks)': 45,
         'R0915(too-many-statements)': 43,
         'W0702(bare-except)': 39,
         'C0121(singleton-comparison)': 38,
         'W0231(super-init-not-called)': 38,
         'C0305(trailing-newlines)': 36,
         'W0511(fixme)': 35,
         'R0911(too-many-return-statements)': 28,
         'W0105(pointless-string-statement)': 26,
         'E0202(method-hidden)': 25,
         'R1714(consider-using-in)': 25,
         'W0404(reimported)': 24,
         'W0703(broad-except)': 23,
         'C0302(too-many-lines)': 21,
         'C0412(ungrouped-imports)': 20,
         'W0108(unnecessary-lambda)': 20,
         'E1120(no-value-for-parameter)': 19,
         'W0601(global-variable-undefined)': 18,
         'C0410(multiple-imports)': 16,
         'C0123(unidiomatic-typecheck)': 13,
         'R0904(too-many-public-methods)': 11,
         'W0312(mixed-indentation)': 11,
         'E0602(undefined-variable)': 11,
         'C0202(bad-classmethod-argument)': 11,
         'R1706(consider-using-ternary)': 10,
         'W0631(undefined-loop-variable)': 9,
         'W0301(unnecessary-semicolon)': 9,
         'W0603(global-statement)': 8,
         'R1708(stop-iteration-return)': 8,
         'W1505(deprecated-method)': 8,
         'W0640(cell-var-from-loop)': 8,
         'E1136(unsubscriptable-object)': 7,
         'R1704(redefined-argument-from-local)': 7,
         'W0406(import-self)': 7,
         'W0101(unreachable)': 7,
         'W0123(eval-used)': 6,
         'E0401(import-error)': 6,
         'R1711(useless-return)': 6,
         'E1121(too-many-function-args)': 6,
         'C0304(missing-final-newline)': 6,
         'W0233(non-parent-init-called)': 6,
         'E0102(function-redefined)': 5,
         'W0402(deprecated-module)': 5,
         'C0112(empty-docstring)': 5,
         'W0104(pointless-statement)': 5,
         'R1718(consider-using-set-comprehension)': 5,
         'R0901(too-many-ancestors)': 5,
         'R1717(consider-using-dict-comprehension)': 5,
         'W0106(expression-not-assigned)': 4,
         'R1701(consider-merging-isinstance)': 4,
         'E0203(access-member-before-definition)': 4,
         'E1133(not-an-iterable)': 4,
         'W0706(try-except-raise)': 4,
         'R1715(consider-using-get)': 4,
         'W1305(format-combined-specification)': 4,
         'E1102(not-callable)': 4,
         'W0642(self-cls-assignment)': 3,
         'C0113(unneeded-not)': 3,
         'W0235(useless-super-delegation)': 3,
         'W0107(unnecessary-pass)': 3,
         'R1712(consider-swap-variables)': 3,
         'W0125(using-constant-test)': 2,
         'C0122(misplaced-comparison-constant)': 2,
         'W0623(redefine-in-handler)': 2,
         'E0213(no-self-argument)': 2,
         'W0120(useless-else-on-loop)': 2,
         'R1703(simplifiable-if-statement)': 2,
         'W1113(keyword-arg-before-vararg)': 2,
         'R0916(too-many-boolean-expressions)': 2,
         'E1130(invalid-unary-operand-type)': 2,
         'W0222(signature-differs)': 2,
         'E0302(unexpected-special-method-signature)': 1,
         'C0414(useless-import-alias)': 1,
         'W0641(possibly-unused-variable)': 1,
         'W0143(comparison-with-callable)': 1,
         'E0704(misplaced-bare-raise)': 1,
         'W0122(exec-used)': 1,
         'E1305(too-many-format-args)': 1,
         'E0632(unbalanced-tuple-unpacking)': 1,
         'R1716(chained-comparison)': 1,
         'W0715(raising-format-tuple)': 1,
         'C0102(blacklisted-name)': 1,
         'W1202(logging-format-interpolation)': 1,
         'E1300(bad-format-character)': 1,
         'R0123(literal-comparison)': 1})
```

**Comment by alvations** [comment]
Now, it's a little better but there's surely room for someone to sit through the pylint output and work through them =)

```
Your code has been rated at 6.20/10 (previous run: 6.08/10, +0.12)
```

Here's the latest pylint output: https://gist.github.com/alvations/92e704b733a9ef22489d7fbab5510612

```
$ python3 -c "from collections import Counter; import re; from pprint import pprint; pprint(Counter(re.findall(r'.*\.py\:\d+\: \[([A-Za-z0-9]+\([A-Za-z0-9-]+\))\,', open('nltk/test/pylintoutput-12SEP18').read())))"
Counter({'C0103(invalid-name)': 3608,
         'W0614(unused-wildcard-import)': 1785,
         'C0326(bad-whitespace)': 1754,
         'C0111(missing-docstring)': 1606,
         'C0330(bad-continuation)': 1547,
         'C0321(multiple-statements)': 987,
         'C0301(line-too-long)': 758,
         'W0212(protected-access)': 418,
         'R1705(no-else-return)': 416,
         'W0613(unused-argument)': 363,
         'R0201(no-self-use)': 259,
         'W0612(unused-variable)': 247,
         'W1401(anomalous-backslash-in-string)': 232,
         'R0205(useless-object-inheritance)': 192,
         'R0913(too-many-arguments)': 188,
         'E0611(no-name-in-module)': 185,
         'W0221(arguments-differ)': 165,
         'C1801(len-as-condition)': 154,
         'W0201(attribute-defined-outside-init)': 152,
         'R0914(too-many-locals)': 142,
         'W0401(wildcard-import)': 141,
         'W0621(redefined-outer-name)': 140,
         'W0611(unused-import)': 136,
         'R0401(cyclic-import)': 128,
         'R0801(duplicate-code)': 127,
         'E1101(no-member)': 126,
         'W0622(redefined-builtin)': 117,
         'W0223(abstract-method)': 112,
         'R0912(too-many-branches)': 90,
         'R1710(inconsistent-return-statements)': 87,
         'C0325(superfluous-parens)': 84,
         'R0903(too-few-public-methods)': 83,
         'C0411(wrong-import-order)': 80,
         'R0902(too-many-instance-attributes)': 59,
         'C0413(wrong-import-position)': 56,
         'C0200(consider-using-enumerate)': 47,
         'W0102(dangerous-default-value)': 46,
         'R1702(too-many-nested-blocks)': 45,
         'R0915(too-many-statements)': 43,
         'W0702(bare-except)': 39,
         'W0231(super-init-not-called)': 38,
         'C0121(singleton-comparison)': 37,
         'W0511(fixme)': 35,
         'C0305(trailing-newlines)': 30,
         'R0911(too-many-return-statements)': 28,
         'W0105(pointless-string-statement)': 26,
         'E0202(method-hidden)': 25,
         'R1714(consider-using-in)': 25,
         'W0404(reimported)': 24,
         'W0703(broad-except)': 23,
         'C0302(too-many-lines)': 21,
         'C0412(ungrouped-imports)': 20,
         'W0108(unnecessary-lambda)': 20,
         'E1120(no-value-for-parameter)': 19,
         'W0601(global-variable-undefined)': 18,
         'C0410(multiple-imports)': 16,
         'C0123(unidiomatic-typecheck)': 13,
         'R0904(too-many-public-methods)': 11,
         'W0312(mixed-indentation)': 11,
         'E0602(undefined-variable)': 11,
         'C0202(bad-classmethod-argument)': 11,
         'C0303(trailing-whitespace)': 10,
         'R1706(consider-using-ternary)': 10,
         'W0631(undefined-loop-variable)': 9,
         'W0301(unnecessary-semicolon)': 9,
         'W0603(global-statement)': 8,
         'R1708(stop-iteration-return)': 8,
         'W1505(deprecated-method)': 8,
         'W0640(cell-var-from-loop)': 8,
         'E1136(unsubscriptable-object)': 7,
         'R1704(redefined-argument-from-local)': 7,
         'W0406(import-self)': 7,
         'W0101(unreachable)': 7,
         'W0123(eval-used)': 6,
         'E0401(import-error)': 6,
         'R1711(useless-return)': 6,
         'E1121(too-many-function-args)': 6,
         'W0233(non-parent-init-called)': 6,
         'E0102(function-redefined)': 5,
         'W0402(deprecated-module)': 5,
         'C0112(empty-docstring)': 5,
         'W0104(pointless-statement)': 5,
         'C0304(missing-final-newline)': 5,
         'R1718(consider-using-set-comprehension)': 5,
         'R0901(too-many-ancestors)': 5,
         'R1717(consider-using-dict-comprehension)': 5,
         'W0106(expression-not-assigned)': 4,
         'R1701(consider-merging-isinstance)': 4,
         'E0203(access-member-before-definition)': 4,
         'E1133(not-an-iterable)': 4,
         'W0706(try-except-raise)': 4,
         'R1715(consider-using-get)': 4,
         'W1305(format-combined-specification)': 4,
         'E1102(not-callable)': 4,
         'W0642(self-cls-assignment)': 3,
         'C0113(unneeded-not)': 3,
         'W0235(useless-super-delegation)': 3,
         'W0107(unnecessary-pass)': 3,
         'R1712(consider-swap-variables)': 3,
         'W0125(using-constant-test)': 2,
         'C0122(misplaced-comparison-constant)': 2,
         'W0623(redefine-in-handler)': 2,
         'E0213(no-self-argument)': 2,
         'W0120(useless-else-on-loop)': 2,
         'R1703(simplifiable-if-statement)': 2,
         'W1113(keyword-arg-before-vararg)': 2,
         'R0916(too-many-boolean-expressions)': 2,
         'E1130(invalid-unary-operand-type)': 2,
         'W0222(signature-differs)': 2,
         'E0302(unexpected-special-method-signature)': 1,
         'W0641(possibly-unused-variable)': 1,
         'W0143(comparison-with-callable)': 1,
         'E0704(misplaced-bare-raise)': 1,
         'W0122(exec-used)': 1,
         'E1305(too-many-format-args)': 1,
         'E0632(unbalanced-tuple-unpacking)': 1,
         'W1202(logging-format-interpolation)': 1})
```

**Comment by stevenbird** [comment]
Thanks @alvations – much appreciated!

**Pull request merged**
