### PR TITLE
Use Extended OMW

### PR DESCRIPTION
**Pull request by ekaf**
This PR is a simpler alternative to #2924 with additional capabilities. 

1. It provides a leaner extended_wordnet class that can be used with any Wordnet version, f. ex. the recent wordnet2021:

> import nltk
> from nltk.corpus import wordnet2021 as wn
> print(f"Loaded Wordnet v. {wn.get_version()} with {len(wn.langs())} languages from OMW-1.4")

`Loaded Wordnet v. 2021 with 32 languages from OMW-1.4
`
> wn.add_exomw()
> print(f"Loaded {len(wn.langs())} languages in total with Extended OMW")

`Loaded 1192 languages in total with Extended OMW
`

> ss=wn.synset('intrinsically.r.01')
> print(ss.lemmas(lang="eng"))

`[Lemma('intrinsically.r.01.intrinsically'), Lemma('intrinsically.r.01.per_se'), Lemma('intrinsically.r.01.in_and_of_itself')]
`

2. This PR can load the English wiktionary wordnet. Different versions of the same language are kept separate, which allows to compare them:

> print(ss.lemmas(lang="eng_wikt"))

`[Lemma('intrinsically.r.01.per_se'), Lemma('intrinsically.r.01.as_such')]`

3. It is still possible to use the set union of different variants of the same language:

> print(set(ss.lemmas(lang="eng")).union(set( ss.lemmas(lang="eng_wikt"))))

`{Lemma('intrinsically.r.01.per_se'), Lemma('intrinsically.r.01.in_and_of_itself'), Lemma('intrinsically.r.01.as_such'), Lemma('intrinsically.r.01.intrinsically')}
`

Thanks to @ExplorerFreda for inspiration!

### CODE REVIEW

**Comment by ekaf** [comment]
Running pytest locally complains that the fixture "mocker" is not found in nltk/test/conftest.py, line 6 ...

**Comment by tomaarsen** [comment]
I ran a quick `pre-commit run --all` over your code to solve the pre-commit issues 👍

**Comment by ekaf** [comment]
Thanks @tomaarsen, the problem was that I had forgotten to initialize the provenance of the default English language.

**Comment by ekaf** [comment]
This PR also solves #2951, by  using a LazyCorpusLoader class to read the eventually zipped "index.sense" file (at line 1220 in wordnet.py).

**Comment by stevenbird** [comment]
Thanks @ekaf, @tomaarsen

**Pull request merged**
