### PR TITLE
Language Modeling

### PR DESCRIPTION
**Pull request by iliakur**
Ok, after getting some feedback on my previous attempt, I re-worked things a bit.
This time there's tests a-plenty and I've tried to add documentation as well.

I have regression tests for:
* #167 
* #367
* #380 

Since I didn't add the Simple Good Turing estimator yet, can't say anything about the issues related to that. Which brings me to the next point. I spent most of my effort making sure the basic datastructures are useable and robust, so didn't have as much time to add a lot of model classes. I'm hoping that the infrastructure the module provides, however, makes it easy for folks to create models on their own.

Would be nice to merge this into the next release :)

Happy modeling!

### CODE REVIEW

**Comment by iliakur** [comment]
@alvations @stevenbird The tests that fail currently all have to do with python 2 lacking `itertools.accumulate`. `functools.singledispatch` is also probably an issue.

I can easily compensate for `accumulate` but could we add `singledispatch` as a dependency? It's a small module, easily installed.

**Comment by stevenbird** [comment]
@Copper-Head thanks for all this... fine to add this dependency.

**Comment by iliakur** [comment]
Ok, it looks like there's more tweaking that I'll have to do to make python 2.7 happy. I'll get to it soon

**Comment by iliakur** [comment]
Looks like python 2 is now happy :)
What's the drill with adding oneself to the contributors list these days?

**Comment by stevenbird** [comment]
Wow, what a big contribution!

**Comment by stevenbird** [comment]
[CI: retest]

**Comment by stevenbird** [comment]
Thanks @Copper-Head!

**Comment by alvations** [comment]
Thanks @Copper-Head!! An awesome update to the model package!!

**Comment by iliakur** [comment]
lol, only took me... 4 years ;)

**Comment by stevenbird** [comment]
How about announcing it on nltk-dev?

**Comment by iliakur** [comment]
Sure!
Which release will this appear in?

**Comment by stevenbird** [comment]
The next one... once it's packaged I hope you can announce your work on nltk-dev

**Pull request merged**
