### PR TITLE
Adressing issue "nltk.metrics.aline feature map missing IPA symbols #3285"

### PR DESCRIPTION
**Pull request by WilliamPLaCroix**
Added several vowel entries to `metrics/aline.py` under `feature_matrix` in order to conform with [Wikipedia IPA vowel chart](https://en.wikipedia.org/wiki/IPA_vowel_chart_with_audio).

### CODE REVIEW

**Comment by TomerYS** [comment]
Thank you for the work.
It should be also considered to add "mid-low" and "mid-high" stats for the "similarity_matrix" as the IPA chart is divided into 5 main levels.

**Comment by WilliamPLaCroix** [comment]
I considered that, but didn't want to make such a big change, since those
would have to be added to the calculation (maybe just "0.25" and "0.75",
respectively), and I didn't know how much that would affect the algorithm /
function.

**Comment by stevenbird** [comment]
Thanks @WilliamPLaCroix.
I pushed aline.py separately.
I agree about fewer vowel heights.

**Comment by WilliamPLaCroix** [comment]
Thank you @stevenbird.
Would you be willing to add me to the AUTHORS.md contributors list? I forgot to update that with the pull request.
"William LaCroix <https://github.com/WilliamPLaCroix>"

**Pull request closed without merging**
