### PR TITLE
Added Phrase Extraction Algorithm for Phrase-based MT in nltk.align

### PR DESCRIPTION
**Pull request by alvations**
Added the phrase extraction algorithm from Philip Koehn (2009) Statistical Machine Translation book. 
Phrase extraction algorithm found on page 133. Also note that the original book has an error in the algorithm, see errata http://www.statmt.org/book/errata.html.

### CODE REVIEW

**Comment by alvations** [comment]
Possibly, the `phrase_based.py` needs to also have a module that generates the phrase tables with the probabilities but for now, the `phrase_extraction()` is usable for people who wants to extract phrases and use other ways to normalize/calculate the phrase probabilities.

**Comment by stevenbird** [comment]
@alvations thanks for the contribution -- would you please take a look at https://github.com/nltk/nltk/wiki/Developers-Guide and follow our coding practices?

**Comment by alvations** [comment]
@stevenbird , really sorry about the bare commenting of the code. I forgot to push the with the proper doctest and comments. i'll push the code up in a min.

**Comment by alvations** [comment]
about some of the weird and not so useful comment. It's because that's what shown in the algorithm in Koehn's SMT book. It might be useful for readers/learners to see the corresponding lines in the algorithm. http://i.stack.imgur.com/0j556.png.

**Comment by stevenbird** [comment]
I agree that it would be good to retain Koehn's original comments.

**Comment by stevenbird** [comment]
Would you also please update your code to work with Python 3 (use 2to3).
Can you avoid nested functions? I don't understand why you've put `extract()` inside `phrase_extraction()`.

**Comment by alvations** [comment]
I guess the spaghetti functions are a little ugly but it's to avoid over-verbosity. It also shields users from using the wrong function in `phrase_based.py` and less parameters transfer from the `phrase_extraction()` to `extract()`. I've untangled the nested functions.

**Comment by stevenbird** [comment]
This looks good now, thanks.

**Pull request merged**
