### PR TITLE
Add chomsky_normal_form for CFGs

### PR DESCRIPTION
**Pull request by virresh**
https://github.com/nltk/nltk/issues/1884

Am a bit unfamiliar with tox style of tests
Would be happy to add a CKY implementation and test the grammar converter as well if someone can guide me to the correct files for including tests and a parser

### CODE REVIEW

**Comment by virresh** [comment]
Also in the Contribution Guidelines, it was written to follow Pep8, but while coding I observed pep8 is not followed uniformly, is there any subset of rules used from Pep8?

O/w maybe we can enforce a Pep8 check via a linter?

**Comment by stevenbird** [comment]
@virresh - thanks for the contribution; are you able to take a look in the nltk/test directory for examples of approaches to testing please?

**Comment by virresh** [comment]
Hello
I've added two unit tests, not sure how to go about the doctests though
Also rebased my branch for confllct resolution

**Comment by stevenbird** [comment]
Thanks @virresh

**Pull request merged**
