### PR TITLE
gitignore generated test files, resolves #1629

### LINKED ISSUE #1629: Unknown XML files in main repo directory
There are these files that somehow got into the repository in #1429 

 - nosetests.xml
- nosetests_scrubbed.xml
- coverage.xml

@adamn Are these files from your debug log? Or are they necessary for actual tests?

### PR DESCRIPTION
**Pull request by adamn**
This also brings the ignore file slightly closer to Github's recommended Python.gitignore:

https://github.com/github/gitignore/blob/master/Python.gitignore

### CODE REVIEW

**Comment by fievelk** [comment]
[CI: retest]

**Comment by fievelk** [comment]
retest this please

**Comment by fievelk** [comment]
retest this please Jenkins

**Comment by fievelk** [comment]
CI: retest

**Comment by fievelk** [comment]
[CI: retest]

**Comment by stevenbird** [comment]
Thanks @adamn

**Pull request merged**
