### PR TITLE
Issue #1859: TypeError in HiddenMarkovModelTrainer train_unsupervised

### PR DESCRIPTION
**Pull request by PavanGJ**
Added a method definition for abstract method max in RandomProbDist and MutableProbDist classes.

### CODE REVIEW

**Comment by stevenbird** [comment]
@PavanGJ would you please document the reason for this PR

**Comment by PavanGJ** [comment]
Hi @stevenbird 

This PR fixes a bug reported in #1859.

RandomProbDist and MutableProbDist extend ProbDistI which defines an abstract method max. The abstract method is not overridden in RandomProbDist and MutableProbDist causing errors such as 
<code>TypeError: Can't instantiate abstract class RandomProbDist with abstract methods max</code>

When a model is not defined, HiddenMarkovModelTagger uses both RandomProbDist and MutableProbDist in train_unsupervised method.

This PR defines the method max in the two classes to overcome this bug.

**Comment by PavanGJ** [comment]
@stevenbird Kindly let me know if I need to document the reason for this PR elsewhere

**Comment by stevenbird** [comment]
Excellent, thanks @PavanGJ.

**Pull request merged**
