### PR TITLE
fixes tests in py3.8

### PR DESCRIPTION
**Pull request by srhrshr**
@Copper-Head this is in response to your post on the `nltk-dev` google group to test out the repository against python version 3.8.0. 

There were a few hiccups setting up the dev environment with the requirements compatible with the python 3.8 version as running `pip install -r pip-req.txt` didn't directly work on my machine. I ended up having to install the `scipy` and `scikit-learn` dependencies from source. You can find the full list of requirements on my virtualenv [here](https://github.com/nltk/nltk/files/3745812/virtualenv-reqts.txt). 

In order to run the tests, I ran `python nltk/test/runtests.py` and fixed the import errors etc that I ran into along the way. This PR is a diff of changes I made for this. 

Does this state of the logs show that tests ran successfully?
```
...................................................S..S.......SS....................SSSSSSSS............................................S....................SSSS...............................................nltk/nltk/test/unit/test_tokenize.py:60: DeprecationWarning: 
The StanfordTokenizer will be deprecated in version 3.2.5.
Please use nltk.parse.corenlp.CoreNLPTokenizer instead.'
  seg = StanfordSegmenter()
Snltk/nltk/test/unit/test_tokenize.py:86: DeprecationWarning: 
The StanfordTokenizer will be deprecated in version 3.2.5.
Please use nltk.parse.corenlp.CoreNLPTokenizer instead.'
  seg = StanfordSegmenter()
S................................
----------------------------------------------------------------------
Ran 660 tests in 194.011s

OK (SKIP=34)
```

Also, running `tox -v py38` didn't directly work because the tox.ini file was not configured to work with python 3.8 (Duh!). But, I can adapt and run this too if this is how you want me to test.  Let me know. 

Thanks,
Harsha

### CODE REVIEW

**Comment by iliakur** [comment]
@alvations or @stevenbird know this better than me, but I would suggest starting with the tox environment and getting that to work first. If there's a mismatch between that and the local setups of those using 3.8 we should fix it separately.

Getting tox to work has the advantage that it'll also get tested by the github CI and we can officially say we support 3.8 until someone complains about their local setup (not a likely scenario).

**Comment by srhrshr** [comment]
The problem with setting up a tox environment is scipy isn't installable via pip and I had to build from source in my venv to get it to work. Looks like scipy is working on releasing a 3.8 compatible version: https://github.com/scipy/scipy/issues/10927. 

So, what do you suggest I do - is there a way to build from source while setting up a tox environment ?

**Comment by iliakur** [comment]
I'd go down the path of least resistance and set up an alert of some kind to notify me when scipy starts supporting 3.8 and then attempt stuff with NLTK.
The easiest would be to subscribe to that issue

This is the cost of having dependencies...

If, of course, you have time and interest, you could help adding 3.8 support to scipy, that's the more proactive approach.

**Comment by srhrshr** [comment]
scipy is close to a release and I've subscribed to their issue re this. Will take this up as soon as they've released the wheels.

**Comment by stevenbird** [comment]
[CI: retest]

**Comment by stevenbird** [comment]
[CI: retest]

**Comment by iliakur** [comment]
@srhrshr any luck getting this to work?

**Comment by srhrshr** [comment]
Will take this up this weekend. You can expect some chatter from me in about 12 hours.

**Comment by alvations** [comment]
Thank you @srhrshr for the help in testing NLTK for python 3.8. We sorely need this =)

Any idea why  the python 3.8 isn't kicked in on the CI from the `.travis.yml`? I'll check the CI to see why that's happening too.

**Comment by srhrshr** [comment]
No worries @alvations - that must be because I didn't update the travis.yml - hopefully it should trigger now. 

Btw, here is a detailed log of the local tox run. 

**tested w/ python 3.8.0:**

```py38 run-test: commands[1] | python runtests.py
-........................................................-...................
.........-.....-.................-........-..................................
…..-/…./nltk/nltk/tokenize/stanford_segmenter.py:305: DeprecationWarning:
The StanfordTokenizer will be deprecated in version 3.2.5.
Please use nltk.parse.corenlp.CoreNLPTokenizer instead.'
  seg = StanfordSegmenter()
-....................................................................-.
...-....-.....-.-..-.......-..-..............................................
.............................................................................
.............................................................................
.......................-..-.......--....................--------.............
.................................-....................----...................
………………………./…../nltk/nltk/test/unit/test_tokenize.py:60: DeprecationWarning:
The StanfordTokenizer will be deprecated in version 3.2.5.
Please use nltk.parse.corenlp.CoreNLPTokenizer instead.'
  seg = StanfordSegmenter()
-/…../nltk/nltk/test/unit/test_tokenize.py:86: DeprecationWarning:
The StanfordTokenizer will be deprecated in version 3.2.5.
Please use nltk.parse.corenlp.CoreNLPTokenizer instead.'
  seg = StanfordSegmenter()
-................................

-----------------------------------------------------------------------------
678 tests run in 165.804 seconds.
35 skipped (643 tests passed)
__________________________________________________________________________________ summary __________________________________________________________________________________
  py38: commands succeeded
  congratulations :)
```


——————————————————————————————————————

**tested w/ python 3.7.4:**

```py37 run-test: commands[1] | python runtests.py
-........................................................-...................
.........-.....-.................-........-..................................
…..-….nltk/nltk/tokenize/stanford_segmenter.py:305: DeprecationWarning:
The StanfordTokenizer will be deprecated in version 3.2.5.
Please use nltk.parse.corenlp.CoreNLPTokenizer instead.'
  seg = StanfordSegmenter()
-....................................................................-.
...-....-.....-.-..-.......-..-..............................................
.............................................................................
.............................................................................
.......................-..-.......--....................--------.............
.................................-....................----...................
………………………./…/nltk/nltk/test/unit/test_tokenize.py:60: DeprecationWarning:
The StanfordTokenizer will be deprecated in version 3.2.5.
Please use nltk.parse.corenlp.CoreNLPTokenizer instead.'
  seg = StanfordSegmenter()
-…/nltk/nltk/test/unit/test_tokenize.py:86: DeprecationWarning:
The StanfordTokenizer will be deprecated in version 3.2.5.
Please use nltk.parse.corenlp.CoreNLPTokenizer instead.'
  seg = StanfordSegmenter()
-................................

-----------------------------------------------------------------------------
678 tests run in 174.890 seconds.
35 skipped (643 tests passed)
__________________________________________________________________________________ summary __________________________________________________________________________________
  py37: commands succeeded
  congratulations :)
```
——————————————————————————————————————

**tested w/ python 3.6.9:**

```py36 run-test: commands[1] | python runtests.py
-........................................................-...................
.........-.....-.................-........-..................................
…..-…nltk/nltk/tokenize/stanford_segmenter.py:305: DeprecationWarning:
The StanfordTokenizer will be deprecated in version 3.2.5.
Please use nltk.parse.corenlp.CoreNLPTokenizer instead.'
  seg = StanfordSegmenter()
-....................................................................-.
...-....-.....-.-..-.......-..-..............................................
.............................................................................
.............................................................................
.......................-..-.......--....................--------.............
.................................-....................----...................
…………………………./nltk/nltk/test/unit/test_tokenize.py:60: DeprecationWarning:
The StanfordTokenizer will be deprecated in version 3.2.5.
Please use nltk.parse.corenlp.CoreNLPTokenizer instead.'
  seg = StanfordSegmenter()
-../nltk/nltk/test/unit/test_tokenize.py:86: DeprecationWarning:
The StanfordTokenizer will be deprecated in version 3.2.5.
Please use nltk.parse.corenlp.CoreNLPTokenizer instead.'
  seg = StanfordSegmenter()
-................................

-----------------------------------------------------------------------------
678 tests run in 167.563 seconds.
35 skipped (643 tests passed)
__________________________________________________________________________________ summary __________________________________________________________________________________
  py36: commands succeeded
  congratulations :)
```

——————————————————————————————————————

**tested w/ python 3.5.4:**
```py35 run-test: commands[1] | python runtests.py
-........................................................-...................
.........-.....-.................-........-..................................
…..-../nltk/nltk/tokenize/stanford_segmenter.py:305: DeprecationWarning:
The StanfordTokenizer will be deprecated in version 3.2.5.
Please use nltk.parse.corenlp.CoreNLPTokenizer instead.'
  seg = StanfordSegmenter()
-....................................................................-.
...-....-.....-.-..-.......-..-..............................................
.............................................................................
.............................................................................
.......................-..-.......--....................--------.............
.................................-....................----...................
………………………./../nltk/nltk/test/unit/test_tokenize.py:60: DeprecationWarning:
The StanfordTokenizer will be deprecated in version 3.2.5.
Please use nltk.parse.corenlp.CoreNLPTokenizer instead.'
  seg = StanfordSegmenter()
-../nltk/nltk/test/unit/test_tokenize.py:86: DeprecationWarning:
The StanfordTokenizer will be deprecated in version 3.2.5.
Please use nltk.parse.corenlp.CoreNLPTokenizer instead.'
  seg = StanfordSegmenter()
-................................

-----------------------------------------------------------------------------
678 tests run in 187.496 seconds.
35 skipped (643 tests passed)
__________________________________________________________________________________ summary __________________________________________________________________________________
  py35: commands succeeded
  congratulations :)
```

**Comment by alvations** [comment]
@srhrshr Thanks for updating the travis yml. Now that looks great!! 

@stevenbird @iliakur I think with `scipy`'s Python 3.8 support upstream, `nltk` should build with 3.8 too.

From the CI side, it looks like it's LGTM for this.

**Review by alvations — APPROVED** [review]

**Comment by stevenbird** [comment]
Thanks @srhrshr and @alvations

**Pull request merged**
