### PR TITLE
Faster Baum-Welch

### PR DESCRIPTION
**Pull request by kmike**
In this pull request most calculations required for HiddenMarkovModelTrainer.train_unsupervised are vectorized; this makes train_unsupervised about 30x faster (number is for demo_pos_bw example).

### CODE REVIEW

**Comment by kmike** [comment]
Initially I was going to introduce a Cython extension (with optimized logaddexp2 and _log_add functions); this extension could make Baum-Welch about 1.5x faster than in this pull request. I decided not to do this now (for simplicity) - 1.5x speed difference is not that critical.

**Comment by kmike** [comment]
There are ways to improve this further in future (e.g. some matrices are re-calculated many times in this pull request).

**Comment by kmike** [comment]
Cython extension code (unused in the final result): https://gist.github.com/kmike/5278404

**Comment by stevenbird** [comment]
Thanks for a great contribution.

**Pull request merged**
