### PR TITLE
move splitta code into nltk/tokenize

### PR DESCRIPTION
**Pull request by swizzard**
_DO NOT MERGE_ (not that anyone would...)

This is "pre-alpha" code. I really just want feedback.

### CODE REVIEW

**Comment by stevenbird** [comment]
@swizzard sorry for the delay – would you please ask on nltk-dev for feedback?

**Comment by stevenbird** [comment]
@swizzard – would you like to get this into 3.1? I'm hoping to package a new release this week.

**Comment by swizzard** [comment]
@stevenbird it's currently non-functional--the results are TERRIBLE--and I don't have the time or resources to improve it. If someone else wants to pick this ball up and run with it, they should, but I can't.

**Comment by stevenbird** [comment]
@swizzard – thanks for the update; no problem. I'll close this for now. The feature request still exists in #181.

**Pull request closed without merging**
