### PR TITLE
add index check for handles_nonbreaking_prefixes

### PR DESCRIPTION
**Pull request by lmatt-bit**
token[i] could be the last element, add check to prevent exception.

### CODE REVIEW

**Comment by alvations** [comment]
@lmatt-bit Would you be able illustrate what the patch fixes in 1-2 examples and add it to the doctest? That'll be helpful for users and learners to know why the patch is added =)

Thanks in advance!

**Comment by alvations** [comment]
Also it seems like #1768 is trying to fix the same issue =)

**Comment by lmatt-bit** [comment]
@alvations, i just found that #1768 is fixing the same issue.

**Comment by alvations** [comment]
@lmatt-bit Thanks for the doctest example! If you don't mind, could you add your name and "Shenjian Zhao" (@SwordYork) to the [`AUTHORS.md`](https://github.com/nltk/nltk/blob/develop/AUTHORS.md))? 

Thereafter this PR looks good to merge.

**Comment by lmatt-bit** [comment]
No problem. Updated.

**Review by alvations — APPROVED** [review]

**Comment by stevenbird** [comment]
Thanks @lmatt-bit

**Pull request merged**
