### PR TITLE
Fix more nltk.six imports

### PR DESCRIPTION
**Pull request by ExplodingCabbage**
I get ImportErrors when trying to run tox otherwise; as far as I can tell, this case is the same as eebeab6?

### CODE REVIEW

**Comment by ExplodingCabbage** [comment]
(Possibly this change is misguided in some way. The tests are royally screwed for me anyway, as noted in https://github.com/nltk/nltk/issues/1466, so it's difficult for me to tell if changes that I think are fixes are actually appropriate.)

**Comment by dimazest** [comment]
it fixes the moses tests for me if I run

```
tox -e py35,py27 -- nltk.tokenize.moses
```

**Comment by jnothman** [comment]
Is the convention to block these imports with the other nltk imports? Otherwise, LGTM

**Comment by stevenbird** [comment]
nltk.six is gone so this PR is stale

**Pull request closed without merging**
