### PR TITLE
Fix for mutable default argument

### PR DESCRIPTION
**Pull request by timgianitsos**
https://docs.python.org/3.6/tutorial/controlflow.html#default-argument-values
https://docs.python-guide.org/writing/gotchas/

### CODE REVIEW

**Review by jnothman — APPROVED** [review]
LGTM (although a test wouldn't hurt even if we didn't bother with much of them a decade ago)

**Comment by alvations** [comment]
[CI: retest]

**Comment by alvations** [comment]
Now, it looks good+safe to merge with the doctest =)

**Comment by stevenbird** [comment]
Thanks @timgianitsos @jnothman @alvations

**Pull request merged**
