### PR TITLE
Refactor and slightly optimize metrics.scores

### PR DESCRIPTION
**Pull request by larsmans**
Some small stuff.

### CODE REVIEW

**Comment by xim** [comment]
Sorry, but the request still references your old commit. Could you place the change on top of it or resubmit the request? =)

**Comment by stevenbird** [comment]
Morten -- is there a reason we can't merge this?

**Comment by xim** [comment]
It imports izip but doesn't use it. Author made a fix, but the commit doesn't reference it. I'll just do it manually!

**Comment by xim** [comment]
dcdf5095c364caa7b3c507c52693780f22d80085 merges 8eeac2779b13b339ef8318878ad02d3b445f2fbf and uses izip

**Pull request closed without merging**
