### PR TITLE
use data.load for vader lexicon

### PR DESCRIPTION
**Pull request by afgiel**
this is in response to https://github.com/nltk/nltk/issues/1296

### CODE REVIEW

**Comment by afgiel** [comment]
accompanying `nltk_data` PR https://github.com/nltk/nltk_data/pull/46

**Comment by stevenbird** [comment]
@afgiel – would you please confirm that this works with the new data location?

**Comment by afgiel** [comment]
@stevenbird using `nltk.download()` puts the `.zip` into `nltk_data/sentiment` but it seems that `nltk.data.load` has trouble dealing with `.zip` files? How does one deal with the `.zip` when we really need a `.txt`?

**Comment by alvations** [comment]
The zipfile problem should be resolved with the recent fixes #1302 . If the ZipFile objects still having problems, drop me a ping.

**Comment by afgiel** [comment]
thanks for the help @alvations 

@stevenbird 
after rebasing, changing a few things, and squashing the old commits I think this works 

```
➜  nltk git:(load_vader_lexicon) ipython
Python 2.7.5 (default, Mar  9 2014, 22:15:05)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import nltk

In [2]: from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "
```

try once without the proper data (`LookupError` expected)

```
In [3]: analyzer = SentimentIntensityAnalyzer()
---------------------------------------------------------------------------
LookupError                               Traceback (most recent call last)
<ipython-input-3-7c921544b6cf> in <module>()
----> 1 a = SentimentIntensityAnalyzer()

/Users/agiel/open_source/nltk/nltk/sentiment/vader.pyc in __init__(self, lexicon_file)
    199     """
    200     def __init__(self, lexicon_file="sentiment/vader_lexicon.zip/vader_lexicon/vader_lexicon.txt"):
--> 201         self.lexicon_file = nltk.data.load(lexicon_file)
    202         self.lexicon = self.make_lex_dict()
    203

/Users/agiel/open_source/nltk/nltk/data.pyc in load(resource_url, format, cache, verbose, logic_parser, fstruct_reader, encoding)
    799
    800     # Load the resource.
--> 801     opened_resource = _open(resource_url)
    802
    803     if format == 'raw':

/Users/agiel/open_source/nltk/nltk/data.pyc in _open(resource_url)
    917
    918     if protocol is None or protocol.lower() == 'nltk':
--> 919         return find(path_, path + ['']).open()
    920     elif protocol.lower() == 'file':
    921         # urllib might not use mode='rb', so handle this one ourselves:

/Users/agiel/open_source/nltk/nltk/data.pyc in find(resource_name, paths)
    639     sep = '*' * 70
    640     resource_not_found = '\n%s\n%s\n%s' % (sep, msg, sep)
--> 641     raise LookupError(resource_not_found)
    642
    643

LookupError:
**********************************************************************
  Resource
  u'sentiment/vader_lexicon.zip/vader_lexicon/vader_lexicon.txt'
  not found.  Please use the NLTK Downloader to obtain the
  resource:  >>> nltk.download()
  Searched in:
    - '/Users/agiel/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - u''
**********************************************************************
```

download `vader_lexicon` using `nltk.download()`

```
In [4]: nltk.download()
showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml
Out[4]: True

In [5]: analyzer = SentimentIntensityAnalyzer()

In [6]: print analyzer
<nltk.sentiment.vader.SentimentIntensityAnalyzer object at 0x105c47410>
```

works! :grin:

**Comment by stevenbird** [comment]
Sorry for the delay @afgiel. Working nicely!

**Comment by afgiel** [comment]
@stevenbird just glad it got merged! :tada:

**Pull request merged**
