### PR TITLE
Enhancement/documentation contributing

### PR DESCRIPTION
**Pull request by turicas**
This is not a feature-pull-request: it just organizes the general documentation, authors and how to contribute.

### CODE REVIEW

**Comment by stevenbird** [comment]
Thanks @turicas

**Comment by turicas** [comment]
@stevenbird, you're welcome! ;-)

I've made some fixes -- the only missing information now is the Slack URL, I think.

**Comment by stevenbird** [comment]
Thanks @turicas. I think I need to create a public channel first...

**Comment by stevenbird** [comment]
It turns out that Slack doesn't support this, and they even [blocked a work-around](http://wiredcraft.com/blog/using-slack-as-a-public-chat/), so I'm removing the reference to slack.

**Pull request merged**
