### PR TITLE
Allow to map more wordnet versions

### LINKED ISSUE #3117: Wordnet maps only from version 3.0
In _wordnet.py_, the _map_to_many()_ function has limited utility, because the source wordnet version is hard-coded to 3.0. 

Allowing to pass a different source version  as a parameter would make the function more useful, by offering the possibility to produce mappings for other wordnet versions.

### PR DESCRIPTION
**Pull request by ekaf**
Fix #3117: add a _version_ parameter to the _map_to_many()_ function in _wordnet.py_, so that mappings can be produced for other versions than the hard-coded Wordnet 3.0.

For example:

```
from nltk.corpus import wordnet2021 as wn

v1 = "wordnet31"

mymap = wn.map_to_many(version=v1)

gone = []
splits = {}

for of in sorted(list(mymap.keys())):
    if mymap[of] == []:
        gone.append(of)
    elif len(set(mymap[of])) > 1:
        splits[of]=set(mymap[of])

print(f"{len(gone)} synsets were removed between {v1} and {wn.get_version()}: {gone}\n")

print(f"{len(splits)} synsets were split between {v1} and {wn.get_version()}:")
for of in splits:
    print(f"{of} -> {splits[of]}")
```

80 synsets were removed between wordnet31 and 2021: ['00021452-r', '00172544-r', '00192093-r', '00387850-r', '00401647-v', '00427109-v', '00447396-n', '00479613-v', '00506084-s', '00521840-v', '00550851-v', '00551895-s', '00597025-v', '00723361-v', '01086999-v', '01087135-v', '01091853-s', '01151793-v', '01174521-n', '01211645-v', '01409010-v', '01535138-s', '01558420-s', '01630972-n', '01770259-v', '01828281-v', '01916702-v', '01926192-s', '02098854-a', '02099131-s', '02099277-s', '02111676-s', '02202748-v', '02209716-s', '02235408-s', '02257563-v', '02340948-s', '02341139-s', '02369766-v', '02449821-s', '02646619-n', '02751757-v', '02768257-v', '02801550-a', '02943799-a', '03739038-n', '04045203-n', '04264001-n', '04928485-n', '04971976-n', '05694760-n', '06234997-n', '06631572-n', '07249395-n', '08270189-n', '08271662-n', '08659519-n', '08946154-n', '09102940-n', '09162715-n', '09728837-n', '10839657-n', '10988249-n', '11075037-n', '11115577-n', '11164281-n', '11179308-n', '11188503-n', '11339239-n', '11487100-n', '11654084-n', '11657017-n', '11661096-n', '11662414-n', '12786162-n', '12940803-n', '13946615-n', '14297570-n', '14431490-n', '14981196-n']

11 synsets were split between wordnet31 and 2021:
00372225-s -> {'03165775-s', '00372038-s'}
01898672-n -> {'15455508-n', '01914228-n'}
04354832-n -> {'15452790-n', '04391434-n'}
04730186-n -> {'15447720-n', '04769376-n'}
04883756-n -> {'04924349-n', '15451438-n'}
05265220-n -> {'15454555-n', '05310075-n'}
06215945-n -> {'15450961-n', '06264443-n'}
08968866-n -> {'09051689-n', '15455105-n'}
10577282-n -> {'10361894-n', '10668093-n'}
11662881-n -> {'15451564-n', '15450310-n'}
13337744-n -> {'13447536-n', '15455343-n'}

### CODE REVIEW

**Review by tomaarsen — APPROVED** [review]
Looks good to me!

**Comment by arademaker** [comment]
the source wordnet, in the code above 'wn31' need not be imported?

**Comment by ekaf** [comment]
@arademaker, no the source wordnet is not imported, because only its 'index.sense' file is read (by the _index_sense()_ function). Still, in order to be able to read that file, the zip package that contains it needs to be available.
Only the target wordnet is imported. So, the idea is that once you load one target wordnet, you will be able to use _map_to_many()_ to produce a mapping to that target from any source wordnet, without loading it, if you have the source package available.

**Comment by ekaf** [comment]
NB: this PR only changes the map_to_many() function. So it produces mappings to potentially several candidate synsets. This is because also changing the map_to_one() function would interfere with the splits and nomap structures collected in that function, which cover the wordnet 3.0 data from OMW.

But it would be possible to move these structures out of the _map_to_one()_ function, in order to also facilitate building more mappings that select the most frequent target synset.

Some wordnet researchers have requested a way to obtain a list of the splits, so a better solution may be to have an explicit function that yields splits, given the _map_to_many()_ output.

**Comment by ekaf** [comment]
A better solution is to add a level to the 'splits' dictionary, so that it can collect information about different wordnet versions simultaneously. From the users perspective,
this allows to directly obtain _map_to_one()_ mappings, as well as _splits_ and _nomap_ lists for any wordnet version.

Thus, the code [above](https://github.com/nltk/nltk/pull/3118#issue-1569784819) now reduces to:

```
from nltk.corpus import wordnet2021 as wn

v1 = "wordnet31"
mymap = wn.map_to_one(version=v1)

gone = wn.nomap[v1]
splits = wn.splits[v1]

print(f"{len(gone)} synsets were removed between {v1} and {wn.get_version()}: {gone}\n")

print(f"{len(splits)} synsets were split between {v1} and {wn.get_version()}:")
for of in splits:
    print(f"{of} -> {splits[of]}")
```

This produces the same output as above:

80 synsets were removed between wordnet31 and 2021: ['00427109-v', '07249395-n', '02340948-s', '01409010-v', '01151793-v', '02768257-v', '13946615-n', '01174521-n', '00597025-v', '02111676-s', '01211645-v', '02202748-v', '05694760-n', '11339239-n', '11179308-n', '11661096-n', '00521840-v', '02801550-a', '08659519-n', '09728837-n', '09162715-n', '01630972-n', '04971976-n', '11115577-n', '00172544-r', '11164281-n', '04264001-n', '11654084-n', '01770259-v', '08946154-n', '00723361-v', '08270189-n', '04045203-n', '01087135-v', '00506084-s', '01926192-s', '06631572-n', '02449821-s', '12786162-n', '10839657-n', '00479613-v', '10988249-n', '14431490-n', '03739038-n', '11662414-n', '00192093-r', '11188503-n', '11075037-n', '02257563-v', '11657017-n', '00447396-n', '02751757-v', '02098854-a', '02369766-v', '04928485-n', '11487100-n', '02099277-s', '01916702-v', '01828281-v', '06234997-n', '00550851-v', '00401647-v', '01091853-s', '09102940-n', '02943799-a', '14981196-n', '02099131-s', '00021452-r', '02209716-s', '14297570-n', '02341139-s', '01558420-s', '00387850-r', '02646619-n', '01086999-v', '02235408-s', '00551895-s', '01535138-s', '12940803-n', '08271662-n']

 The only difference is that the splits collected in _map_to_one()_ also report the number of senses that go into each part of the split:

11 synsets were split between wordnet31 and 2021:
00372225-s -> [(1, '03165775-s'), (3, '00372038-s')]
06215945-n -> [(1, '06264443-n'), (1, '15450961-n')]
13337744-n -> [(1, '13447536-n'), (2, '15455343-n')]
05265220-n -> [(3, '15454555-n'), (1, '05310075-n')]
04730186-n -> [(1, '04769376-n'), (1, '15447720-n')]
08968866-n -> [(1, '15455105-n'), (4, '09051689-n')]
04883756-n -> [(2, '04924349-n'), (1, '15451438-n')]
04354832-n -> [(3, '04391434-n'), (1, '15452790-n')]
11662881-n -> [(1, '15450310-n'), (2, '15451564-n')]
01898672-n -> [(1, '15455508-n'), (2, '01914228-n')]
10577282-n -> [(3, '10668093-n'), (1, '10361894-n')]

**Comment by ekaf** [comment]
@tomaarsen, I wonder whether it could be 'a breaking change' that the latest version of this PR makes the 'splits' and 'nomap' structures deeper. 

These structures are still undocumented features, and so new that very few people are likely to be aware of them yet. They are intended to be useful to wordnet researchers who want to improve the mappings. Actually, I have also received requests to provide access to a list of 'merged' synsets, but this can probably wait for a later PR.

If this change is a problem, the solution could be to leave the 'splits' and 'nomap' as they are, and use a different name for the deeper structures.

**Comment by ekaf** [comment]
I think that the latest commit completes this PR. In addition to mappings and splits, it also allows to get merges for any pair of English Wordnets.

However, I am a little worried that some changes may be perceived as too big, so it would be useful get a new review from @tomaarsen, and also to hear from @arademaker.

```
from nltk.corpus import wordnet2021 as wn

source_wn = "wordnet31"

merges = wn.merged_synsets(source_wn)

print(f"\n\n{len(merges)} synsets were merged between {source_wn} and {wn.get_version()}:\n")

for target,sources in sorted(list(merges.items())):
    print(f"{sources} -> {target}")
```

13 synsets were merged between wordnet31 and 2021:

{'00326578-v', '00327111-v'} -> 00327791-v
{'00062066-r', '00062215-r'} -> 00520330-r
{'01481233-v', '01481639-v'} -> 01484541-v
{'01741498-v', '01622373-v'} -> 01626447-v
{'01681111-s', '01681586-s'} -> 01680459-s
{'02301687-v', '02332196-v'} -> 02339696-v
{'04415309-n', '02747082-n'} -> 02773965-n
{'09202161-n', '09201896-n'} -> 09288102-n
{'09253407-n', '09295679-n'} -> 09339730-n
{'09544292-n', '09543752-n'} -> 09632039-n
{'09550135-n', '09552135-n'} -> 09637712-n
{'10271476-n', '10577282-n'} -> 10361894-n
{'09545972-n', '11019869-n'} -> 11114298-n

**Comment by tomaarsen** [comment]
@ekaf My apologies, I've been quite busy recently. I hope to get some time for this soon, and otherwise perhaps @stevenbird will be able to handle this PR and the related issue.

**Comment by ekaf** [comment]
I presented a related paper last month at the Global Wordnet Conference 2023 in San Sebastian, and this PR is motivated by conversations with some attendees who need info about the splits and merges. The final version of the paper "Mapping Wordnets on the fly with permanent sense keys" is due at the end of this month, and will be available through the ACL anthology. Meanwhile, there is an early version here https://www.hitz.eus/gwc2023/sites/default/files/aurkezpenak/GWC2023_paper_8970.pdf

**Comment by stevenbird** [comment]
Thanks @ekaf!

**Pull request merged**
