### PR TITLE
BLUE score refactoring and more tests.

### PR DESCRIPTION
**Pull request by dimazest**
BLUE score is now stable across different python versions. Some functions are refactored to make them more readable.

More tests are added based on examples from Papineni et al.

### CODE REVIEW

**Comment by stevenbird** [comment]
Thanks @dimazest this is great!

**Comment by dimazest** [comment]
I've forgotten to mention, but I had to change the returned score in the tests. But I didn't calculate it by hand, nor got if from a paper.

**Comment by stevenbird** [comment]
This happens all the time.

**Comment by dimazest** [comment]
I mean, the returned score might be wrong :) but i'm not a MT expert.

**Pull request merged**
