### PR TITLE
K alpha

### PR DESCRIPTION
**Pull request by myproblemchild**
Rewrite K-Alpha calculation method.

The previous method gives incorrect results on the data I've tested.
The simplest one being: [('c1', 'item1', 'yes'), ('c2', 'item1', 'no'), ('c1', 'item2', 'yes'), ('c2', 'item2', 'no'), ('c3', 'item2', 'no'), ('c3', 'item3', 'yes')].
My implementation gives correct results on all the data I've tried it on.

For one, the item3 should not be taken into account since it has only 1 rating present.
But even ignoring that, the existing method gives incorrect results.

By the way, I'd be happy to add tests if you could explain how to run it in a simple command :)

### CODE REVIEW

**Comment by 53X** [comment]
@myproblemchild  can you share your data?

**Comment by myproblemchild** [comment]
Sure. I will provide 4 examples, and following that outputs from current NLTK implementation, and after than with my patch.

**1. Examples.**

simple_example is based on https://github.com/foolswood/krippendorffs_alpha/raw/master/krippendorff.pdf .
simple_example2 is the same, but the item that has only 1 rating is removed.

advanced_example is based on 
http://www.agreestat.com/research_papers/onkrippendorffalpha.pdf
advanced_example2 is the same, but the item that has only 1 rating is removed.

$ cat simple_example
coder1,dress1,YES
coder2,dress1,NO
coder3,dress1,NO
coder1,dress2,YES
coder2,dress2,NO
coder3,dress3,NO

$ cat simple_example2
coder1,dress1,YES
coder2,dress1,NO
coder3,dress1,NO
coder1,dress2,YES
coder2,dress2,NO

$ cat advanced_example
A,1,1
B,1,1
D,1,1
A,2,2
B,2,2
C,2,3
D,2,2
A,3,3
B,3,3
C,3,3
D,3,3
A,4,3
B,4,3
C,4,3
D,4,3
A,5,2
B,5,2
C,5,2
D,5,2
A,6,1
B,6,2
C,6,3
D,6,4
A,7,4
B,7,4
C,7,4
D,7,4
A,8,1
B,8,1
C,8,2
D,8,1
A,9,2
B,9,2
C,9,2
D,9,2
B,10,5
C,10,5
D,10,5
C,11,1
D,11,1
C,12,3

$ cat advanced_example2
A,1,1
B,1,1
D,1,1
A,2,2
B,2,2
C,2,3
D,2,2
A,3,3
B,3,3
C,3,3
D,3,3
A,4,3
B,4,3
C,4,3
D,4,3
A,5,2
B,5,2
C,5,2
D,5,2
A,6,1
B,6,2
C,6,3
D,6,4
A,7,4
B,7,4
C,7,4
D,7,4
A,8,1
B,8,1
C,8,2
D,8,1
A,9,2
B,9,2
C,9,2
D,9,2
B,10,5
C,10,5
D,10,5
C,11,1
D,11,1

**2. Output from current NLTK version.**
$ for f in \*\_example\*; do echo "Processing $f: "; python nltk/metrics/agreement.py -a alpha -c , -f $f; done
Processing advanced_example:
0.705329153605
Processing advanced_example2:
0.717105263158
Processing simple_example:
-0.5
Processing simple_example2:
-0.25

**3. Output from NLTK version with my patch.**
$ for f in \*\_example\*; do echo "Processing $f: "; python nltk/metrics/agreement.py -a alpha -c , -f $f; done
Processing advanced_example:
0.743421052632
Processing advanced_example2:
0.743421052632
Processing simple_example:
-0.333333333333
Processing simple_example2:
-0.333333333333

**4. Some notes.**
First, you can see that with my patch removal of items that only have 1 rating does not affect the final score, which is expected (compare with current NLTK version where this influences results).
Second, you can see that with my patch the code produces the same results as in the links that I have put at the beginning of this comment.

Please let me know if you have any thoughts on this.

**Comment by stevenbird** [comment]
@myproblemchild: thanks - I'll include these tests.

**Comment by myproblemchild** [comment]
@stevenbird Steven, thank you for reply. Could you please comment on whether this pull request have chances to be merged in? Or whether there are stylistics/functional issues that you'd like me to address. Thanks!

**Comment by stevenbird** [comment]
@myproblemchild Sorry for the delay... the only thing that still needs to happen is to include these tests in a doctest or unit test in nltk/test. I meant to do this but haven't had time. Would you like to take it on please?

**Comment by myproblemchild** [comment]
@stevenbird thanks for reply! I gave it a try, let me see whether the checks will pass. I was able to run tests successfully on my local machine at least.

**Comment by myproblemchild** [comment]
@stevenbird Friendly ping, do you have any comments?

**Comment by purificant** [comment]
Some of the code that was re-written in this PR has been reformatted in `develop` due to https://github.com/nltk/nltk/pull/2163. In order to resolve the conflict please take all changes from this PR as they should completely replace the old code in `develop`. To summarise: method `Do_alpha` is deleted, and method `alpha` is mostly replaced by this PR.

**Comment by stevenbird** [comment]
@purificant - thanks for this, and the merge instructions

**Pull request merged**
