### PR TITLE
Fix issue #2224 by correcting typo in common_contexts()

### LINKED ISSUE #2224: Minor typo in the docstring of common_contexts()
The parameter name is `words`, but the docstring uses `word`.

image

### PR DESCRIPTION
**Pull request by bharatr21**
Corrected the typo in the docstring of common_contexts() to fix #2224

### CODE REVIEW

**Comment by purificant** [comment]
CI could not install py35 and failed, I believe re-running CI should fix this.

**Review by purificant — APPROVED** [review]

**Comment by bharatr21** [comment]
@purificant How to re-run the travis CI build? Or if not, please consider merging this PR at the risk of it going stale

**Comment by purificant** [comment]
@Bharat123rox 
You can re-run CI build by pushing a new commit on your branch.

This can also be done artificially, without creating a new commit by simply changing the hash of the last commit, like this on your branch:

`git rebase -i HEAD~1`
change `pick` to `reword`, keep the same message as before or update it
`git push -f`

**Comment by bharatr21** [comment]
@purificant now that the build has passed and you have approved changes, what else remains to be done (should I do anything?)

**Comment by alvations** [comment]
Thanks @Bharat123rox @purificant!

**Pull request merged**
