### PR TITLE
TrigramCollocationFinder.from_words with window

### PR DESCRIPTION
**Pull request by helmanofer**
Added the option to create a trigram finder with windows_size

### CODE REVIEW

**Comment by jnothman** [comment]
This seems a clean solution. Is it substantially slower where `window_size=3`? Can you please provide a test for the new functionality?

**Comment by helmanofer** [comment]
The solution isn't slower for the default value of window_size=3:

```
import nltk
from nltk.collocations import *
import time

trigram_measures = nltk.collocations.TrigramAssocMeasures()
t = time.time()
finder = TrigramCollocationFinder.from_words(nltk.corpus.genesis.words('english-web.txt'))
print(finder.nbest(trigram_measures.pmi, 10))
print('original from_words function:', time.time() - t)

t = time.time()
finder = TrigramCollocationFinder.from_words_with_window(nltk.corpus.genesis.words('english-web.txt'), 3)
print(finder.nbest(trigram_measures.pmi, 10))
print('modified from_words function with default window_size:', time.time() - t)

t = time.time()
finder = TrigramCollocationFinder.from_words_with_window(nltk.corpus.genesis.words('english-web.txt'), 4)
print(finder.nbest(trigram_measures.pmi, 10))
print('modified from_words function with window_size=4:',time.time() - t)
```

```
[('rider', 'falls', 'backward'), ('sewed', 'fig', 'leaves'), ('olive', 'leaf', 'plucked'), ('yield', 'royal', 'dainties'), ('during', 'mating', 'season'), ('Their', 'hearts', 'failed'), ('Valley', ').', 'Melchizedek'), ('Salt', 'Sea', ').'), ('Sea', ').', 'Twelve'), ('doing', 'forced', 'labor')]
original from_words function: 2.059999942779541
[('rider', 'falls', 'backward'), ('sewed', 'fig', 'leaves'), ('olive', 'leaf', 'plucked'), ('yield', 'royal', 'dainties'), ('during', 'mating', 'season'), ('Their', 'hearts', 'failed'), ('Valley', ').', 'Melchizedek'), ('Salt', 'Sea', ').'), ('Sea', ').', 'Twelve'), ('doing', 'forced', 'labor')]
modified from_words function with default window_size: 2.0829999446868896
[('olive', 'leaf', 'plucked'), ('rider', 'falls', 'backward'), ('sewed', 'fig', 'leaves'), ('Salt', 'Sea', 'Twelve'), ('cutting', 'instrument', 'brass'), ('fresh', 'poplar', 'almond'), ('yield', 'royal', 'dainties'), ('during', 'mating', 'season'), ('current', 'merchants', 'standard'), ('Rephaim', 'Ashteroth', 'Karnaim')]
modified from_words function with window_size=4: 6.3470001220703125
```

**Comment by stevenbird** [comment]
Thanks @helmanofer! Would you mind adding some tests to `nltk/test/collocations.doctest` please?

**Comment by helmanofer** [comment]
Hi Steven, Joel

After running some tests regarding my commit, I came to a conclusion that my initial commit was wrong 

here is the suggested new function:

```
@classmethod
    def from_words(cls, words, window_size=3):
        """Construct a TrigramCollocationFinder for all trigrams in the given
        sequence.
        """
        if window_size < 3:
            raise ValueError("Specify window_size at least 3")

        wfd = FreqDist()
        wildfd = FreqDist()
        bfd = FreqDist()
        tfd = FreqDist()
        for window in ngrams(words, window_size, pad_right=True):
            w1 = window[0]
            for w2, w3 in _itertools.combinations(window[1:], 2):
                wfd[w1] += 1
                if w2 is None:
                    continue
                bfd[(w1, w2)] += 1
                if w3 is None:
                    continue
                wildfd[(w1, w3)] += 1
                tfd[(w1, w2, w3)] += 1
        return cls(wfd, bfd, wildfd, tfd)
```

here is the test I've made:

```
trigram_measures = nltk.collocations.TrigramAssocMeasures()
text = "I do not like green eggs and ham, I do not like them green Sam I am!"
tokens = nltk.wordpunct_tokenize(text)
finder = TrigramCollocationFinder.from_words(tokens, window_size=4)
print(finder.ngram_fd)
```

and the results:

With the initial commit:

```
FreqDist({('do', 'not', 'like'): 4, ('I', 'do', 'not'): 3, ('not', 'like', 'green'): 3, ('green', 'Sam', 'I'): 2, ('and', 'ham', ','): 2, ('Sam', 'I', 'am'): 2, ('eggs', 'and', 'ham'): 2, ('ham', ',', 'I'): 2, ('I', 'am', '!'): 2, ('green', 'eggs', 'and'): 2, ...})
```

With the new function:

```
FreqDist({('do', 'not', 'like'): 2, ('I', 'do', 'like'): 2, ('I', 'do', 'not'): 2, ('I', 'not', 'like'): 2, ('not', 'like', 'green'): 2, ('green', 'Sam', 'I'): 1, ('and', 'ham', ','): 1, ('do', 'not', 'green'): 1, ('Sam', 'I', 'am'): 1, ('like', 'green', 'and'): 1, ...})
```

Another issue that I am not sure about is Church and Hanks (1990), counts are scaled by a factor of 1/(window_size - 1) in score_ngram

Thanks and sorry for the trouble

**Comment by jnothman** [comment]
Yes, that looks more akin to the bigram case (and we've had previous issues with counting gappy bigrams). Is there a reason you've not committed this change? The diff then would be more apparent.

**Comment by stevenbird** [comment]
Thanks for the contribution @helmanofer and for vetting it @jnothman. OK for me to merge this?

**Comment by helmanofer** [comment]
I would just like to clarify an issue that I am not sure about,  "Church and Hanks (1990), counts are scaled by a factor of 1/(window_size - 1) in score_ngram" should it be added in TrigramCollocationFinder?

**Comment by jnothman** [comment]
@stevenbird, I've not finished looking through it. And I'm not sure if we would rather something generic for n > 3; and whether we want an option to only count the n-gram and unigram counts, which are sufficient for some association measures.

**Comment by jnothman** [comment]
Sorry, confused this with the more recent PR.

**Comment by jnothman** [comment]
> "Church and Hanks (1990), counts are scaled by a factor of 1/(window_size - 1) in score_ngram" should it be added in TrigramCollocationFinder?

Probably, but it needs some clarification first. I think the factor should still be 1 for `window_size==3==n`, and I expect we need to adjust the other counts as well. Church and Hanks' normalisation is an issue only brought up here by @rmalouf at #403.

**Comment by stevenbird** [comment]
@helmanofer do you have any further comments here?

**Comment by helmanofer** [comment]
no comment

**Comment by stevenbird** [comment]
@jnothman I'm not sure what to make of your request for clarification now. It seems like we do not have agreement about the scaling factor to use.

**Comment by stevenbird** [comment]
@helmanofer I'm going to close this for now, since I don't now how to move it forward, sorry.

**Pull request closed without merging**
