### PR TITLE
Update CITATION.cff metadata

### PR DESCRIPTION
**Pull request by cgobat**
This PR adds the publication month (June), [book website](https://www.nltk.org/book/) URL, ISBN, and [publisher website](https://www.oreilly.com/) for the *Natural Language Processing with Python* book in the CITATION.cff file. This additional information (especially the ISBN) will help enable proper/complete attribution.

### CODE REVIEW

**Comment by cgobat** [comment]
Bumping this @tomaarsen

**Comment by tomaarsen** [comment]
I don't think it's my place to approve the changing of the citation without permission from @stevenbird, as it's not my name on the citation.

**Comment by cgobat** [comment]
Fair enough. Wasn't sure who would be the right person to tag

**Comment by tomaarsen** [comment]
No worries!

**Comment by stevenbird** [comment]
Thanks @cgobat

**Pull request merged**
