### PR TITLE
Fix bug can't find gensim_sample

### PR DESCRIPTION
**Pull request by longdt219**
Hi @stevenbird 
This is to fix bug #1001

### CODE REVIEW

**Comment by stevenbird** [comment]
Thanks @longdt219

**Comment by sahutd** [comment]
Looks like this commit introduced the following regression which prevents nltk from being imported(confirmed using bisection). Attached the error:

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import nltk
  File "/home/saimadhav/development/nltk/nltk/__init__.py", line 131, in <module>
    from nltk.inference import *
  File "/home/saimadhav/development/nltk/nltk/inference/__init__.py", line 19, in <module>
    from nltk.inference.discourse import (ReadingCommand, CfgReadingCommand,
  File "/home/saimadhav/development/nltk/nltk/inference/discourse.py", line 56, in <module>
    from nltk.sem.glue import DrtGlue
  File "/home/saimadhav/development/nltk/nltk/sem/glue.py", line 15, in <module>
    from nltk.corpus import brown
  File "/home/saimadhav/development/nltk/nltk/corpus/__init__.py", line 256, in <module>
    word2vec_sample = str(find('models/word2vec_sample/pruned.word2vec.bin'))
  File "/home/saimadhav/development/nltk/nltk/data.py", line 624, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource 'models/word2vec_sample/pruned.word2vec.bin' not found.
  Please use the NLTK Downloader to obtain the resource:  >>>
  nltk.download()
  Searched in:
    - '/home/saimadhav/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

Feel that the added code should be in a try-except block. If I am correct, it is not critical to nltk.

Also the suggestion to use nltk.download() is redundant, because, it is impossible to use nltk.download() for reason above.

**Comment by stevenbird** [comment]
I think we have the same problem showing up on our CI server: https://nltk.ci.cloudbees.com/job/nltk/lastCompletedBuild/TOXENV=py32-jenkins,jdk=jdk8latestOnlineInstall/testReport/nose.failure/Failure/runTest/

**Comment by longdt219** [comment]
I created a PR #1011

**Pull request merged**
