### PR TITLE
Two fixes in NaiveBayesClassifier

### PR DESCRIPTION
**Pull request by apresta**
- Fixed a regression in prob_classify(): we cannot iterate on a dictionary and change it at the same time. Iterate on a copy of the keys instead.
- In train(), switched from defaultdict(FreqDist) to ConditionalFreqDist()

While we're there, can someone briefly explain me the status of this GitHub repo? Is it the official development repository now?
I ask because of the regression I've found (it's fixed in the SVN repo).
Also, the nltk.compat seems to have gone. Was this intended or is it another regression?

### CODE REVIEW

**Comment by xim** [comment]
Yes, Github is the official source repository for NLTK now. The regression was a minor error done during a refactor. Thanks for the fix! ^_^

The commit that removed compat.py was deliberate:

commit 8617fa77205a58ff50a89fa9638854024d62b56a
Author: Steven Bird stevenbird1@gmail.com
Date:   Wed Nov 2 04:32:30 2011 +1100

```
removed support for Python 2.4
```

**Comment by stevenbird** [comment]
Yes, that was deliberate.  What's the reason for this change please: "In train(), switched from defaultdict(FreqDist) to ConditionalFreqDist()"?

**Comment by apresta** [comment]
The only reason is consistency. I noticed there was a ConditionalFreqDist class that is essentially a defaultdict(FreqDist), so why not take advantage of it? This, unless I misinterpreted the original intent.

**Comment by xim** [comment]
ConditionalFreqDist has some extra functionality that isn't used here, so it would be preferable to make it clear we're not using it - e.g. by making a defaultdict(FreqDist). Will undo that part =)

**Comment by apresta** [comment]
Alright, makes sense to me. Sorry for that!

**Comment by stevenbird** [comment]
Please submit a new pull request to undo this change, thanks.

**Comment by apresta** [comment]
Morten already did that: https://github.com/nltk/nltk/commit/ddb25430b99a4742932de375dc7d627576a0e8c1

**Comment by anirudhs2005** [comment]
I am doing a project on spam classification. The first algorithm I ran was Naive Bayes Algorithm . The algorithm ran perfectly on Feb 10 and a few days after that. I haven't done any updates to the code after that. I have the snap shots of the output too. 
Now, suddenly the classifier has gone awry and it pops up such errors. I thought it was a problem with Naive Bayes and I ran MaxEnt; even then the result is the same. 
Could you please help me out ? I think many of them have faced this problem. What could be the solution to it?

> > > import spambot as s
> > > cl=s.spamclassifier()
> > > cl.classifier()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "spambot.py", line 58, in classifier
> > >     classifier= NaiveBayesClassifier.train(training_set)
> > >   File "/usr/local/lib/python2.7/dist-packages/nltk/classify/naivebayes.py", line 215, in train
> > >     label_probdist = estimator(label_freqdist)
> > >   File "/usr/local/lib/python2.7/dist-packages/nltk/probability.py", line 916, in **init**
> > >     LidstoneProbDist.**init**(self, freqdist, 0.5, bins)
> > >   File "/usr/local/lib/python2.7/dist-packages/nltk/probability.py", line 802, in **init**
> > >     'must have at least one bin.')
> > > ValueError: A ELE probability distribution must have at least one bin.

**Comment by stevenbird** [comment]
Please submit a new issue, with a small code sample that allows us to replicate the problem, thanks.

**Pull request merged**
