### PR TITLE
Raise warning for infinite recursion

### PR DESCRIPTION
**Pull request by alvations**
Patching #7
Raises humanly-understandable warning for infinite recursion.

### CODE REVIEW

**Comment by nschneid** [comment]
Is there a risk that this patch would lead to uninformative output for RuntimeErrors that _aren't_ due to infinite recursion? Should `raise RuntimeError` be simply `raise` in the event of a non-recursion error?

**Comment by alvations** [comment]
@nschneid The error would still be raised as in L48 regardless. For now, it's raising the error but just without the note on the inifite grammer. And if the maximum recursion occurs, it should be due to infinite recursion, as noticed the error message `"maximum recursion depth exceeded"`. 

E.g.

``` python
>>> from nltk.parse import generate
>>> generate.demo_grammar = """
... A -> A B | 'a'
... B -> 'b'
... """
>>> 
>>> generate.demo()
Generating the first 23 sentences for demo grammar:

A -> A B | 'a'
B -> 'b'

The grammar has rule(s) that yield infinite recursion!!

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/parse/generate.py", line 78, in demo
    for n, sent in enumerate(generate(grammar, n=N), 1):
  File "nltk/parse/generate.py", line 48, in _generate_all
    raise RuntimeError
RuntimeError
```

Without the note, it would be:

``` python

>>> from nltk.parse import generate
>>> generate.demo_grammar = """
... A -> A B | 'a'
... B -> 'b'
... """
>>> 
>>> generate.demo()
Generating the first 23 sentences for demo grammar:

A -> A B | 'a'
B -> 'b'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/parse/generate.py", line 72, in demo
    for n, sent in enumerate(generate(grammar, n=N), 1):
  File "nltk/parse/generate.py", line 41, in _generate_all
    for frag1 in _generate_one(grammar, items[0], depth):
  File "nltk/parse/generate.py", line 51, in _generate_one
    for frag in _generate_all(grammar, prod.rhs(), depth-1):
  File "nltk/parse/generate.py", line 41, in _generate_all
    for frag1 in _generate_one(grammar, items[0], depth):
  File "nltk/parse/generate.py", line 51, in _generate_one
    for frag in _generate_all(grammar, prod.rhs(), depth-1):
... (repeating errors)
  File "nltk/parse/generate.py", line 50, in _generate_one
    for prod in grammar.productions(lhs=item):
  File "nltk/grammar.py", line 558, in productions
    return self._lhs_index.get(lhs, [])
RuntimeError: maximum recursion depth exceeded
```

Maybe instead of `raise RuntimeError`, we could do:

``` python
import traceback

def _generate_all(grammar, items, depth):
    if items:
        try:
            for frag1 in _generate_one(grammar, items[0], depth):
                for frag2 in _generate_all(grammar, items[1:], depth):
                    yield frag1 + frag2
        except RuntimeError as _error:
            if _error.message == "maximum recursion depth exceeded":
                print("The grammar has rule(s) that yield infinite recursion!!\n", file=sys.stderr)
            traceback.print_exc()
            raise RuntimeError("maximum recursion depth exceeded")

    else:
        yield []
```

which should output:

``` python

>>> from nltk.parse import generate
>>> generate.demo_grammar = """
... A -> A B | 'a'
... B -> 'b'
... """
>>> 
>>> generate.demo()
Generating the first 23 sentences for demo grammar:

A -> A B | 'a'
B -> 'b'

The grammar has rule(s) that yield infinite recursion!!

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/parse/generate.py", line 72, in demo
    for n, sent in enumerate(generate(grammar, n=N), 1):
  File "nltk/parse/generate.py", line 41, in _generate_all
    for frag1 in _generate_one(grammar, items[0], depth):
  File "nltk/parse/generate.py", line 51, in _generate_one
    for frag in _generate_all(grammar, prod.rhs(), depth-1):
  File "nltk/parse/generate.py", line 41, in _generate_all
    for frag1 in _generate_one(grammar, items[0], depth):
  File "nltk/parse/generate.py", line 51, in _generate_one
    for frag in _generate_all(grammar, prod.rhs(), depth-1):
... (repeating errors)
  File "nltk/parse/generate.py", line 50, in _generate_one
    for prod in grammar.productions(lhs=item):
  File "nltk/grammar.py", line 558, in productions
    return self._lhs_index.get(lhs, [])
RuntimeError: maximum recursion depth exceeded

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/parse/generate.py", line 78, in demo
    for n, sent in enumerate(generate(grammar, n=N), 1):
  File "nltk/parse/generate.py", line 48, in _generate_all
    raise RuntimeError
RuntimeError: maximum recursion depth exceeded
```

Or we could do:

``` python
import traceback

def _generate_all(grammar, items, depth):
    if items:
        try:
            for frag1 in _generate_one(grammar, items[0], depth):
                for frag2 in _generate_all(grammar, items[1:], depth):
                    yield frag1 + frag2
        except RuntimeError as _error:
            if _error.message == "maximum recursion depth exceeded":
                print("The grammar has rule(s) that yield infinite recursion!!\n", file=sys.stderr)
            traceback.print_stack()

    else:
        yield []
```

which should automatically raise the exception and output:

``` python

>>> from nltk.parse import generate
>>> generate.demo_grammar = """
... A -> A B | 'a'
... B -> 'b'
... """
>>> 
>>> generate.demo()
Generating the first 23 sentences for demo grammar:

A -> A B | 'a'
B -> 'b'

The grammar has rule(s) that yield infinite recursion!!

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/parse/generate.py", line 72, in demo
    for n, sent in enumerate(generate(grammar, n=N), 1):
  File "nltk/parse/generate.py", line 41, in _generate_all
    for frag1 in _generate_one(grammar, items[0], depth):
  File "nltk/parse/generate.py", line 51, in _generate_one
    for frag in _generate_all(grammar, prod.rhs(), depth-1):
  File "nltk/parse/generate.py", line 41, in _generate_all
    for frag1 in _generate_one(grammar, items[0], depth):
  File "nltk/parse/generate.py", line 51, in _generate_one
    for frag in _generate_all(grammar, prod.rhs(), depth-1):
... (repeating errors)
  File "nltk/parse/generate.py", line 50, in _generate_one
    for prod in grammar.productions(lhs=item):
  File "nltk/grammar.py", line 558, in productions
    return self._lhs_index.get(lhs, [])
RuntimeError: maximum recursion depth exceeded

```

**Comment by nschneid** [comment]
That's fine in the case of infinite recursion; I'm worried about other kinds of `RuntimeError`s that might arise. The current solution would alter the traceback and remove the informative error message. How about:

``` py
except RuntimeError as _error:
    if _error.message == "maximum recursion depth exceeded":
        # more helpful error message (and don't distract the user by showing the recursion stack)
        raise StandardError('The grammar has rule(s) that yield infinite recursion!!')
    else: # don't handle non-recursion errors
        raise
```

**Comment by alvations** [comment]
@nschneid let me test out all possibilities and output them, then we can choose depending on how informative they are. I'll do that later today, got to go to work soon =)

**Comment by alvations** [comment]
@nschneid If we're raising error for the recursion, I think raising `RuntimeError` to be consistent with the catch might be better than `StandardError`. 

**Proposal 1: With `StandardError`**

``` python
def _generate_all(grammar, items, depth):
    if items:
        try:
            for frag1 in _generate_one(grammar, items[0], depth):
                for frag2 in _generate_all(grammar, items[1:], depth):
                    yield frag1 + frag2
        except RuntimeError as _error:
            if _error.message == "maximum recursion depth exceeded":
                # Helpful error message while still showing the recursion stack.
                raise StandardError("The grammar has rule(s) that yield infinite recursion!!")
            else:
                raise
    else:
        yield []
```

[out]:

``` python
>>> from nltk.parse import generate
>>> generate.demo_grammar = """
... A -> A B | 'a'
... B -> 'b'
... """
>>> generate.demo()
Generating the first 23 sentences for demo grammar:

A -> A B | 'a'
B -> 'b'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/parse/generate.py", line 79, in demo
    for n, sent in enumerate(generate(grammar, n=N), 1):
  File "nltk/parse/generate.py", line 42, in _generate_all
    for frag1 in _generate_one(grammar, items[0], depth):
  File "nltk/parse/generate.py", line 58, in _generate_one
    for frag in _generate_all(grammar, prod.rhs(), depth-1):
  File "nltk/parse/generate.py", line 42, in _generate_all
    for frag1 in _generate_one(grammar, items[0], depth):
  File "nltk/parse/generate.py", line 58, in _generate_one
... (repeating errors)
  File "nltk/parse/generate.py", line 48, in _generate_all
    raise StandardError("The grammar has rule(s) that yield infinite recursion!!")
StandardError: The grammar has rule(s) that yield infinite recursion!!
```

---

**Proposal 2: With `RuntimeError`**

``` python
def _generate_all(grammar, items, depth):
    if items:
        try:
            for frag1 in _generate_one(grammar, items[0], depth):
                for frag2 in _generate_all(grammar, items[1:], depth):
                    yield frag1 + frag2
        except RuntimeError as _error:
            if _error.message == "maximum recursion depth exceeded":
                # Helpful error message while still showing the recursion stack.
                raise RuntimeError("The grammar has rule(s) that yield infinite recursion!!")
            else:
                raise
    else:
        yield []
```

``` python
>>> from nltk.parse import generate
>>> generate.demo_grammar = """
... A -> A B | 'a'
... B -> 'b'
... """
>>> generate.demo()
Generating the first 23 sentences for demo grammar:

A -> A B | 'a'
B -> 'b'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/parse/generate.py", line 79, in demo
    for n, sent in enumerate(generate(grammar, n=N), 1):
  File "nltk/parse/generate.py", line 42, in _generate_all
    for frag1 in _generate_one(grammar, items[0], depth):
  File "nltk/parse/generate.py", line 58, in _generate_one
    for frag in _generate_all(grammar, prod.rhs(), depth-1):
  File "nltk/parse/generate.py", line 42, in _generate_all
    for frag1 in _generate_one(grammar, items[0], depth):
  File "nltk/parse/generate.py", line 58, in _generate_one
... (repeating errors)
  File "nltk/parse/generate.py", line 48, in _generate_all
    raise RuntimeError("The grammar has rule(s) that yield infinite recursion!!")
RuntimeError: The grammar has rule(s) that yield infinite recursion!!
```

**Comment by stevenbird** [comment]
Thanks for the feedback @nschneid

**Pull request merged**
