### PR TITLE
Pickle-free maxent chunkers

### PR DESCRIPTION
**Pull request by ekaf**
Tab files are not exposed to the "sleepy" vulnerabilities reported with Python pickles.

This PR adds a loader for the [corresponding data package](https://github.com/nltk/nltk_data/pull/217).

```
from nltk.chunk import ne_chunker
from nltk.corpus import treebank
from pprint import pprint

sent = treebank.tagged_sents()[2]
```
The chunker is initialized with parameters saved as tab-files. 
Load the "binary" model:

```
chunker = ne_chunker("binary")
pprint(chunker.parse(sent))
```
> Tree('S', [Tree('NE', [('Rudolph', 'NNP'), ('Agnew', 'NNP')]), (',', ','), ('55', 'CD'), ('years', 'NNS'), ('old', 'JJ'), ('and', 'CC'), ('former', 'JJ'), ('chairman', 'NN'), ('of', 'IN'), Tree('NE', [('Consolidated', 'NNP'), ('Gold', 'NNP'), ('Fields', 'NNP'), ('PLC', 'NNP')]), (',', ','), ('was', 'VBD'), ('named', 'VBN'), ('*-1', '-NONE-'), ('a', 'DT'), ('nonexecutive', 'JJ'), ('director', 'NN'), ('of', 'IN'), ('this', 'DT'), Tree('NE', [('British', 'JJ')]), ('industrial', 'JJ'), ('conglomerate', 'NN'), ('.', '.')])

Load the recommended "multiclass" model:
```
chunker = ne_chunker()
pprint(chunker.parse(sent))
```

> Tree('S', [Tree('PERSON', [('Rudolph', 'NNP')]), Tree('GPE', [('Agnew', 'NNP')]), (',', ','), ('55', 'CD'), ('years', 'NNS'), ('old', 'JJ'), ('and', 'CC'), ('former', 'JJ'), ('chairman', 'NN'), ('of', 'IN'), Tree('ORGANIZATION', [('Consolidated', 'NNP'), ('Gold', 'NNP'), ('Fields', 'NNP')]), ('PLC', 'NNP'), (',', ','), ('was', 'VBD'), ('named', 'VBN'), ('*-1', '-NONE-'), ('a', 'DT'), ('nonexecutive', 'JJ'), ('director', 'NN'), ('of', 'IN'), ('this', 'DT'), Tree('GPE', [('British', 'JJ')]), ('industrial', 'JJ'), ('conglomerate', 'NN'), ('.', '.')])

### CODE REVIEW

**Comment by ekaf** [comment]
Now, this PR also includes a handler for the _maxent_treebank_pos_tagger_ data, and thus completes the removal of all the unsafe pickles. After merging this and #3283, there will be no more need for the  _compat.py_ library.

```
from nltk.corpus import treebank
from nltk.classify.maxent import maxent_pos_tagger

print(maxent_pos_tagger().tag(treebank.sents()[0]))
```

[('Pierre', 'NNP'), ('Vinken', 'NNP'), (',', ','), ('61', 'CD'), ('years', 'NNS'), ('old', 'JJ'), (',', ','), ('will', 'MD'), ('join', 'VB'), ('the', 'DT'), ('board', 'NN'), ('as', 'IN'), ('a', 'DT'), ('nonexecutive', 'JJ'), ('director', 'NN'), ('Nov.', 'NNP'), ('29', 'CD'), ('.', '.')]

**Comment by ekaf** [comment]
The CI failures don't seem related to this PR:

> 2024-07-22T08:46:53.1970607Z E           RuntimeError: Senna command failed! Details: b'FATAL ERROR: unable to open file </home/runner/third/senna/data/ner.loc.dat>\n'

**Comment by stevenbird** [comment]
Let's try :)

**Comment by stevenbird** [comment]
Thanks @ekaf!

**Comment by ekaf** [comment]
Attention: This PR was merged without the needed [nltk_data packages: PR 217](https://github.com/nltk/nltk_data/pull/217) and  [PR 218](https://github.com/nltk/nltk_data/pull/218).

The data packages are a prerequisite for this PR, which cannot be expected to work without the corresponding data.

**Pull request merged**
