### PR TITLE
Fixed some encoding bugs in wordnet_app.py, cf https://github.com/nltk/nltk/issues/535

### PR DESCRIPTION
**Pull request by stevenxxiu**
Fixed some encoding bugs in wordnet_app.py, cf https://github.com/nltk/nltk/issues/535

### CODE REVIEW

**Comment by stevenbird** [comment]
@jskda are you testing with both Python 2.6 and 3.2?

**Comment by stevenxxiu** [comment]
@stevenbird: I've tested with python 2.7 and 3.2, I'll test with python 2.6 today.

**Comment by stevenxxiu** [comment]
@stevenbird: I've now tested this with python 2.6 on linux and it works for me.

**Comment by stevenbird** [comment]
Thanks.

**Pull request merged**
