### PR TITLE
Remove duplicate productions in CNF for CFGs

### PR DESCRIPTION
**Pull request by Daksh**
Related Issue #1884 

I was not sure if I should add my name (in AUTHORS.md) for such a small change. Did not know what is the protocol followed in nltk community, if maintainers believe it is a mistake, please accept my apologies and let me know, I will amend the commit :)

### CODE REVIEW

**Comment by stevenbird** [comment]
[CI: retest]

**Comment by stevenbird** [comment]
[CI: retest]

**Comment by stevenbird** [comment]
@Daksh my apologies for the long delay.

**Comment by Daksh** [comment]
@stevenbird Thanks for merging it :D no worries about the delay

**Pull request merged**
