### PR TITLE
Remove `__new__` from Tree classes

### PR DESCRIPTION
**Pull request by heatherleaf**
I have removed `__new__` from the Tree class and its subclasses.  This makes the code much more readable, and slightly shorter, than before.

I also added some regression tests for immutable trees, and all tests (new and old) pass

### CODE REVIEW

**Comment by stevenbird** [comment]
Thanks.  I'm not sure why **new** was considered necessary.  It would be helpful to check that the parser and chunker tests (that depend on trees) also still pass.

**Comment by stevenbird** [comment]
You should be identified as a contributor to tree.py

**Comment by alexrudnick** [comment]
Ah, great! This fixes issue 130 as well. Thank you, Peter!

**Comment by heatherleaf** [comment]
Alex: I didn't know that, cool! Btw, I think you get an automatic link to the issue if you write #130. And it is closed automatically if you write fixes #130 or closes #130. 

(But perhaps that only works in commits, see the section "Commits+Issues" here:
https://github.com/blog/831-issues-2-0-the-next-generation
)

**Comment by heatherleaf** [comment]
(At least) the following doctests pass: tree, treetransforms, parse, chunk, featstruct, featgram

**Comment by stevenbird** [comment]
Excellent, thanks.

**Pull request merged**
