### PR TITLE
Custom tab file support

### PR DESCRIPTION
**Pull request by ExplodingCabbage**
There are *(edit: no longer)* two commits here, which are best reviewed independently.

[The first](https://github.com/nltk/nltk/commit/c95624a1851a580d32ba70bc1ce9de394250baa8) <strike>fixes a slew of issues that flake8 complained about when I opened wordnet.py. Besides the redundant import, I believe that all the changes are either outright, objective PEP8 violations or at least *arguably* PEP8 violations (some of the stuff in PEP8 is a little woolly and not all of pycodestyle's linting rules 100% match up with the wording of PEP8) and that as such fixing these is consistent with [the contributing guidelines](https://github.com/nltk/nltk/blob/develop/CONTRIBUTING.md). Regardless, it made my editor not throw so many errors in my face, which made the next commit easier to write. :)</strike> is already merged via #1633.

[The second](https://github.com/nltk/nltk/pull/1621/commits/16c18360868280d0f2392d66fc49c7b2c6a5648a) provides a method for telling `nltk.corpus.wordnet` to read a custom tab file and expose its data, resolving https://github.com/nltk/nltk/issues/1620

I have not written any tests for the new functionality, nor have I run any existing tests, but I have tested this briefly at my shell (in both Python 3.5 and Python 2.7), as shown below:

```
>>> import nltk
>>> nltk.corpus.wordnet.use_tab_file_for_language(open('/home/krzana/Downloads/data/wikt/wn-wikt-deu.tab'), 'deu')
>>> nltk.corpus.wordnet.synsets('monkey')[0].lemmas(lang='deu')
[Lemma('monkey.n.01.Affe')]
>>> nltk.corpus.wordnet.synsets('monkey')[0].lemmas(lang='fra')
[Lemma('monkey.n.01.singe')]
```

### CODE REVIEW

**Comment by stevenbird** [comment]
@ExplodingCabbage – it's hard to process these two commits at the same time. The first is important housekeeping, and the second is a significant enhancement that deserves some discussion first, or at least, the opportunity for discussion. Could I trouble you to submit this as two PRs? The first I'll merge right away, and the second I'll write to nltk-dev to invite comment first (or you could write). Thanks very much.

**Comment by ExplodingCabbage** [comment]
> Could I trouble you to submit this as two PRs?

Done. New PR at https://github.com/nltk/nltk/pull/1633

**Comment by ExplodingCabbage** [comment]
> the second I'll write to nltk-dev to invite comment first (or you could write)

I'm not familiar with nltk-dev, so if you could do this, I'd appreciate it.

**Comment by stevenbird** [comment]
Thanks @ExplodingCabbage – I'm happy to post to nltk-dev about the PR for extending the functionality of wordnet.

**Comment by ExplodingCabbage** [comment]
Thanks.

I've updated the first post here and have also swapped to target branch away from and back to `develop` to trigger GitHub to update the overall diff and commit history here to reflect the fact that  c95624a is now merged. (The merge itself didn't trigger such an update, which is a long-standing GitHub bug.)

**Comment by stevenbird** [comment]
I [posted](https://groups.google.com/forum/#!topic/nltk-dev/RJgxsbDlq1s) to nltk-dev last week. Will leave it a few more days before going ahead.

**Comment by alvations** [comment]
@fcbond any suggestions?

**Comment by jnothman** [comment]
Sorry for not coming to this conversation when invited months ago.

Currently there are two things strange to me about this:
* one is the requirement that a 3-letter language code be used, rather than allowing the user to trial arbitrary variations on a lexicon (why not?)
* the other is that the data is loaded immediately on registration. Should we instead have a `register_language` function, and the data be loaded dynamically as for other languages? This allows the registration to be performed as a preamble, even if it lands up not being used...

**Comment by ExplodingCabbage** [comment]
> the requirement that a 3-letter language code be used, rather than allowing the user to trial arbitrary variations on a lexicon (why not?)

Users who are willing to be slow can just swap out tab files between calls to whatever other functions they're using, and users who are willing to be hacky can put in a made-up language code if they want to use different lemma sets for the same language side by side. I guess in principle we might want to support that flow through a fast, non-hacky means, but that would mean doing one of these two things:

- Changing all the pre-existing functions in the module that take a `lang` argument to *instead* take some other sort of identifier. This would be a significant backwards-incompatible change (since users of the library might be calling those methods use keyword arguments).
- Changing all those functions to take an *additional* argument called `variant` or something like that, defaulting to `None`.

(Both approaches would need documentation explaining the meaning and intended usage of this new argument.)

The first option seems like a bad idea - we'd be making the API for the most common use case more confusing that it needs to be, and breaking backwards compatibility at the same time, all avoidably. The second approach I have no objection to, but it's a whole additional feature on top of what I've done here that I've personally got no interest in building.

> the other is that the data is loaded immediately on registration. Should we instead have a `register_language` function, and the data be loaded dynamically as for other languages? This allows the registration to be performed as a preamble, even if it lands up not being used...

I also wouldn't object to this. It's not obviously the right approach, though - loading a new tab file takes a small fraction of a second on even a modest modern machine, and making the loading lazy means deferring detecting any errors in the tab file until usage time, meaning a user of the library will see an exception when they call some non-loading-related method like `wn.lemmas()` rather than at the time of loading their tab file. There's a trade-off between a tiny performance consideration and a similarly-tiny ease-of-debugging consideration, both of which can be easily worked around by a user of the library. I have no real preference one way or the other.

**Pull request merged**
