### PR TITLE
Fixing Wordnet demo()

### PR DESCRIPTION
**Pull request by campionfellin**
This PR is to fix Issue #1789 regarding the wordnet demo. I fixed the regex and added a check depending on if the number in the middle is 2 digits or 1.

### CODE REVIEW

**Comment by alvations** [comment]
@campionfellin Thank you for the fix! Sorry for getting back this late.

I have moved the `demo()` code to unittest  so that we can automate the testing for the fix you've added.

The fix looks good to merge once it pass the automated test.

**Review by alvations — CHANGES_REQUESTED** [review]
Moved the `demo()` code to `nltk.test.unit.test_wordnet.py`

**Comment by campionfellin** [comment]
Awesome, is there anything I should do in my end? @alvations

**Comment by alvations** [comment]
Whoops I forgot to check back on whether the [automated test passed](https://nltk.ci.cloudbees.com/job/pull_request_tests/394/TOXENV=py35-jenkins,jdk=jdk8latestOnlineInstall/testReport/nltk.test.unit.test_wordnet/WordnNetDemo/). 

Great, it passed! @campionfellin Thank you again for the contribution! 

One step towards #1724

That should be all for this PR. It's good to merge now =)

**Review by alvations — APPROVED** [review]

**Comment by stevenbird** [comment]
Thanks @campionfellin and @alvations

**Pull request merged**
