### PR TITLE
tnt tagger probability multiplication change to log addition

### PR DESCRIPTION
**Pull request by isnowfy**
tnt tagger probability multiplication change to log addition to get more precision

### CODE REVIEW

**Comment by kmike** [comment]
I think this is a change in good direction, but it will require some work to get merged. E.g. variables with log probability shouldn't be named "prob" ("logprob" is better); docstrings should be also updated, e.g. this is no longer correct:

```
        :param current_states : List of possible tag combinations for
                                the sentence so far, and the probability
                                associated with each tag combination

```

**Comment by isnowfy** [comment]
@kmike Thanks for your advices and I will change it

**Comment by kmike** [comment]
Thanks! One more point: in other NLTK parts (e.g. `nltk.probability.ProbDistI.logprob(sample)`) base 2 logarithm is used instead of natural logarithm; I think it is better to be consistent here.

**Comment by isnowfy** [comment]
@kmike Thanks for your reminder, I have changed the variable, docstrings and used base 2 log instead of natural log.

**Comment by kmike** [comment]
Thanks!

**Pull request merged**
