### PR TITLE
Add abstract base class syntax to tokenize/api.py

### PR DESCRIPTION
**Pull request by mrecachinas**
As per #1130.

### CODE REVIEW

**Comment by kmike** [comment]
This is Python 2 - only syntax for abc, in Python 3 it does nothing. Check six.with_metaclass or six.add_metaclass (https://pythonhosted.org/six/#six.with_metaclass)

**Comment by mrecachinas** [comment]
@kmike Ah good catch! Fixing this...

**Comment by stevenbird** [comment]
Thanks @mrecachinas, @kmike

**Comment by mrecachinas** [comment]
@stevenbird Ready for merge or should I add any other changes?

**Comment by stevenbird** [comment]
Thanks @mrecachinas. Sorry for the delay. Looks like we have a model that could be applied across the toolkit now.

**Pull request merged**
