### PR TITLE
max phrase length added

### PR DESCRIPTION
**Pull request by barancik**
Added maximal length of extracted phrases, one redundant variable deleted.

### CODE REVIEW

**Comment by alvations** [comment]
@barancik thanks for the improvement.

@stevenbird, @barancik has made one of the suggested improvement to the NLTK code as listed on https://github.com/alvations/mt4nltk. 

The +1 , -1 indices in the `phrase_extraction` is a little confusing but that was the attempt to implement the Koehn's algorithm verbatim. Possibly the next improvement is the remove the +1 -1 indices in the code and make it more natural to read.

Should we make the changes for the indices before merging? Or merge the max phrase length added from this PR and make another PR for the indices changing?

**Comment by alvations** [comment]
@stevenbird , the default max_phrase_length 7 is because it's Moses default. But after continuing work on the phrase extraction. I realize setting the default to -1 to extract all phrases would be more appropriate.

Suggesting change from (@barancik  PR):

```
def phrase_extraction(srctext, trgtext, alignment, max_phrase_length=7):
    # ... 
        # Index e_end from e_start to len(e) - 1 or the length of maximum phrase
        max_idx = min(srclen, e_start + max_phrase_length)
```

to:

```
def phrase_extraction(srctext, trgtext, alignment, max_phrase_length=-1):
    # ... 
        if max_phrase_length is -1: # Extracts phrases of all length.
            max_idx = max_phrase_length = srclen
        else:
            # Index e_end from e_start to len(e) - 1 or the length of maximum phrase
            max_idx = min(srclen, e_start + max_phrase_length)
```

When emulating Moses, users should set it to 7. We'll add that as a note in the docstring.

I'm adding more features to the phrase extraction so that we can get phrase probabilities and lexicalized weights and reordering from the internal alignments  The max_phrase_length is necessary to reduce vocab size `|V|` so that the smoothing don't get to negligible. 

**Should the default `max_phrase_length` be set to -1 or 0?**

**Comment by stevenbird** [comment]
@alvations, note that we now presume at least Python 2.7, so `xrange` is fine.

**Comment by stevenbird** [comment]
Thanks @barancik. I'm going to merge this, and change back to using xrange.

**Comment by alvations** [comment]
@stevenbird , thanks for the note and the merge!

**Pull request merged**
