### PR TITLE
Superficial Pylint cleanup

### PR DESCRIPTION
**Pull request by alvations**
Following #2098, here's some easy cleanups. Not much but slowly, we clean. 

From pylint:

```
Your code has been rated at 6.23/10 (previous run: 6.08/10, +0.02)
```

Full `pylintoutput` file on https://gist.github.com/alvations/59306f7e0b0336a8300a793e25f1dd13

Quick summary of leftover cleanups:

```
nltk/nltk/test$ python3 -c "from collections import Counter; import re; from pprint import pprint; pprint(Counter(re.findall(r'.*\.py\:\d+\: \[([A-Za-z0-9]+\([A-Za-z0-9-]+\))\,', open('pylintoutput').read())))"
Counter({'C0103(invalid-name)': 3608,
         'W0614(unused-wildcard-import)': 1785,
         'C0326(bad-whitespace)': 1752,
         'C0111(missing-docstring)': 1606,
         'C0330(bad-continuation)': 1548,
         'C0321(multiple-statements)': 982,
         'C0301(line-too-long)': 759,
         'W0212(protected-access)': 418,
         'R1705(no-else-return)': 416,
         'W0613(unused-argument)': 363,
         'R0201(no-self-use)': 259,
         'W0612(unused-variable)': 247,
         'W1401(anomalous-backslash-in-string)': 232,
         'R0205(useless-object-inheritance)': 192,
         'R0913(too-many-arguments)': 188,
         'E0611(no-name-in-module)': 183,
         'W0221(arguments-differ)': 165,
         'C1801(len-as-condition)': 154,
         'W0201(attribute-defined-outside-init)': 152,
         'R0914(too-many-locals)': 142,
         'W0401(wildcard-import)': 141,
         'W0621(redefined-outer-name)': 140,
         'R0401(cyclic-import)': 138,
         'W0611(unused-import)': 134,
         'E1101(no-member)': 126,
         'R0801(duplicate-code)': 126,
         'W0622(redefined-builtin)': 117,
         'W0223(abstract-method)': 112,
         'R0912(too-many-branches)': 90,
         'R1710(inconsistent-return-statements)': 87,
         'C0325(superfluous-parens)': 84,
         'R0903(too-few-public-methods)': 83,
         'R0902(too-many-instance-attributes)': 59,
         'C0413(wrong-import-position)': 53,
         'C0200(consider-using-enumerate)': 47,
         'R1702(too-many-nested-blocks)': 46,
         'W0102(dangerous-default-value)': 46,
         'W0511(fixme)': 43,
         'R0915(too-many-statements)': 43,
         'W0231(super-init-not-called)': 38,
         'W0702(bare-except)': 37,
         'C0121(singleton-comparison)': 37,
         'R0911(too-many-return-statements)': 28,
         'W0105(pointless-string-statement)': 26,
         'E0202(method-hidden)': 25,
         'R1714(consider-using-in)': 25,
         'W0404(reimported)': 23,
         'W0703(broad-except)': 23,
         'C0302(too-many-lines)': 21,
         'W0108(unnecessary-lambda)': 20,
         'E1120(no-value-for-parameter)': 19,
         'W0601(global-variable-undefined)': 18,
         'C0412(ungrouped-imports)': 17,
         'C0410(multiple-imports)': 14,
         'C0123(unidiomatic-typecheck)': 13,
         'R0904(too-many-public-methods)': 11,
         'E0602(undefined-variable)': 11,
         'C0202(bad-classmethod-argument)': 11,
         'C0303(trailing-whitespace)': 10,
         'W0631(undefined-loop-variable)': 9,
         'W0603(global-statement)': 8,
         'R1708(stop-iteration-return)': 8,
         'W1505(deprecated-method)': 8,
         'W0640(cell-var-from-loop)': 8,
         'E1136(unsubscriptable-object)': 7,
         'R1704(redefined-argument-from-local)': 7,
         'W0406(import-self)': 7,
         'W0101(unreachable)': 7,
         'W0123(eval-used)': 6,
         'E0401(import-error)': 6,
         'R1711(useless-return)': 6,
         'E1121(too-many-function-args)': 6,
         'W0233(non-parent-init-called)': 6,
         'E0102(function-redefined)': 5,
         'W0706(try-except-raise)': 5,
         'W0402(deprecated-module)': 5,
         'C0112(empty-docstring)': 5,
         'R0901(too-many-ancestors)': 5,
         'R1717(consider-using-dict-comprehension)': 5,
         'C0411(wrong-import-order)': 4,
         'W0106(expression-not-assigned)': 4,
         'R1701(consider-merging-isinstance)': 4,
         'E0203(access-member-before-definition)': 4,
         'E1133(not-an-iterable)': 4,
         'R1715(consider-using-get)': 4,
         'W1305(format-combined-specification)': 4,
         'E1102(not-callable)': 4,
         'W0642(self-cls-assignment)': 3,
         'C0305(trailing-newlines)': 3,
         'W0235(useless-super-delegation)': 3,
         'W0107(unnecessary-pass)': 3,
         'R1712(consider-swap-variables)': 3,
         'W0125(using-constant-test)': 2,
         'C0122(misplaced-comparison-constant)': 2,
         'W0623(redefine-in-handler)': 2,
         'W0104(pointless-statement)': 2,
         'E0213(no-self-argument)': 2,
         'W0120(useless-else-on-loop)': 2,
         'R1703(simplifiable-if-statement)': 2,
         'W1113(keyword-arg-before-vararg)': 2,
         'R0916(too-many-boolean-expressions)': 2,
         'E1130(invalid-unary-operand-type)': 2,
         'W0222(signature-differs)': 2,
         'E0302(unexpected-special-method-signature)': 1,
         'W0641(possibly-unused-variable)': 1,
         'W0143(comparison-with-callable)': 1,
         'E0704(misplaced-bare-raise)': 1,
         'W0122(exec-used)': 1,
         'E1305(too-many-format-args)': 1,
         'E0632(unbalanced-tuple-unpacking)': 1,
         'W1202(logging-format-interpolation)': 1})
```

Some of the issues above that isn't solved yet but its worth looking through are: #2113 #2115 #2116 #2118 #2119 #2120 #2121

### CODE REVIEW

**Comment by iliakur** [comment]
I think as a first step we should decide how much we actually trust `pylint`. It's opinionated about a lot of things and I'm not sure I agree with all of them. For instance, forcing people to write docstrings for every single class/method/function ends up creating lots of cruft and conceptual duplication (both result higher maintenance). From personal experience it's much easier to read code that's broken up into very small clearly-named functions (without dostrings!!) than megamethods with equally detailed and elaborate docstrings.

Don't get me wrong: docstrings are immensely useful for public API classes/methods/functions, they really help users understand how to use these. But unfortunately `pylint` doesn't know which stuff is public, so it will indiscriminately demand that we write docstrings for everything.

End of rant. My point is we should critically evaluate what this tool tells us before actually following its recommendations :)

**Comment by alvations** [comment]
Agree. Most of the fixes here are really superficial though. It helps to keep out extra empty lines and not doing silly things like checking for boolean using a tuple and [0]  or [1] access, casting generator into a list before a set and erratic import behaviours. I'll try to summarize when I'm on a desktop. 

Some of the issues highlighted in the previous comments are worth fixing though.

Some pylint suggestions like bad whitespace and too long line are nice but really impractical.

**Comment by alvations** [comment]
Here's a summary of the superficial cleanups in this PR:

 - `C0305` and `C0304`: Ensures that there's only 1 new line created after end of the file. So have multiple, so have none, I think the 1 newline before EOF convention should be easy to keep consistent in the codebase =)
 - `W0104`: The `next` keyword is used to pass on to the next iteration instead of `continue`, corrected that
 - `C0113 `: Changed `not x in y` (checks  `x in y` then negates) to `x not in y` (checks `x not in y`) - Technically both `O(n)` but `not x in y` can end earlier if `x` in not at the end of the list, regardless if `y` is a set, time taken should be quite negligible for sensible length `y`
 - `W0301`: Removed semi-colons at end of line
 - `W0312`: Use spaces instead of tabs in `.py` files where there's a mix of tabs and spaces for indentation. 
 - `W0611`: Removed unused import
 - `R1718`: Remove the list casting when changing a generator into a set
 - `R1706`: This one is where our code gets really weird, there're some cases where the tuple is used to do some sort of boolean checking:
     - Originally: `disc_id = (self.token(), self.discourse_id)[self.discourse_id is not None]`
     - Changed:  `disc_id = self.discourse_id if self.discourse_id is not None else self.token()`

 - `W0233` and `E0102` : these issues were left unfixed but put a `#FIXME` comment
 - `C0411`: Reordered the import order, native packages first, then external dependencies, then NLTK absolute imports
 - `W0702`: Only fixed https://github.com/nltk/nltk/pull/2117/commits/32882ca3ab4703397fe2e0db4d3a268a48617fff where the proper except error type is caught and instead of ending with a bare except, use `finally`.

@Copper-Head @stevenbird I hope the changes made above are logical enough to use pylint as a guide to suggest where we can improve the codebase. I went through each one of the suggestions, so it's not an automated cleanup =)

**Comment by iliakur** [comment]
lgtm! IIRC you can tell pylint which errors you wish to ignore in the future. just to minimize the amount of noise

**Comment by stevenbird** [comment]
Thanks @alvations! This is great.

**Pull request merged**
