### PR TITLE
Map satellite pos to adjective pos for omw, fixing problems with wordnet.lemmmas(...)

### PR DESCRIPTION
**Pull request by frankier**
Before:
```
>>> from nltk.corpus import wordnet
>>> wordnet.lemmas('Ｔ形+的', lang='cmn')
[]
```
After
```:
>>> from nltk.corpus import wordnet
>>> wordnet.lemmas('Ｔ形+的', lang='cmn')
[Lemma('t-shaped.s.01.Ｔ形+的')]
```

### CODE REVIEW

**Comment by stevenbird** [comment]
@frankier is this justified as a global change?
@fcbond would you please confirm?

**Comment by frankier** [comment]
It's justified because:
1. ss2of is only called in one place, lemma_names(...) (which is in turn called by lemmas(...) )
2. Open Multilingual Wordnet is meant to have scrapped the satellite pos tag. I can't find a reference for this any more, but a cursory look at the data will confirm.

Unfortunately, in practice omw does sometimes use the satellite pos tag. The languages that do are: nld, lit and slk. I have been in contact with @fcbond about this already. Given a new release is not forthcoming immediately, this should perhaps be taken into account.

**Comment by frankier** [comment]
Okay. Now I've added an exception which can be removed if/when these languages also remove the satellite tag.

**Comment by stevenbird** [comment]
That looks good, thanks @frankier

**Pull request merged**
