### PR TITLE
enable testing with python 3.6 (do not merge)

### PR DESCRIPTION
**Pull request by purificant**
Enable running tests against python 3.6

### CODE REVIEW

**Comment by stevenbird** [comment]
@purificant: we'll merge this once several known issues for Python 3.6 are resolved, and we can check progress by getting the CI server to retest this PR, without needing to merge just yet.
https://github.com/nltk/nltk/labels/python3

**Comment by purificant** [comment]
Thanks for explaining @stevenbird

**Comment by alvations** [comment]
Anyone working on #1659 ?

**Comment by alvations** [comment]
[CI: retest]

**Comment by alvations** [comment]
[CI: retest]

**Comment by alvations** [comment]
@stevenbird Do we need to setup extra workflow on Jenkins to run Py36 tests?

**Comment by stevenbird** [comment]
@alvations: happy to do this, and see how we get on...

**Comment by alvations** [comment]
@stevenbird looks like the configuration wasn't set up correctly: https://nltk.ci.cloudbees.com/job/nltk/TOXENV=py34-jenkins,jdk=jdk8latestOnlineInstall/763/console =(

**Comment by stevenbird** [comment]
@alvations - yes, trying to work out what I did wrong

**Comment by stevenbird** [comment]
It looks like Python 3.6 is not available, cf https://repository-cloudbees.forge.cloudbees.com/distributions/ci-addons/python/fc17/

I submitted a support request.

**Comment by stevenbird** [comment]
Cloudbees is working on setting up 3.6 but might not be right away. ttps://support.cloudbees.com/hc/requests/56274

**Comment by alvations** [comment]
c.f. https://github.com/nltk/nltk/pull/1942

**Comment by alvations** [comment]
Thanks @purificant for starting this PR! 
The Jenkins server with tox should work on Py3.6 now =)

**Comment by purificant** [comment]
Thanks for the merge, glad to see tests running on py3.6 !

**Pull request merged**
