### PR TITLE
Fixes nonbreaking prefix conditions for MosesTokenizer

### PR DESCRIPTION
**Pull request by alvations**
c.f. #1616

### CODE REVIEW

**Comment by stevenbird** [comment]
Thanks @alvations. Would you please look into the failing check for https://github.com/nltk/nltk/pull/1693/commits/b7c58a3e88b5e70409e556272e18fc7bc936dc8f

**Comment by alvations** [comment]
[CI:retest]

**Comment by alvations** [comment]
[ci:restest]

**Comment by alvations** [comment]
[CI: retest]

**Comment by alvations** [comment]
[CI: retest]

**Comment by alvations** [comment]
@stevenbird The problem seemed to be partly due to the test timeout on the Jenkins. I think this PR shouldn't be merged. I'll recreate another one without the mess in the commit messages =)

I'll leave this open for 1-2 days and when I clean up my git branch, rebase and recommit, I'll close this PR when I request for the new one.

**Comment by alvations** [comment]
It's cool how @Github automatically closes the issue when the branch gets stale after a git rebase is activated to revert the commits =)

**Pull request closed without merging**
