### PR TITLE
fix LazyCorpusLoader for python 3.7+ 

### PR DESCRIPTION
**Pull request by purificant**
This pull request addresses Python 3.7 compatibility issue outlined in: https://github.com/nltk/nltk/issues/2145

### CODE REVIEW

**Comment by purificant** [comment]
Travis build will fail due to https://github.com/nltk/nltk/issues/2144. Once resolved, the build should be green.

**Comment by alvations** [comment]
BTW, travis doesn't support Python 3.7 for their default Ubuntu distributions without `sudo:yes`, see https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905

**Comment by purificant** [comment]
For python 3.7 on travis we can do something like this: https://github.com/nltk/nltk/pull/2142
once the compatibility fixes are in develop in order to produce a green build.

**Comment by stevenbird** [comment]
So if I merge this, are we ready to deal with any fallout on Travis for python 3.7?

**Comment by alvations** [comment]
I'm not sure. But perhaps creating a branch and merging it there to check would be better than merging directly to `develop`.

**Comment by purificant** [comment]
The proposed code changes here only do two things:
- address the python 3.7 compatibility issues outlined in https://github.com/nltk/nltk/issues/2145
- add py37 to tox configuration so that you can run `tox` and verify test execution under python 3.7 in a local dev environment

This PR does not change Travis configuration, so we will not see anything different on Travis, the build will only run for <= 3.6 as before. For example, there is a successful build for this PR here: https://travis-ci.org/nltk/nltk/builds/444056973

That being said, I think this might be the last fix need to get a green Travis build for Python 3.7 and I'd like to propose a new PR to start testing on 3.7 in Travis along the lines of https://github.com/nltk/nltk/pull/2142 once all the fixes are in develop.

I would hold of on merging this at the moment though due to an ongoing GitHub outage, best to wait until the status page confirms that all service is restored: https://status.github.com/messages
For example, webhooks are down at the moment, which means externals builds like Travis won't get triggered and not all comments are visible on the PR as sometimes you are shown an old version.

**Comment by alvations** [comment]
Thanks @purificant  for the detailed explanation!

It passes on all other python versions from the last time it tested so it shouldn't be a problem. But yes, we should wait for github to be back up.

**Comment by alvations** [comment]
Github has resolved their issues, lets try merging this.

We do still have to remember to disable the `sudo` so when travis support it by default.

**Pull request merged**
