### PR TITLE
Pickless-less tagsets helper

### PR DESCRIPTION
**Pull request by alvations**
Instead of loading of tagsets pickle, this PR loads the tagsets_json dataset.

Related: https://github.com/nltk/nltk/issues/3266

### Testing

```
% python3 -m unittest nltk/test/unit/test_pos_tag.py -vvv
test_pos_tag_eng (nltk.test.unit.test_pos_tag.TestPosTag) ... ok
test_pos_tag_eng_universal (nltk.test.unit.test_pos_tag.TestPosTag) ... ok
test_pos_tag_rus (nltk.test.unit.test_pos_tag.TestPosTag) ... ok
test_pos_tag_rus_universal (nltk.test.unit.test_pos_tag.TestPosTag) ... ok
test_pos_tag_unknown_lang (nltk.test.unit.test_pos_tag.TestPosTag) ... ok
test_tagsets_brown (nltk.test.unit.test_pos_tag.TestPosTag) ... ok
test_tagsets_claw5 (nltk.test.unit.test_pos_tag.TestPosTag) ... ok
test_tagsets_upenn (nltk.test.unit.test_pos_tag.TestPosTag) ... ok
test_unspecified_lang (nltk.test.unit.test_pos_tag.TestPosTag) ... ok

----------------------------------------------------------------------
Ran 9 tests in 0.421s

OK
```

### CODE REVIEW

**Review by ekaf — APPROVED** [review]
Looks good:

> test_tagsets_brown (nltk.test.unit.test_pos_tag.TestPosTag.test_tagsets_brown) ... ok
> test_tagsets_claw5 (nltk.test.unit.test_pos_tag.TestPosTag.test_tagsets_claw5) ... ok
> test_tagsets_upenn (nltk.test.unit.test_pos_tag.TestPosTag.test_tagsets_upenn) ... ok
>

**Comment by ekaf** [comment]
@alvations, the CI log shows that black modifies a file:

> black....................................................................Failed
> - hook id: black
> - files were modified by this hook
> 
> reformatted nltk/test/unit/test_pos_tag.py

This indicates that, after running black, you probably forgot to re-run _git add_ and _git commit_ on that file. Using 'git status' would reveal if any file needs to be committed again,

**Comment by alvations** [comment]
[CI: retest]

**Comment by alvations** [comment]
[CI: retest]

**Comment by alvations** [comment]
Thanks @ekaf for checking the PR and catching the black/isort missing.

**Pull request merged**
