### PR TITLE
Fix undefined variable bugs

### PR DESCRIPTION
**Pull request by timleslie**
This pull request identifies and fixes some undefined variable bugs.

It also (as a side effect) makes trailing whitespace in these files pep8 compliant, mostly because my editor does that automatically. If you prefer I can remove all the whitespace changes and just leave the variable changes.

### CODE REVIEW

**Comment by iliakur** [comment]
@timleslie this one commit contains a lot of unrelated changes (variable name changes, whitespace changes, the use of imported modules).
Would you mind splitting all of them up a bit, so that in case a regression is introduced it's easier to identify which commit it comes from?

**Comment by stevenbird** [comment]
I agree. And a more detailed commit message too please! Thanks @timleslie – much appreciated.

**Comment by timleslie** [comment]
No worries, thanks for the feedback, I will make the suggested changes later tonight and let you know when it's ready for another look.

**Comment by timleslie** [comment]
I've removed the whitespace changes from the PR, so hopefully now all the changes are more obvious.

**Comment by stevenbird** [comment]
Thanks @timleslie – much appreciated!

**Pull request merged**
