### PR TITLE
nltk tokenize doctest non-existent import

### PR DESCRIPTION
**Pull request by stevenxxiu**
Removed nltk tokenize doctest non-existent import.

### CODE REVIEW

**Comment by kmike** [comment]
There are also references to this function later in docsting. It seems Steven wanted to rename `wordpunct_tokenize` to `tokenize`, but I'm not sure. @stevenbird - could you please clarify it?

**Comment by kmike** [comment]
(I merged this PR too early, sorry for that)

**Comment by stevenxxiu** [comment]
The doctest seems to work for me, @kmike which ones are you referring to?

**Comment by kmike** [comment]
The references are in text, they don't affect test running:

> This is a simple regular-expression based tokenizer which does not handle
>  periods very well. We can also use a sentence tokenizer (Punkt) and followed
>  by a good sentence-internal word tokenizer (Treebank). The `tokenize()`
>  function combines both of these.

**Comment by stevenbird** [comment]
Thanks for picking this up @kmike. Yes, I intended to create a `tokenize()` function that combined sentence tokenization and sentence-internal word tokenization. The name is unfortunate in colliding with the package name (`nltk.tokenize`) but I think its workable. I'll open a separate issue to make sure we deal with this before nltk3 beta is finalized.

**Pull request merged**
