### PR TITLE
Make floating point division more consistent

### PR DESCRIPTION
**Pull request by mrecachinas**
This addresses #815. Tested to ensure nothing broke. Also, converted integer division to `//`.

### CODE REVIEW

**Comment by mrecachinas** [comment]
There appeared to be a whitespace merge conflict when I rebased off `nltk/develop`, so that would be why the commits are duplicated. I'll try to remove the duplicates.

**Comment by alvations** [comment]
@mrecachinas while you're at it, there's a few more on:

``` bash
alvas@ubi:~/git/nltk$ grep -rn '/ float(' nltk/*
nltk/app/collocations_app.py:330:                scored = [((w1,w2), fd[(w1,w2)] ** 3 / float(vocab[w1] * vocab[w2])) for w1, w2 in fd]
nltk/cluster/kmeans.py:177:            return centroid / float(len(cluster))
nltk/draw/table.py:187:        charwidth = lb.winfo_width() / float(lb['width'])
nltk/metrics/association.py:202:            yield (cont[i] + cont[i ^ 1]) * (cont[i] + cont[i ^ 2]) / float(n_xx)
nltk/metrics/distance.py:137:    return 1 - (len_intersection / float(len_union)) * m
nltk/metrics/agreement.py:183:        ret = float(sum(self.agr(cA, cB, item, item_data) for item, item_data in data)) / float(len(self.I))
nltk/metrics/agreement.py:223:        ret = (1.0 / float((len(self.I) * len(self.C) * (len(self.C) - 1)))) * total
nltk/metrics/agreement.py:255:        Ae = 1.0 / float(len(self.K))
nltk/metrics/agreement.py:268:        Ae = total / float((len(self.I) * len(self.C)) ** 2)
nltk/probability.py:1100:            self._P0 = self._T / float(self._Z * (self._N + self._T))
nltk/probability.py:1105:        return (c / float(self._N + self._T) if c != 0 else self._P0)
nltk/tag/perceptron.py:84:                averaged = round(total / float(self.i), 3)
nltk/tag/tnt.py:271:            return float(v1) / float(v2)
nltk/tag/tnt.py:517:        tp_un = float(t.unknown) / float(t.known +t.unknown)
nltk/tag/tnt.py:518:        tp_kn = float(t.known) / float(t.known + t.unknown)
nltk/tag/tnt.py:529:        sp_un = float(s.unknown) / float(s.known +s.unknown)
nltk/tag/tnt.py:530:        sp_kn = float(s.known) / float(s.known + s.unknown)
nltk/tag/tnt.py:574:        tp_un = float(t.unknown) / float(t.known +t.unknown)
nltk/tag/tnt.py:575:        tp_kn = float(t.known) / float(t.known + t.unknown)
nltk/tag/tnt.py:581:        sp_un = float(s.unknown) / float(s.known + s.unknown)
nltk/tag/tnt.py:582:        sp_kn = float(s.known) / float(s.known + s.unknown)
nltk/translate/ibm3.py:200:                initial_prob = 1 / float(m)
nltk/translate/ibm2.py:149:                initial_prob = 1 / float(l + 1)
```

Also here:

``` bash
alvas@ubi:~/git/nltk$ grep -rn '1.0 \*' nltk/*
nltk/app/rdparser_app.py:809:        dy = (1.0 * (node.bbox()[3] - widget.bbox()[1] + 14) /
nltk/metrics/distance.py:161:    return lambda x, y: 1.0 * ((label in x) == (label in y))
nltk/probability.py:1269:        x_mean = 1.0 * sum(log_r) / len(log_r)
nltk/probability.py:1270:        y_mean = 1.0 * sum(log_zr) / len(log_zr)
nltk/probability.py:1295:            unsmooth_r_star = 1.0 * (r_ + 1) * nr[i+1] / nr[i]
nltk/probability.py:1352:                p = p / (1.0 * self._bins - self._freqdist.B())
nltk/probability.py:1361:            return 1.0 * self._freqdist.Nr(1) / self._freqdist.N()
nltk/probability.py:1364:            Er_1 = 1.0 * self._freqdist.Nr(count+1)
nltk/probability.py:1365:            Er = 1.0 * self._freqdist.Nr(count)
nltk/probability.py:1385:        return  1.0 * self.smoothedNr(1) / self._freqdist.N()
nltk/test/probability.doctest:101:    ...     print('%.2f%%' % (100 * hmm.evaluate(test_corpus)))
nltk/tokenize/punkt.py:1063:        p = 1.0 * count_b / N
nltk/tokenize/punkt.py:1064:        p1 = 1.0 * count_ab / count_a
nltk/tokenize/punkt.py:1065:        p2 = 1.0 * (count_b - count_ab) / (N - count_a)
nltk/translate/ribes_score.py:57:        bp = min(1.0, math.exp(1.0 - 1.0 * len(reference)/len(hypothesis)))
nltk/translate/ribes_score.py:60:        p1 = 1.0 * len(worder) / len(hypothesis)
nltk/translate/ribes_score.py~:57:        bp = min(1.0, math.exp(1.0 - 1.0 * len(reference)/len(hypothesis)))
nltk/translate/ribes_score.py~:60:        p1 = 1.0 * len(worder) / len(hypothesis)
```

and possibly a few of these

``` bash
alvas@ubi:~/git/nltk$ grep -rn '\* 1.0' nltk/*
nltk/app/wordfreq_app.py:17:    values = [sum(values[:i+1]) * 100.0/fd.N() for i in range(len(values))]
nltk/classify/textcat.py:189:        print('#' * 140)
nltk/probability.py:245:        # percents = [f * 100 for f in freqs]  only in ProbDist?
nltk/probability.py:278:        # percents = [f * 100 for f in freqs]  only in ProbDist?
nltk/probability.py:1769:            # percents = [f * 100 for f in freqs] only in ConditionalProbDist?
nltk/tag/perceptron.py:284:    return (float(n) / d) * 100
nltk/tag/hmm.py:807:        print('accuracy over %d tokens: %.2f' % (count, acc * 100))
nltk/tag/sequential.py:203:            backoff = 100 - (hit_count * 100.0)/ token_count
nltk/tag/sequential.py:204:            pruning = 100 - (size * 100.0) / len(fd.conditions())
nltk/test/unit/translate/test_ibm5.py:127:        fertility = 1*0.99 * 1*0.99 * 1*0.99 * 1*0.99 * 2*0.999
nltk/test/unit/translate/test_ibm3.py:100:        fertility = 1*0.99 * 1*0.99 * 1*0.99 * 1*0.99 * 2*0.999
nltk/test/unit/translate/test_ibm4.py:121:        fertility = 1*0.99 * 1*0.99 * 1*0.99 * 1*0.99 * 2*0.999
```

And possibly a few of these too (but some of these are `float(str)`, so do be careful ;P :

``` bash
alvas@ubi:~/git/nltk$ grep -rn 'float(' nltk/*
nltk/app/chunkparser_app.py:943:            self.show_devset(int(float(args[0])*self._devset_size.get()))
nltk/app/chunkparser_app.py:987:        first = float(self.devset_index)/self._devset_size.get()
nltk/app/chunkparser_app.py:988:        last = float(self.devset_index+2)/self._devset_size.get()
nltk/app/chartparser_app.py:1193:                                     float(y-dy)/self._chart_height)
nltk/app/collocations_app.py:330:                scored = [((w1,w2), fd[(w1,w2)] ** 3 / float(vocab[w1] * vocab[w2])) for w1, w2 in fd]
nltk/chunk/util.py:193:        else: return float(self._tp_num) / div
nltk/chunk/util.py:205:        else: return float(self._tp_num) / div
Binary file nltk/chunk/util.pyc matches
nltk/classify/decisiontree.py:72:        return float(errors)/len(labeled_featuresets)
nltk/classify/tadm.py:69:        weights.append(float(line.strip()))
nltk/classify/util.py:84:    return math.log(float(sum(ll))/len(ll))
nltk/classify/util.py:90:        return float(sum(correct))/len(correct)
nltk/classify/weka.py:125:        probs = [float(v) for v in re.split('[*,]+', s) if v.strip()]
nltk/classify/megam.py:137:            weights[int(fid)] = float(weight)
nltk/cluster/gaac.py:112:            centroid /= float(len(cluster))
nltk/cluster/kmeans.py:168:            return centroid / (1+float(len(cluster)))
nltk/cluster/kmeans.py:177:            return centroid / float(len(cluster))
nltk/corpus/reader/reviews.py:174:        >>> mean = float(tot)/n_reviews
nltk/corpus/reader/wordnet.py:692:        inf = float('inf')
nltk/corpus/reader/wordnet.py:1771:            weight = float(counts[ww])
nltk/corpus/reader/wordnet.py:1773:                weight /= float(len(possible_synsets))
nltk/corpus/reader/wordnet.py:1822:            value = float(fields[1])
nltk/corpus/reader/childes.py:252:            numWords = float(len(flatten([word.split('-')
nltk/corpus/reader/childes.py:254:            numSents = float(len(results)) - sentDiscount
Binary file nltk/corpus/reader/lin.pyc matches
nltk/corpus/reader/sentiwordnet.py:66:                self._db[(pos, offset)] = (float(pos_score), float(neg_score))
Binary file nltk/corpus/reader/reviews.pyc matches
nltk/corpus/reader/lin.py:58:                            self._thesaurus[fileid][key][ngram.strip('"')] = float(score)
nltk/downloader.py:571:                delta = float(len(item.packages))/num_packages
nltk/downloader.py:616:                num_blocks = max(1, float(info.size)/(1024*16))
nltk/draw/util.py:957:            return float(self.canvas().itemcget(self._box, attr))
nltk/draw/util.py:1035:            return float(self.canvas().itemcget(self._oval, attr))
nltk/draw/table.py:187:        charwidth = lb.winfo_width() / float(lb['width'])
nltk/grammar.py:1133:                                prob=float(pcount[p]) / lcount[p.lhs()])
nltk/grammar.py:1191:            probabilities[-1] = float(m.group(1)[1:-1])
nltk/internals.py:287:    if m.group(2): return float(m.group()), m.end()
nltk/metrics/spearman.py:38:        return 1 - (6 * float(res) / (n * (n*n - 1)))
nltk/metrics/scores.py:40:    return float(sum(x == y for x, y in izip(reference, test))) / len(test)
nltk/metrics/scores.py:62:        return float(len(reference.intersection(test)))/len(test)
nltk/metrics/scores.py:84:        return float(len(reference.intersection(test)))/len(reference)
nltk/metrics/scores.py:163:    stat = kwargs.get('statistic', lambda lst: float(sum(lst)) / len(lst))
nltk/metrics/scores.py:194:            print('significance: %f' % (float(c + 1) / (i + 1)))
nltk/metrics/scores.py:197:    significance = float(c + 1) / (shuffles + 1)
Binary file nltk/metrics/distance.pyc matches
nltk/metrics/paice.py:106:        return float('inf')
nltk/metrics/paice.py:205:            sw = float('nan')
nltk/metrics/paice.py:208:            sw = float('inf')
nltk/metrics/paice.py:312:                return float('inf')
nltk/metrics/paice.py:314:                return float('nan')
nltk/metrics/association.py:86:                   float(n_all ** (cls._n - 1)))
nltk/metrics/association.py:91:        return float(marginals[NGRAM]) / marginals[TOTAL]
nltk/metrics/association.py:100:                  float(marginals[TOTAL] ** (cls._n - 1))) /
nltk/metrics/association.py:120:                float(_product(marginals[UNIGRAMS])))
nltk/metrics/association.py:136:                sum(obs * _ln(float(obs) / (exp + _SMALL) + _SMALL)
nltk/metrics/association.py:143:               float(marginals[TOTAL] ** (cls._n - 1)))
nltk/metrics/association.py:150:        return float(cont[0]) / sum(cont[:-1])
nltk/metrics/association.py:202:            yield (cont[i] + cont[i ^ 1]) * (cont[i] + cont[i ^ 2]) / float(n_xx)
nltk/metrics/association.py:211:        return (float((n_ii*n_oo - n_io*n_oi)**2) /
nltk/metrics/association.py:238:        return 2 * float(n_ii) / (n_ix + n_xi)
nltk/metrics/distance.py:109:    return (len(label1.union(label2)) - len(label1.intersection(label2)))/float(len(label1.union(label2)))
nltk/metrics/distance.py:137:    return 1 - (len_intersection / float(len_union)) * m
nltk/metrics/distance.py:166:        abs((float(1.0 / len(x)) - float(1.0 / len(y)))) * (label in x and label in y) \
nltk/metrics/distance.py:168:        or abs(float(1.0 / len(x))) * (label in x and label not in y) \
nltk/metrics/distance.py:169:        or (float(1.0 / len(y))) * (label not in x and label in y)
nltk/metrics/distance.py:179:            data[frozenset([labelA,labelB])] = float(dist)
Binary file nltk/metrics/association.pyc matches
Binary file nltk/metrics/paice.pyc matches
nltk/metrics/agreement.py:142:        ret = 1.0 - float(self.distance(k1['labels'], k2['labels']))
nltk/metrics/agreement.py:150:        return float(sum(1 for x in self.data if x['labels'] == k))
nltk/metrics/agreement.py:153:        return float(sum(1 for x in self.data if x['item'] == i and x['labels'] == k))
nltk/metrics/agreement.py:156:        return float(sum(1 for x in self.data if x['coder'] == c and x['labels'] == k))
nltk/metrics/agreement.py:183:        ret = float(sum(self.agr(cA, cB, item, item_data) for item, item_data in data)) / float(len(self.I))
nltk/metrics/agreement.py:222:                    total += float(nj * nl) * self.distance(l, j)
nltk/metrics/agreement.py:223:        ret = (1.0 / float((len(self.I) * len(self.C) * (len(self.C) - 1)))) * total
nltk/metrics/agreement.py:255:        Ae = 1.0 / float(len(self.K))
nltk/metrics/agreement.py:268:        Ae = total / float((len(self.I) * len(self.C)) ** 2)
nltk/metrics/agreement.py:273:        nitems = float(len(self.I))
nltk/metrics/agreement.py:313:                De += float(nj * label_freqs[l]) * self.distance(j, l)
nltk/probability.py:54:_NINF = float('-1e300')
nltk/probability.py:197:        return float(self[sample]) / self.N()
nltk/probability.py:692:        self._gamma = float(gamma)
nltk/probability.py:1100:            self._P0 = self._T / float(self._Z * (self._N + self._T))
nltk/probability.py:1105:        return (c / float(self._N + self._T) if c != 0 else self._P0)
nltk/probability.py:1303:        r = float(r)
nltk/probability.py:1304:        nr = float(nr)
nltk/probability.py:1305:        nr_1 = float(nr_1)
nltk/probability.py:1452:            return float('-inf')
Binary file nltk/probability.pyc matches
nltk/sentiment/vader.py:212:                lex_dict[word] = float(measure)
nltk/sentiment/vader.py:402:                pos_sum += (float(sentiment_score) +1) # compensates for neutral words that are counted as 1
nltk/sentiment/vader.py:404:                neg_sum += (float(sentiment_score) -1) # when used with math.fabs(), compensates for neutrals
nltk/sentiment/vader.py:411:            sum_s = float(sum(sentiments))
nltk/tag/perceptron.py:84:                averaged = round(total / float(self.i), 3)
nltk/tag/perceptron.py:279:            if n >= freq_thresh and (float(mode) / n) >= ambiguity_thresh:
nltk/tag/perceptron.py:284:    return (float(n) / d) * 100
nltk/tag/tnt.py:240:                    tl2 += float(self._tri[history][tag]) /2.0
nltk/tag/tnt.py:241:                    tl3 += float(self._tri[history][tag]) /2.0
nltk/tag/tnt.py:246:                    tl1 += float(self._tri[history][tag]) /2.0
nltk/tag/tnt.py:247:                    tl2 += float(self._tri[history][tag]) /2.0
nltk/tag/tnt.py:271:            return float(v1) / float(v2)
nltk/tag/tnt.py:370:                    p_wd = float(self._wd[word][t])/float(self._uni[(t,C)])
nltk/tag/tnt.py:517:        tp_un = float(t.unknown) / float(t.known +t.unknown)
nltk/tag/tnt.py:518:        tp_kn = float(t.known) / float(t.known + t.unknown)
nltk/tag/tnt.py:529:        sp_un = float(s.unknown) / float(s.known +s.unknown)
nltk/tag/tnt.py:530:        sp_kn = float(s.known) / float(s.known + s.unknown)
nltk/tag/tnt.py:574:        tp_un = float(t.unknown) / float(t.known +t.unknown)
nltk/tag/tnt.py:575:        tp_kn = float(t.known) / float(t.known + t.unknown)
nltk/tag/tnt.py:581:        sp_un = float(s.unknown) / float(s.known + s.unknown)
nltk/tag/tnt.py:582:        sp_kn = float(s.known) / float(s.known + s.unknown)
nltk/test/corpus.doctest:643:    >>> mean = float(tot)/n_reviews
nltk/text.py:568:            idf = (log(float(len(self._texts)) / matches) if matches else 0.0)
Binary file nltk/text.pyc matches
nltk/tokenize/punkt.py:1039:        p1 = float(count_b) / N
nltk/tokenize/punkt.py:1042:        null_hypo = (float(count_ab) * math.log(p1) +
nltk/tokenize/punkt.py:1044:        alt_hypo  = (float(count_ab) * math.log(p2) +
nltk/tokenize/punkt.py:1129:                    (float(self._type_fdist.N())/typ1_count >
nltk/tokenize/punkt.py:1130:                     float(typ2_count)/col_count)):
nltk/tokenize/punkt.py:1169:                float(self._type_fdist.N())/self._sentbreak_count >
nltk/tokenize/punkt.py:1170:                float(typ_count)/typ_at_break_count):
nltk/translate/ibm3.py:200:                initial_prob = 1 / float(m)
nltk/translate/old-mert.py:70:            map[thiskey].append(float(element))
nltk/translate/ibm_model.py:450:        average_position = float(sum(self.cepts[i])) / len(self.cepts[i])
nltk/translate/gale_church.py:55:            return float('-inf')
nltk/translate/gale_church.py:114:        return float('-inf')
nltk/translate/gale_church.py:146:            min_dist = float('inf')
nltk/translate/gale_church.py:158:            if min_dist == float('inf'):
nltk/translate/metrics.py:38:    return (1.0 - float(len(hypothesis & reference) + len(hypothesis & possible)) /
nltk/translate/metrics.py:39:            float(len(hypothesis) + len(reference)))
nltk/translate/stack_decoder.py:232:        scores = defaultdict(lambda: defaultdict(lambda: float('-inf')))
nltk/translate/stack_decoder.py:453:            self.__log_beam_threshold = float('-inf')
nltk/translate/ibm2.py:149:                initial_prob = 1 / float(l + 1)
nltk/translate/mert.py:40:            reference2nbest[int(sentid)].append((translation, params, float(score)))
nltk/translate/ibm5.py:278:        if max_m > 0 and (float(1) / (2 * max_m)) < IBMModel.MIN_PROB:
nltk/translate/ibm4.py:264:            initial_prob = float(1) / (2 * (max_m - 1))
```

Thanks @mrecachinas !

**Comment by mrecachinas** [comment]
@alvations Thanks -- will do!

**Comment by stevenbird** [comment]
Thanks @mrecachinas, @alvations!

**Comment by mrecachinas** [comment]
@alvations Little regex fix that got me a few times -- escaping the dot -- `grep -rn '1.0 \*' nltk/*` -> `grep -rn '1\.0 \*' nltk/*. Otherwise,`100` matches the first one. :)

**Comment by mrecachinas** [comment]
@stevenbird This should be ready to go. I believe I have tested everything. If not, I've structured the commits in such a way that it will be easy to revert any that fail (due to possible `int` division misses).

Thanks for the suggestions @alvations!

**Comment by stevenbird** [comment]
This is great, @mrecachinas! Thanks for helping us bring NLTK up-to-date. Fingers crossed that there's no failures, or that our regression tests find them. I'll merge and then check the result on the CI server later.

**Comment by mrecachinas** [comment]
@stevenbird Not a problem :+1:  -- if there are any failures, let me know what/where and I'll take a look.

**Pull request merged**
