### PR TITLE
specify tagset for russian tagger in tag init documentation

### PR DESCRIPTION
**Pull request by tsolakghukasyan**
Specifies the tagset for the russian tagger and adds an example in tag/init's documentation.

### CODE REVIEW

**Comment by tsolakghukasyan** [comment]
the code example in docs caused build errors (probably because the russian model was not installed), so I removed it.

**Comment by stevenbird** [comment]
Hi @tsolakghukasyan, sorry for the delay. How about you say something about the tagger in the documentation still, so that people know it is available. E.g. mention that a russian tagger is available if you specify `lang="rus"` etc.

**Comment by tsolakghukasyan** [comment]
Hi @stevenbird,

Edited the documentation according to your suggestion. I also added the doc example back but with a "# doctest: +SKIP" to avoid build errors.

**Comment by stevenbird** [comment]
Thanks @tsolakghukasyan

**Pull request merged**
