### PR TITLE
Fix CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by NQNStudios**
This simply changes the documentation so other contributors won't run into my problem with #2195.

### CODE REVIEW

**Comment by purificant** [comment]
Should the docs specify `all` for data downloads, or should we amend `tests` to actually include all the necessary data for tests?

Any thoughts @alvations?

**Comment by NQNStudios** [comment]
The test_output.txt I uploaded to my issue report should contain all the
information needed to make that fix. If we do, we should change
CONTRIBUTING.md to note that when writing tests, the necessary files should
be added to the `tests` download list to prevent this from becoming an
evergreen bug.

**Comment by purificant** [comment]
This is a valid issue, as any new contributor is likely to run into it by following the docs. Hat off to @NQNStudios for identifying the issue and proposing a fix.

If `python -m nltk.downloader tests` is replaced with `python -m nltk.downloader all` in the docs, will that essentially make `tests` obsolete? Why was only a subset of data installed for tests previously and not all of the available data?

**Comment by NQNStudios** [comment]
Would you like me to measure how much file size is added by using `all` instead of `tests`? In any case, I'm also happy to update the `tests` resource list to add what's needed, or remove it if `all` is the way to go.

**Comment by alvations** [comment]
@purificant @NQNStudios @Copper-Head yes, since the CI is already using `nltk.download('all')` https://github.com/nltk/nltk/blob/develop/tools/travis/install.sh#L10 , it makes sense that contributors should start testing with a similar environment as the CI. 

Until we find a better way to handle and separate test-needed data from all, downloading `all` nltk_data seems to be necessary for contributors to get through the testing with ease.

**Review by alvations — APPROVED** [review]

**Comment by alvations** [comment]
Thanks @NQNStudios for raising this! Thanks @purificant for following up!

**Pull request merged**
